../../target/tran/tr_mgr.o: tr_mgr.c ../platform/procdefs.h \
  ../util/status.h base.h ../rpc/rpc.h \
  /usr/include/libxml2/libxml/xmlstring.h \
  /usr/include/libxml2/libxml/xmlversion.h \
  /usr/include/libxml2/libxml/xmlexports.h ../base/buf.h ../util/xmlns.h \
  ../util/dlq.h ../util/xml_util.h \
  /usr/include/libxml2/libxml/xmlreader.h \
  /usr/include/libxml2/libxml/tree.h \
  /usr/include/libxml2/libxml/xmlstring.h \
  /usr/include/libxml2/libxml/xmlregexp.h \
  /usr/include/libxml2/libxml/dict.h \
  /usr/include/libxml2/libxml/xmlmemory.h \
  /usr/include/libxml2/libxml/threads.h \
  /usr/include/libxml2/libxml/globals.h \
  /usr/include/libxml2/libxml/parser.h /usr/include/libxml2/libxml/hash.h \
  /usr/include/libxml2/libxml/valid.h \
  /usr/include/libxml2/libxml/xmlerror.h \
  /usr/include/libxml2/libxml/list.h \
  /usr/include/libxml2/libxml/xmlautomata.h \
  /usr/include/libxml2/libxml/entities.h \
  /usr/include/libxml2/libxml/encoding.h \
  /usr/include/libxml2/libxml/xmlIO.h /usr/include/libxml2/libxml/SAX.h \
  /usr/include/libxml2/libxml/xlink.h /usr/include/libxml2/libxml/SAX2.h \
  /usr/include/libxml2/libxml/relaxng.h \
  /usr/include/libxml2/libxml/xmlschemas.h ../ncx/ncxconst.h ../base/op.h \
  ../ncx/ps.h ../ncx/psd.h ../ncx/typ.h ../ncx/tk.h ../ncx/val.h xml.h
