
/*****************************************************************************************************
 * Copyright (C) 2017-2022 by Intrising
 *  - ian0113@intrising.com.tw
 * 
 * Generated by protoc-gen-yang@gen-yang
 * 
 *****************************************************************************************************/

#include <libxml/xmlstring.h>
#include "agt.h"
#include "agt_cb.h"
#include "agt_rpc.h"
#include "agt_timer.h"
#include "agt_util.h"
#include "dlq.h"
#include "ncx.h"
#include "ncx_feature.h"
#include "ncxmod.h"
#include "ncxtypes.h"
#include "procdefs.h"
#include "rpc.h"
#include "ses.h"
#include "status.h"
#include "val.h"
#include "val_util.h"
#include "xml_util.h"

#include "intri-time@2022-06-24.h"
#include "../../../../../../../../.libintrishare/libintrishare.h"
#include "../../../../../../genc-trans/github.com/Intrising/intri-type/common/intri-common-trans.h"
#include "../../../../../../genc-trans/github.com/Intrising/intri-type/core/time/intri-time-trans.h"
#include "../../../../../../genc-trans/github.com/golang/protobuf/ptypes/empty/intri-empty-trans.h"
#include "../../../../../../genc-trans/github.com/golang/protobuf/ptypes/timestamp/intri-timestamp-trans.h"

static ncx_module_t *intri_time_mod;
static obj_template_t *intri_time_GetConfig_obj;
static obj_template_t *intri_time_SetConfig_obj;
static obj_template_t *intri_time_GetStatus_obj;
static obj_template_t *intri_time_GetTimeDate_obj;
static obj_template_t *intri_time_RunSyncNow_obj;
static obj_template_t *intri_time_RunListTimeZones_obj;
static obj_template_t *intri_time_GetCorrectionTime_obj;
static obj_template_t *intri_time_GetCorrectionTimeWithInt64_obj;
static obj_template_t *intri_time_GetUTC_obj;

static status_t intri_time_Time_GetConfig_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct emptypb_Empty in;
  struct timepb_Config out;
  time_Time_GetConfig(&in, &out);
  val_value_t *resval = val_new_value();
  res =  build_to_xml_time_Config(
      resval,
    &out);
  return res;
}

static status_t intri_time_Time_SetConfig_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct timepb_Config in;
  struct emptypb_Empty out;
  time_Time_SetConfig(&in, &out);
  val_value_t *resval = val_new_value();
  return res;
}

static status_t intri_time_Time_GetStatus_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct emptypb_Empty in;
  struct timepb_Status out;
  time_Time_GetStatus(&in, &out);
  val_value_t *resval = val_new_value();
  res =  build_to_xml_time_Status(
      resval,
    &out);
  return res;
}

static status_t intri_time_Time_GetTimeDate_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct emptypb_Empty in;
  struct commonpb_DateTime out;
  time_Time_GetTimeDate(&in, &out);
  val_value_t *resval = val_new_value();
  res =  build_to_xml_common_DateTime(
      resval,
    &out);
  return res;
}

static status_t intri_time_Time_RunSyncNow_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct emptypb_Empty in;
  struct emptypb_Empty out;
  time_Time_RunSyncNow(&in, &out);
  val_value_t *resval = val_new_value();
  return res;
}

static status_t intri_time_Time_RunListTimeZones_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct emptypb_Empty in;
  struct timepb_ListTimeZones out;
  time_Time_RunListTimeZones(&in, &out);
  val_value_t *resval = val_new_value();
  res =  build_to_xml_time_ListTimeZones(
      resval,
    &out);
  return res;
}

static status_t intri_time_Time_GetCorrectionTime_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct timepb_RequestWithTimestamp in;
  struct timepb_Response out;
  time_Time_GetCorrectionTime(&in, &out);
  val_value_t *resval = val_new_value();
  res =  build_to_xml_time_Response(
      resval,
    &out);
  return res;
}

static status_t intri_time_Time_GetCorrectionTimeWithInt64_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct timepb_RequestWithInt64 in;
  struct timepb_Response out;
  time_Time_GetCorrectionTimeWithInt64(&in, &out);
  val_value_t *resval = val_new_value();
  res =  build_to_xml_time_Response(
      resval,
    &out);
  return res;
}

static status_t intri_time_Time_GetUTC_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct emptypb_Empty in;
  struct timepb_Response out;
  time_Time_GetUTC(&in, &out);
  val_value_t *resval = val_new_value();
  res =  build_to_xml_time_Response(
      resval,
    &out);
  return res;
}

status_t y_intri_time_init(
    const xmlChar *modname,
    const xmlChar *revision) {
  status_t res = NO_ERR;
  agt_profile_t *agt_profile = agt_get_profile();

  if (xml_strcmp(modname, y_M_intri_time)) {
    return ERR_NCX_UNKNOWN_MODULE;
  }

  if (revision && xml_strcmp(revision, y_R_intri_time)) {
    return ERR_NCX_WRONG_VERSION;
  }

  res = ncxmod_load_module(
      y_M_intri_time,
      y_R_intri_time,
      &agt_profile->agt_savedevQ,
      &intri_time_mod);
  if (res != NO_ERR) {
    return res;
  }

  intri_time_GetConfig_obj = ncx_find_object(
      intri_time_mod,
      "intri-time-GetConfig");
  if (intri_time_GetConfig_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_time,
      "intri-time-GetConfig",
      AGT_RPC_PH_INVOKE,
      intri_time_Time_GetConfig_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_time_SetConfig_obj = ncx_find_object(
      intri_time_mod,
      "intri-time-SetConfig");
  if (intri_time_SetConfig_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_time,
      "intri-time-SetConfig",
      AGT_RPC_PH_INVOKE,
      intri_time_Time_SetConfig_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_time_GetStatus_obj = ncx_find_object(
      intri_time_mod,
      "intri-time-GetStatus");
  if (intri_time_GetStatus_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_time,
      "intri-time-GetStatus",
      AGT_RPC_PH_INVOKE,
      intri_time_Time_GetStatus_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_time_GetTimeDate_obj = ncx_find_object(
      intri_time_mod,
      "intri-time-GetTimeDate");
  if (intri_time_GetTimeDate_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_time,
      "intri-time-GetTimeDate",
      AGT_RPC_PH_INVOKE,
      intri_time_Time_GetTimeDate_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_time_RunSyncNow_obj = ncx_find_object(
      intri_time_mod,
      "intri-time-RunSyncNow");
  if (intri_time_RunSyncNow_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_time,
      "intri-time-RunSyncNow",
      AGT_RPC_PH_INVOKE,
      intri_time_Time_RunSyncNow_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_time_RunListTimeZones_obj = ncx_find_object(
      intri_time_mod,
      "intri-time-RunListTimeZones");
  if (intri_time_RunListTimeZones_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_time,
      "intri-time-RunListTimeZones",
      AGT_RPC_PH_INVOKE,
      intri_time_Time_RunListTimeZones_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_time_GetCorrectionTime_obj = ncx_find_object(
      intri_time_mod,
      "intri-time-GetCorrectionTime");
  if (intri_time_GetCorrectionTime_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_time,
      "intri-time-GetCorrectionTime",
      AGT_RPC_PH_INVOKE,
      intri_time_Time_GetCorrectionTime_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_time_GetCorrectionTimeWithInt64_obj = ncx_find_object(
      intri_time_mod,
      "intri-time-GetCorrectionTimeWithInt64");
  if (intri_time_GetCorrectionTimeWithInt64_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_time,
      "intri-time-GetCorrectionTimeWithInt64",
      AGT_RPC_PH_INVOKE,
      intri_time_Time_GetCorrectionTimeWithInt64_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_time_GetUTC_obj = ncx_find_object(
      intri_time_mod,
      "intri-time-GetUTC");
  if (intri_time_GetUTC_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_time,
      "intri-time-GetUTC",
      AGT_RPC_PH_INVOKE,
      intri_time_Time_GetUTC_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  return res;
}

void y_intri_time_cleanup(void) {
  agt_rpc_unregister_method(
      y_M_intri_time,
      "intri-time-GetConfig");

  agt_rpc_unregister_method(
      y_M_intri_time,
      "intri-time-SetConfig");

  agt_rpc_unregister_method(
      y_M_intri_time,
      "intri-time-GetStatus");

  agt_rpc_unregister_method(
      y_M_intri_time,
      "intri-time-GetTimeDate");

  agt_rpc_unregister_method(
      y_M_intri_time,
      "intri-time-RunSyncNow");

  agt_rpc_unregister_method(
      y_M_intri_time,
      "intri-time-RunListTimeZones");

  agt_rpc_unregister_method(
      y_M_intri_time,
      "intri-time-GetCorrectionTime");

  agt_rpc_unregister_method(
      y_M_intri_time,
      "intri-time-GetCorrectionTimeWithInt64");

  agt_rpc_unregister_method(
      y_M_intri_time,
      "intri-time-GetUTC");

}

