
/*****************************************************************************************************
 * Copyright (C) 2017-2022 by Intrising
 *  - ian0113@intrising.com.tw
 * 
 * Generated by protoc-gen-yang@gen-yang
 * 
 *****************************************************************************************************/

#include <libxml/xmlstring.h>
#include "agt.h"
#include "agt_cb.h"
#include "agt_rpc.h"
#include "agt_timer.h"
#include "agt_util.h"
#include "dlq.h"
#include "ncx.h"
#include "ncx_feature.h"
#include "ncxmod.h"
#include "ncxtypes.h"
#include "procdefs.h"
#include "rpc.h"
#include "ses.h"
#include "status.h"
#include "val.h"
#include "val_util.h"
#include "xml_util.h"

#include "intri-device@2022-06-24.h"
#include "../../../../../../../.libintrishare/libintrishare.h"
#include "../../../../../genc-trans/github.com/Intrising/intri-type/common/intri-common-trans.h"
#include "../../../../../genc-trans/github.com/Intrising/intri-type/device/intri-device-trans.h"
#include "../../../../../genc-trans/github.com/golang/protobuf/ptypes/empty/intri-empty-trans.h"

static ncx_module_t *intri_device_mod;
static obj_template_t *intri_device_GetMACAddress_obj;
static obj_template_t *intri_device_GetPortLists_obj;
static obj_template_t *intri_device_GetLAGPortLists_obj;
static obj_template_t *intri_device_GetPoEPortLists_obj;
static obj_template_t *intri_device_GetHardwareTableSize_obj;
static obj_template_t *intri_device_GetDeviceInfo_obj;
static obj_template_t *intri_device_GetBoardInfo_obj;
static obj_template_t *intri_device_GetHardwareInfo_obj;
static obj_template_t *intri_device_GetFunctionControl_obj;
static obj_template_t *intri_device_GetBoundary_obj;
static obj_template_t *intri_device_GetPath_obj;
static obj_template_t *intri_device_GetTimeControlInfo_obj;

static status_t intri_device_Device_GetMACAddress_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct emptypb_Empty in;
  struct commonpb_MACAddress out;
  device_Device_GetMACAddress(&in, &out);
  val_value_t *resval = val_new_value();
  res =  build_to_xml_common_MACAddress(
      resval,
    &out);
  return res;
}

static status_t intri_device_Device_GetPortLists_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct emptypb_Empty in;
  struct devicepb_PortList out;
  device_Device_GetPortLists(&in, &out);
  val_value_t *resval = val_new_value();
  res =  build_to_xml_device_PortList(
      resval,
    &out);
  return res;
}

static status_t intri_device_Device_GetLAGPortLists_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct emptypb_Empty in;
  struct devicepb_PortList out;
  device_Device_GetLAGPortLists(&in, &out);
  val_value_t *resval = val_new_value();
  res =  build_to_xml_device_PortList(
      resval,
    &out);
  return res;
}

static status_t intri_device_Device_GetPoEPortLists_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct emptypb_Empty in;
  struct devicepb_PortList out;
  device_Device_GetPoEPortLists(&in, &out);
  val_value_t *resval = val_new_value();
  res =  build_to_xml_device_PortList(
      resval,
    &out);
  return res;
}

static status_t intri_device_Device_GetHardwareTableSize_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct emptypb_Empty in;
  struct devicepb_HardwareTableSize out;
  device_Device_GetHardwareTableSize(&in, &out);
  val_value_t *resval = val_new_value();
  res =  build_to_xml_device_HardwareTableSize(
      resval,
    &out);
  return res;
}

static status_t intri_device_Device_GetDeviceInfo_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct emptypb_Empty in;
  struct devicepb_Info out;
  device_Device_GetDeviceInfo(&in, &out);
  val_value_t *resval = val_new_value();
  res =  build_to_xml_device_Info(
      resval,
    &out);
  return res;
}

static status_t intri_device_Device_GetBoardInfo_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct emptypb_Empty in;
  struct devicepb_BoardInfo out;
  device_Device_GetBoardInfo(&in, &out);
  val_value_t *resval = val_new_value();
  res =  build_to_xml_device_BoardInfo(
      resval,
    &out);
  return res;
}

static status_t intri_device_Device_GetHardwareInfo_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct emptypb_Empty in;
  struct devicepb_HardwareInfo out;
  device_Device_GetHardwareInfo(&in, &out);
  val_value_t *resval = val_new_value();
  res =  build_to_xml_device_HardwareInfo(
      resval,
    &out);
  return res;
}

static status_t intri_device_Device_GetFunctionControl_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct emptypb_Empty in;
  struct devicepb_FunctionControlAll out;
  device_Device_GetFunctionControl(&in, &out);
  val_value_t *resval = val_new_value();
  res =  build_to_xml_device_FunctionControlAll(
      resval,
    &out);
  return res;
}

static status_t intri_device_Device_GetBoundary_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct emptypb_Empty in;
  struct devicepb_BoundaryAll out;
  device_Device_GetBoundary(&in, &out);
  val_value_t *resval = val_new_value();
  res =  build_to_xml_device_BoundaryAll(
      resval,
    &out);
  return res;
}

static status_t intri_device_Device_GetPath_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct emptypb_Empty in;
  struct devicepb_PathAll out;
  device_Device_GetPath(&in, &out);
  val_value_t *resval = val_new_value();
  res =  build_to_xml_device_PathAll(
      resval,
    &out);
  return res;
}

static status_t intri_device_Device_GetTimeControlInfo_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct emptypb_Empty in;
  struct devicepb_TimeControlInfo out;
  device_Device_GetTimeControlInfo(&in, &out);
  val_value_t *resval = val_new_value();
  res =  build_to_xml_device_TimeControlInfo(
      resval,
    &out);
  return res;
}

status_t y_intri_device_init(
    const xmlChar *modname,
    const xmlChar *revision) {
  status_t res = NO_ERR;
  agt_profile_t *agt_profile = agt_get_profile();

  if (xml_strcmp(modname, y_M_intri_device)) {
    return ERR_NCX_UNKNOWN_MODULE;
  }

  if (revision && xml_strcmp(revision, y_R_intri_device)) {
    return ERR_NCX_WRONG_VERSION;
  }

  res = ncxmod_load_module(
      y_M_intri_device,
      y_R_intri_device,
      &agt_profile->agt_savedevQ,
      &intri_device_mod);
  if (res != NO_ERR) {
    return res;
  }

  intri_device_GetMACAddress_obj = ncx_find_object(
      intri_device_mod,
      "intri-device-GetMACAddress");
  if (intri_device_GetMACAddress_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_device,
      "intri-device-GetMACAddress",
      AGT_RPC_PH_INVOKE,
      intri_device_Device_GetMACAddress_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_device_GetPortLists_obj = ncx_find_object(
      intri_device_mod,
      "intri-device-GetPortLists");
  if (intri_device_GetPortLists_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_device,
      "intri-device-GetPortLists",
      AGT_RPC_PH_INVOKE,
      intri_device_Device_GetPortLists_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_device_GetLAGPortLists_obj = ncx_find_object(
      intri_device_mod,
      "intri-device-GetLAGPortLists");
  if (intri_device_GetLAGPortLists_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_device,
      "intri-device-GetLAGPortLists",
      AGT_RPC_PH_INVOKE,
      intri_device_Device_GetLAGPortLists_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_device_GetPoEPortLists_obj = ncx_find_object(
      intri_device_mod,
      "intri-device-GetPoEPortLists");
  if (intri_device_GetPoEPortLists_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_device,
      "intri-device-GetPoEPortLists",
      AGT_RPC_PH_INVOKE,
      intri_device_Device_GetPoEPortLists_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_device_GetHardwareTableSize_obj = ncx_find_object(
      intri_device_mod,
      "intri-device-GetHardwareTableSize");
  if (intri_device_GetHardwareTableSize_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_device,
      "intri-device-GetHardwareTableSize",
      AGT_RPC_PH_INVOKE,
      intri_device_Device_GetHardwareTableSize_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_device_GetDeviceInfo_obj = ncx_find_object(
      intri_device_mod,
      "intri-device-GetDeviceInfo");
  if (intri_device_GetDeviceInfo_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_device,
      "intri-device-GetDeviceInfo",
      AGT_RPC_PH_INVOKE,
      intri_device_Device_GetDeviceInfo_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_device_GetBoardInfo_obj = ncx_find_object(
      intri_device_mod,
      "intri-device-GetBoardInfo");
  if (intri_device_GetBoardInfo_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_device,
      "intri-device-GetBoardInfo",
      AGT_RPC_PH_INVOKE,
      intri_device_Device_GetBoardInfo_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_device_GetHardwareInfo_obj = ncx_find_object(
      intri_device_mod,
      "intri-device-GetHardwareInfo");
  if (intri_device_GetHardwareInfo_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_device,
      "intri-device-GetHardwareInfo",
      AGT_RPC_PH_INVOKE,
      intri_device_Device_GetHardwareInfo_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_device_GetFunctionControl_obj = ncx_find_object(
      intri_device_mod,
      "intri-device-GetFunctionControl");
  if (intri_device_GetFunctionControl_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_device,
      "intri-device-GetFunctionControl",
      AGT_RPC_PH_INVOKE,
      intri_device_Device_GetFunctionControl_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_device_GetBoundary_obj = ncx_find_object(
      intri_device_mod,
      "intri-device-GetBoundary");
  if (intri_device_GetBoundary_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_device,
      "intri-device-GetBoundary",
      AGT_RPC_PH_INVOKE,
      intri_device_Device_GetBoundary_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_device_GetPath_obj = ncx_find_object(
      intri_device_mod,
      "intri-device-GetPath");
  if (intri_device_GetPath_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_device,
      "intri-device-GetPath",
      AGT_RPC_PH_INVOKE,
      intri_device_Device_GetPath_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_device_GetTimeControlInfo_obj = ncx_find_object(
      intri_device_mod,
      "intri-device-GetTimeControlInfo");
  if (intri_device_GetTimeControlInfo_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_device,
      "intri-device-GetTimeControlInfo",
      AGT_RPC_PH_INVOKE,
      intri_device_Device_GetTimeControlInfo_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  return res;
}

void y_intri_device_cleanup(void) {
  agt_rpc_unregister_method(
      y_M_intri_device,
      "intri-device-GetMACAddress");

  agt_rpc_unregister_method(
      y_M_intri_device,
      "intri-device-GetPortLists");

  agt_rpc_unregister_method(
      y_M_intri_device,
      "intri-device-GetLAGPortLists");

  agt_rpc_unregister_method(
      y_M_intri_device,
      "intri-device-GetPoEPortLists");

  agt_rpc_unregister_method(
      y_M_intri_device,
      "intri-device-GetHardwareTableSize");

  agt_rpc_unregister_method(
      y_M_intri_device,
      "intri-device-GetDeviceInfo");

  agt_rpc_unregister_method(
      y_M_intri_device,
      "intri-device-GetBoardInfo");

  agt_rpc_unregister_method(
      y_M_intri_device,
      "intri-device-GetHardwareInfo");

  agt_rpc_unregister_method(
      y_M_intri_device,
      "intri-device-GetFunctionControl");

  agt_rpc_unregister_method(
      y_M_intri_device,
      "intri-device-GetBoundary");

  agt_rpc_unregister_method(
      y_M_intri_device,
      "intri-device-GetPath");

  agt_rpc_unregister_method(
      y_M_intri_device,
      "intri-device-GetTimeControlInfo");

}

