// Code generated by protoc-gen-yang(*.c) DO NOT EDIT.

/*****************************************************************************************************
 * Copyright (C) 2017-2022 by Intrising
 *  - ian0113@intrising.com.tw
 * 
 * Generated by protoc-gen-yang@gen-yang
 * 
 *****************************************************************************************************/

#include <libxml/xmlstring.h>
#include "agt.h"
#include "agt_cb.h"
#include "agt_rpc.h"
#include "agt_timer.h"
#include "agt_util.h"
#include "dlq.h"
#include "ncx.h"
#include "ncx_feature.h"
#include "ncxmod.h"
#include "ncxtypes.h"
#include "procdefs.h"
#include "rpc.h"
#include "ses.h"
#include "status.h"
#include "val.h"
#include "val_util.h"
#include "xml_util.h"

#include "sercom-log@2022-06-24.h"
#include "../../../../../../../.libintrishare/libintrishare.h"

#include "../../../../../realize/github.com/Intrising/intri-type/common/sercom-common@2022-06-24.h"
#include "../../../../../realize/github.com/Intrising/intri-type/event/sercom-event@2022-06-24.h"
#include "../../../../../realize/github.com/golang/protobuf/ptypes/empty/sercom-empty@2022-06-24.h"
#include "../../../../../realize/github.com/golang/protobuf/ptypes/timestamp/sercom-timestamp@2022-06-24.h"

#include "../../../../../genc-trans/github.com/Intrising/intri-type/common/intri-common-trans.h"
#include "../../../../../genc-trans/github.com/Intrising/intri-type/event/intri-event-trans.h"
#include "../../../../../genc-trans/github.com/Intrising/intri-type/log/intri-log-trans.h"
#include "../../../../../genc-trans/github.com/golang/protobuf/ptypes/empty/intri-empty-trans.h"
#include "../../../../../genc-trans/github.com/golang/protobuf/ptypes/timestamp/intri-timestamp-trans.h"

static ncx_module_t *intri_log_mod;

static status_t intri_log_Log_GetConfig_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct emptypb_Empty *in = malloc(sizeof(*in));
  struct logpb_Config *out = malloc(sizeof(*out));
  GoString *errstr = malloc(sizeof(*errstr));

  errstr->n = 0;
  log_Log_GetConfig(in, out, errstr);
  if (errstr->n >0) {
    const xmlChar *errorstr = NULL;
    val_value_t *errorval = NULL;
    ncx_errinfo_t *errinfo = ncx_new_errinfo();
    errinfo->error_message = (xmlChar*)(errstr->p);
    res = ERR_NCX_INVALID_VALUE;
    agt_record_error_errinfo(
        scb,
        &msg->mhdr,
        NCX_LAYER_RPC,
        res,
        methnode,
        NCX_NT_NONE,
        errorstr,
        NCX_NT_NONE,
        errorval,
        errinfo);
    log_debug("err= %s", errstr->p);
    free(in);
    free(out);
    free(errstr);
    return res;
  }

  obj_template_t *outobj = obj_find_child(
      msg->rpc_method,
      y_M_intri_log,
      "output");
  val_value_t *outval = val_new_value();
  val_init_from_template(outval, outobj);

  res = build_to_xml_log_Config(outval, out);
  if (res != NO_ERR) {
    free(in);
    free(out);
    free(errstr);
    return SET_ERROR(res);
  }

  dlq_block_enque(&outval->v.childQ, &msg->rpc_dataQ);

  /* debug: print `val_value_t` in `msg->rpc_dataQ` */
  // for (val_value_t *val = (val_value_t *)dlq_firstEntry(&msg->rpc_dataQ);
  //      val != NULL;
  //      val = (val_value_t *)dlq_nextEntry(val)) {
  //   val_dump_value(val, 2);
  // }

  free(in);
  free(out);
  free(errstr);
  return res;
}
static status_t intri_log_Log_GetBasicConfig_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct emptypb_Empty *in = malloc(sizeof(*in));
  struct logpb_BasicConfig *out = malloc(sizeof(*out));
  GoString *errstr = malloc(sizeof(*errstr));

  errstr->n = 0;
  log_Log_GetBasicConfig(in, out, errstr);
  if (errstr->n >0) {
    const xmlChar *errorstr = NULL;
    val_value_t *errorval = NULL;
    ncx_errinfo_t *errinfo = ncx_new_errinfo();
    errinfo->error_message = (xmlChar*)(errstr->p);
    res = ERR_NCX_INVALID_VALUE;
    agt_record_error_errinfo(
        scb,
        &msg->mhdr,
        NCX_LAYER_RPC,
        res,
        methnode,
        NCX_NT_NONE,
        errorstr,
        NCX_NT_NONE,
        errorval,
        errinfo);
    log_debug("err= %s", errstr->p);
    free(in);
    free(out);
    free(errstr);
    return res;
  }

  obj_template_t *outobj = obj_find_child(
      msg->rpc_method,
      y_M_intri_log,
      "output");
  val_value_t *outval = val_new_value();
  val_init_from_template(outval, outobj);

  res = build_to_xml_log_BasicConfig(outval, out);
  if (res != NO_ERR) {
    free(in);
    free(out);
    free(errstr);
    return SET_ERROR(res);
  }

  dlq_block_enque(&outval->v.childQ, &msg->rpc_dataQ);

  /* debug: print `val_value_t` in `msg->rpc_dataQ` */
  // for (val_value_t *val = (val_value_t *)dlq_firstEntry(&msg->rpc_dataQ);
  //      val != NULL;
  //      val = (val_value_t *)dlq_nextEntry(val)) {
  //   val_dump_value(val, 2);
  // }

  free(in);
  free(out);
  free(errstr);
  return res;
}
static status_t intri_log_Log_UpdateBasicConfig_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct logpb_BasicConfig *in = malloc(sizeof(*in));
  struct emptypb_Empty *out = malloc(sizeof(*out));
  GoString *errstr = malloc(sizeof(*errstr));

  errstr->n = 0;
  log_Log_GetBasicConfig(out, in, errstr);
  if (errstr->n > 0) {
    const xmlChar *errorstr = NULL;
    val_value_t *errorval = NULL;
    ncx_errinfo_t *errinfo = ncx_new_errinfo();
    errinfo->error_message = (xmlChar*)(errstr->p);
    res = ERR_NCX_INVALID_VALUE;
    agt_record_error_errinfo(
        scb,
        &msg->mhdr,
        NCX_LAYER_RPC,
        res,
        methnode,
        NCX_NT_NONE,
        errorstr,
        NCX_NT_NONE,
        errorval,
        errinfo);
    log_debug("err= %s", errstr->p);
    free(in);
    free(out);
    free(errstr);
    return res;
  }
  res = build_to_priv_log_BasicConfig(msg->rpc_input, in);
  if (res != NO_ERR) {
    free(in);
    free(out);
    free(errstr);
    return SET_ERROR(res);
  }
  errstr->n = 0;
  log_Log_UpdateBasicConfig(in, out, errstr);
  if (errstr->n >0) {
    const xmlChar *errorstr = NULL;
    val_value_t *errorval = NULL;
    ncx_errinfo_t *errinfo = ncx_new_errinfo();
    errinfo->error_message = (xmlChar*)(errstr->p);
    res = ERR_NCX_INVALID_VALUE;
    agt_record_error_errinfo(
        scb,
        &msg->mhdr,
        NCX_LAYER_RPC,
        res,
        methnode,
        NCX_NT_NONE,
        errorstr,
        NCX_NT_NONE,
        errorval,
        errinfo);
    log_debug("err= %s", errstr->p);
    free(in);
    free(out);
    free(errstr);
    return res;
  }

  free(in);
  free(out);
  free(errstr);
  return res;
}
static status_t intri_log_Log_GetTargetConfig_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct emptypb_Empty *in = malloc(sizeof(*in));
  struct logpb_TargetConfig *out = malloc(sizeof(*out));
  GoString *errstr = malloc(sizeof(*errstr));

  errstr->n = 0;
  log_Log_GetTargetConfig(in, out, errstr);
  if (errstr->n >0) {
    const xmlChar *errorstr = NULL;
    val_value_t *errorval = NULL;
    ncx_errinfo_t *errinfo = ncx_new_errinfo();
    errinfo->error_message = (xmlChar*)(errstr->p);
    res = ERR_NCX_INVALID_VALUE;
    agt_record_error_errinfo(
        scb,
        &msg->mhdr,
        NCX_LAYER_RPC,
        res,
        methnode,
        NCX_NT_NONE,
        errorstr,
        NCX_NT_NONE,
        errorval,
        errinfo);
    log_debug("err= %s", errstr->p);
    free(in);
    free(out);
    free(errstr);
    return res;
  }

  obj_template_t *outobj = obj_find_child(
      msg->rpc_method,
      y_M_intri_log,
      "output");
  val_value_t *outval = val_new_value();
  val_init_from_template(outval, outobj);

  res = build_to_xml_log_TargetConfig(outval, out);
  if (res != NO_ERR) {
    free(in);
    free(out);
    free(errstr);
    return SET_ERROR(res);
  }

  dlq_block_enque(&outval->v.childQ, &msg->rpc_dataQ);

  /* debug: print `val_value_t` in `msg->rpc_dataQ` */
  // for (val_value_t *val = (val_value_t *)dlq_firstEntry(&msg->rpc_dataQ);
  //      val != NULL;
  //      val = (val_value_t *)dlq_nextEntry(val)) {
  //   val_dump_value(val, 2);
  // }

  free(in);
  free(out);
  free(errstr);
  return res;
}
static status_t intri_log_Log_AddTargetConfigEntry_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct logpb_TargetConfigEntry *in = malloc(sizeof(*in));
  struct emptypb_Empty *out = malloc(sizeof(*out));
  GoString *errstr = malloc(sizeof(*errstr));

  /* ian: this func has no prefix Update/Set */
  res = build_to_priv_log_TargetConfigEntry(msg->rpc_input, in);
  if (res != NO_ERR) {
    free(in);
    free(out);
    free(errstr);
    return SET_ERROR(res);
  }
  errstr->n = 0;
  log_Log_AddTargetConfigEntry(in, out, errstr);
  if (errstr->n >0) {
    const xmlChar *errorstr = NULL;
    val_value_t *errorval = NULL;
    ncx_errinfo_t *errinfo = ncx_new_errinfo();
    errinfo->error_message = (xmlChar*)(errstr->p);
    res = ERR_NCX_INVALID_VALUE;
    agt_record_error_errinfo(
        scb,
        &msg->mhdr,
        NCX_LAYER_RPC,
        res,
        methnode,
        NCX_NT_NONE,
        errorstr,
        NCX_NT_NONE,
        errorval,
        errinfo);
    log_debug("err= %s", errstr->p);
    free(in);
    free(out);
    free(errstr);
    return res;
  }

  free(in);
  free(out);
  free(errstr);
  return res;
}
static status_t intri_log_Log_UpdateTargetConfigEntry_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct logpb_TargetConfigEntry *in = malloc(sizeof(*in));
  struct emptypb_Empty *out = malloc(sizeof(*out));
  GoString *errstr = malloc(sizeof(*errstr));

  /* ian: has no Get func */
  res = build_to_priv_log_TargetConfigEntry(msg->rpc_input, in);
  if (res != NO_ERR) {
    free(in);
    free(out);
    free(errstr);
    return SET_ERROR(res);
  }
  errstr->n = 0;
  log_Log_UpdateTargetConfigEntry(in, out, errstr);
  if (errstr->n >0) {
    const xmlChar *errorstr = NULL;
    val_value_t *errorval = NULL;
    ncx_errinfo_t *errinfo = ncx_new_errinfo();
    errinfo->error_message = (xmlChar*)(errstr->p);
    res = ERR_NCX_INVALID_VALUE;
    agt_record_error_errinfo(
        scb,
        &msg->mhdr,
        NCX_LAYER_RPC,
        res,
        methnode,
        NCX_NT_NONE,
        errorstr,
        NCX_NT_NONE,
        errorval,
        errinfo);
    log_debug("err= %s", errstr->p);
    free(in);
    free(out);
    free(errstr);
    return res;
  }

  free(in);
  free(out);
  free(errstr);
  return res;
}
static status_t intri_log_Log_DeleteTargetConfigEntry_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct logpb_TargetConfigEntry *in = malloc(sizeof(*in));
  struct emptypb_Empty *out = malloc(sizeof(*out));
  GoString *errstr = malloc(sizeof(*errstr));

  /* ian: this func has no prefix Update/Set */
  res = build_to_priv_log_TargetConfigEntry(msg->rpc_input, in);
  if (res != NO_ERR) {
    free(in);
    free(out);
    free(errstr);
    return SET_ERROR(res);
  }
  errstr->n = 0;
  log_Log_DeleteTargetConfigEntry(in, out, errstr);
  if (errstr->n >0) {
    const xmlChar *errorstr = NULL;
    val_value_t *errorval = NULL;
    ncx_errinfo_t *errinfo = ncx_new_errinfo();
    errinfo->error_message = (xmlChar*)(errstr->p);
    res = ERR_NCX_INVALID_VALUE;
    agt_record_error_errinfo(
        scb,
        &msg->mhdr,
        NCX_LAYER_RPC,
        res,
        methnode,
        NCX_NT_NONE,
        errorstr,
        NCX_NT_NONE,
        errorval,
        errinfo);
    log_debug("err= %s", errstr->p);
    free(in);
    free(out);
    free(errstr);
    return res;
  }

  free(in);
  free(out);
  free(errstr);
  return res;
}
static status_t intri_log_Log_GetActionConfig_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct emptypb_Empty *in = malloc(sizeof(*in));
  struct logpb_ActionConfig *out = malloc(sizeof(*out));
  GoString *errstr = malloc(sizeof(*errstr));

  errstr->n = 0;
  log_Log_GetActionConfig(in, out, errstr);
  if (errstr->n >0) {
    const xmlChar *errorstr = NULL;
    val_value_t *errorval = NULL;
    ncx_errinfo_t *errinfo = ncx_new_errinfo();
    errinfo->error_message = (xmlChar*)(errstr->p);
    res = ERR_NCX_INVALID_VALUE;
    agt_record_error_errinfo(
        scb,
        &msg->mhdr,
        NCX_LAYER_RPC,
        res,
        methnode,
        NCX_NT_NONE,
        errorstr,
        NCX_NT_NONE,
        errorval,
        errinfo);
    log_debug("err= %s", errstr->p);
    free(in);
    free(out);
    free(errstr);
    return res;
  }

  obj_template_t *outobj = obj_find_child(
      msg->rpc_method,
      y_M_intri_log,
      "output");
  val_value_t *outval = val_new_value();
  val_init_from_template(outval, outobj);

  res = build_to_xml_log_ActionConfig(outval, out);
  if (res != NO_ERR) {
    free(in);
    free(out);
    free(errstr);
    return SET_ERROR(res);
  }

  dlq_block_enque(&outval->v.childQ, &msg->rpc_dataQ);

  /* debug: print `val_value_t` in `msg->rpc_dataQ` */
  // for (val_value_t *val = (val_value_t *)dlq_firstEntry(&msg->rpc_dataQ);
  //      val != NULL;
  //      val = (val_value_t *)dlq_nextEntry(val)) {
  //   val_dump_value(val, 2);
  // }

  free(in);
  free(out);
  free(errstr);
  return res;
}
static status_t intri_log_Log_UpdateActionConfig_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct logpb_ActionConfig *in = malloc(sizeof(*in));
  struct emptypb_Empty *out = malloc(sizeof(*out));
  GoString *errstr = malloc(sizeof(*errstr));

  errstr->n = 0;
  log_Log_GetActionConfig(out, in, errstr);
  if (errstr->n > 0) {
    const xmlChar *errorstr = NULL;
    val_value_t *errorval = NULL;
    ncx_errinfo_t *errinfo = ncx_new_errinfo();
    errinfo->error_message = (xmlChar*)(errstr->p);
    res = ERR_NCX_INVALID_VALUE;
    agt_record_error_errinfo(
        scb,
        &msg->mhdr,
        NCX_LAYER_RPC,
        res,
        methnode,
        NCX_NT_NONE,
        errorstr,
        NCX_NT_NONE,
        errorval,
        errinfo);
    log_debug("err= %s", errstr->p);
    free(in);
    free(out);
    free(errstr);
    return res;
  }
  res = build_to_priv_log_ActionConfig(msg->rpc_input, in);
  if (res != NO_ERR) {
    free(in);
    free(out);
    free(errstr);
    return SET_ERROR(res);
  }
  errstr->n = 0;
  log_Log_UpdateActionConfig(in, out, errstr);
  if (errstr->n >0) {
    const xmlChar *errorstr = NULL;
    val_value_t *errorval = NULL;
    ncx_errinfo_t *errinfo = ncx_new_errinfo();
    errinfo->error_message = (xmlChar*)(errstr->p);
    res = ERR_NCX_INVALID_VALUE;
    agt_record_error_errinfo(
        scb,
        &msg->mhdr,
        NCX_LAYER_RPC,
        res,
        methnode,
        NCX_NT_NONE,
        errorstr,
        NCX_NT_NONE,
        errorval,
        errinfo);
    log_debug("err= %s", errstr->p);
    free(in);
    free(out);
    free(errstr);
    return res;
  }

  free(in);
  free(out);
  free(errstr);
  return res;
}
static status_t intri_log_Log_RunSendTestEvent_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct emptypb_Empty *in = malloc(sizeof(*in));
  struct emptypb_Empty *out = malloc(sizeof(*out));
  GoString *errstr = malloc(sizeof(*errstr));

  errstr->n = 0;
  log_Log_RunSendTestEvent(in, out, errstr);
  if (errstr->n >0) {
    const xmlChar *errorstr = NULL;
    val_value_t *errorval = NULL;
    ncx_errinfo_t *errinfo = ncx_new_errinfo();
    errinfo->error_message = (xmlChar*)(errstr->p);
    res = ERR_NCX_INVALID_VALUE;
    agt_record_error_errinfo(
        scb,
        &msg->mhdr,
        NCX_LAYER_RPC,
        res,
        methnode,
        NCX_NT_NONE,
        errorstr,
        NCX_NT_NONE,
        errorval,
        errinfo);
    log_debug("err= %s", errstr->p);
    free(in);
    free(out);
    free(errstr);
    return res;
  }

  free(in);
  free(out);
  free(errstr);
  return res;
}
static status_t intri_log_Log_GetStatistics_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct emptypb_Empty *in = malloc(sizeof(*in));
  struct logpb_Statistics *out = malloc(sizeof(*out));
  GoString *errstr = malloc(sizeof(*errstr));

  errstr->n = 0;
  log_Log_GetStatistics(in, out, errstr);
  if (errstr->n >0) {
    const xmlChar *errorstr = NULL;
    val_value_t *errorval = NULL;
    ncx_errinfo_t *errinfo = ncx_new_errinfo();
    errinfo->error_message = (xmlChar*)(errstr->p);
    res = ERR_NCX_INVALID_VALUE;
    agt_record_error_errinfo(
        scb,
        &msg->mhdr,
        NCX_LAYER_RPC,
        res,
        methnode,
        NCX_NT_NONE,
        errorstr,
        NCX_NT_NONE,
        errorval,
        errinfo);
    log_debug("err= %s", errstr->p);
    free(in);
    free(out);
    free(errstr);
    return res;
  }

  obj_template_t *outobj = obj_find_child(
      msg->rpc_method,
      y_M_intri_log,
      "output");
  val_value_t *outval = val_new_value();
  val_init_from_template(outval, outobj);

  res = build_to_xml_log_Statistics(outval, out);
  if (res != NO_ERR) {
    free(in);
    free(out);
    free(errstr);
    return SET_ERROR(res);
  }

  dlq_block_enque(&outval->v.childQ, &msg->rpc_dataQ);

  /* debug: print `val_value_t` in `msg->rpc_dataQ` */
  // for (val_value_t *val = (val_value_t *)dlq_firstEntry(&msg->rpc_dataQ);
  //      val != NULL;
  //      val = (val_value_t *)dlq_nextEntry(val)) {
  //   val_dump_value(val, 2);
  // }

  free(in);
  free(out);
  free(errstr);
  return res;
}
static status_t intri_log_Log_RunCleanStatistics_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct emptypb_Empty *in = malloc(sizeof(*in));
  struct emptypb_Empty *out = malloc(sizeof(*out));
  GoString *errstr = malloc(sizeof(*errstr));

  errstr->n = 0;
  log_Log_RunCleanStatistics(in, out, errstr);
  if (errstr->n >0) {
    const xmlChar *errorstr = NULL;
    val_value_t *errorval = NULL;
    ncx_errinfo_t *errinfo = ncx_new_errinfo();
    errinfo->error_message = (xmlChar*)(errstr->p);
    res = ERR_NCX_INVALID_VALUE;
    agt_record_error_errinfo(
        scb,
        &msg->mhdr,
        NCX_LAYER_RPC,
        res,
        methnode,
        NCX_NT_NONE,
        errorstr,
        NCX_NT_NONE,
        errorval,
        errinfo);
    log_debug("err= %s", errstr->p);
    free(in);
    free(out);
    free(errstr);
    return res;
  }

  free(in);
  free(out);
  free(errstr);
  return res;
}
static status_t intri_log_Log_GetRecordTargetLogList_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct emptypb_Empty *in = malloc(sizeof(*in));
  struct logpb_LogFiles *out = malloc(sizeof(*out));
  GoString *errstr = malloc(sizeof(*errstr));

  errstr->n = 0;
  log_Log_GetRecordTargetLogList(in, out, errstr);
  if (errstr->n >0) {
    const xmlChar *errorstr = NULL;
    val_value_t *errorval = NULL;
    ncx_errinfo_t *errinfo = ncx_new_errinfo();
    errinfo->error_message = (xmlChar*)(errstr->p);
    res = ERR_NCX_INVALID_VALUE;
    agt_record_error_errinfo(
        scb,
        &msg->mhdr,
        NCX_LAYER_RPC,
        res,
        methnode,
        NCX_NT_NONE,
        errorstr,
        NCX_NT_NONE,
        errorval,
        errinfo);
    log_debug("err= %s", errstr->p);
    free(in);
    free(out);
    free(errstr);
    return res;
  }

  obj_template_t *outobj = obj_find_child(
      msg->rpc_method,
      y_M_intri_log,
      "output");
  val_value_t *outval = val_new_value();
  val_init_from_template(outval, outobj);

  res = build_to_xml_log_LogFiles(outval, out);
  if (res != NO_ERR) {
    free(in);
    free(out);
    free(errstr);
    return SET_ERROR(res);
  }

  dlq_block_enque(&outval->v.childQ, &msg->rpc_dataQ);

  /* debug: print `val_value_t` in `msg->rpc_dataQ` */
  // for (val_value_t *val = (val_value_t *)dlq_firstEntry(&msg->rpc_dataQ);
  //      val != NULL;
  //      val = (val_value_t *)dlq_nextEntry(val)) {
  //   val_dump_value(val, 2);
  // }

  free(in);
  free(out);
  free(errstr);
  return res;
}
static status_t intri_log_Log_RunCleanRecordTargetLogList_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct emptypb_Empty *in = malloc(sizeof(*in));
  struct emptypb_Empty *out = malloc(sizeof(*out));
  GoString *errstr = malloc(sizeof(*errstr));

  errstr->n = 0;
  log_Log_RunCleanRecordTargetLogList(in, out, errstr);
  if (errstr->n >0) {
    const xmlChar *errorstr = NULL;
    val_value_t *errorval = NULL;
    ncx_errinfo_t *errinfo = ncx_new_errinfo();
    errinfo->error_message = (xmlChar*)(errstr->p);
    res = ERR_NCX_INVALID_VALUE;
    agt_record_error_errinfo(
        scb,
        &msg->mhdr,
        NCX_LAYER_RPC,
        res,
        methnode,
        NCX_NT_NONE,
        errorstr,
        NCX_NT_NONE,
        errorval,
        errinfo);
    log_debug("err= %s", errstr->p);
    free(in);
    free(out);
    free(errstr);
    return res;
  }

  free(in);
  free(out);
  free(errstr);
  return res;
}
static status_t intri_log_Log_RunSaveLogToYAML_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct commonpb_Path *in = malloc(sizeof(*in));
  struct emptypb_Empty *out = malloc(sizeof(*out));
  GoString *errstr = malloc(sizeof(*errstr));

  /* ian: this func has no prefix Update/Set */
  res = build_to_priv_common_Path(msg->rpc_input, in);
  if (res != NO_ERR) {
    free(in);
    free(out);
    free(errstr);
    return SET_ERROR(res);
  }
  errstr->n = 0;
  log_Log_RunSaveLogToYAML(in, out, errstr);
  if (errstr->n >0) {
    const xmlChar *errorstr = NULL;
    val_value_t *errorval = NULL;
    ncx_errinfo_t *errinfo = ncx_new_errinfo();
    errinfo->error_message = (xmlChar*)(errstr->p);
    res = ERR_NCX_INVALID_VALUE;
    agt_record_error_errinfo(
        scb,
        &msg->mhdr,
        NCX_LAYER_RPC,
        res,
        methnode,
        NCX_NT_NONE,
        errorstr,
        NCX_NT_NONE,
        errorval,
        errinfo);
    log_debug("err= %s", errstr->p);
    free(in);
    free(out);
    free(errstr);
    return res;
  }

  free(in);
  free(out);
  free(errstr);
  return res;
}

status_t y_sercom_log_init(
    const xmlChar *modname,
    const xmlChar *revision) {
  status_t res = NO_ERR;
  agt_profile_t *agt_profile = agt_get_profile();

  if (xml_strcmp(modname, y_M_intri_log)) {
    return ERR_NCX_UNKNOWN_MODULE;
  }
  if (revision && xml_strcmp(revision, y_R_intri_log)) {
    return ERR_NCX_WRONG_VERSION;
  }

  res = agt_load_sil_code(
    y_M_intri_event,
    y_R_intri_event,
    true);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  res = agt_load_sil_code(
    y_M_intri_timestamp,
    y_R_intri_timestamp,
    true);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  res = agt_load_sil_code(
    y_M_intri_empty,
    y_R_intri_empty,
    true);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  res = agt_load_sil_code(
    y_M_intri_common,
    y_R_intri_common,
    true);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  res = ncxmod_load_module(
      y_M_intri_log,
      y_R_intri_log,
      &agt_profile->agt_savedevQ,
      &intri_log_mod);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  res = agt_rpc_register_method(
      y_M_intri_log,
      "sercom-log-Log-GetConfig",
      AGT_RPC_PH_INVOKE,
      intri_log_Log_GetConfig_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  res = agt_rpc_register_method(
      y_M_intri_log,
      "sercom-log-Log-GetBasicConfig",
      AGT_RPC_PH_INVOKE,
      intri_log_Log_GetBasicConfig_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  res = agt_rpc_register_method(
      y_M_intri_log,
      "sercom-log-Log-UpdateBasicConfig",
      AGT_RPC_PH_INVOKE,
      intri_log_Log_UpdateBasicConfig_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  res = agt_rpc_register_method(
      y_M_intri_log,
      "sercom-log-Log-GetTargetConfig",
      AGT_RPC_PH_INVOKE,
      intri_log_Log_GetTargetConfig_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  res = agt_rpc_register_method(
      y_M_intri_log,
      "sercom-log-Log-AddTargetConfigEntry",
      AGT_RPC_PH_INVOKE,
      intri_log_Log_AddTargetConfigEntry_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  res = agt_rpc_register_method(
      y_M_intri_log,
      "sercom-log-Log-UpdateTargetConfigEntry",
      AGT_RPC_PH_INVOKE,
      intri_log_Log_UpdateTargetConfigEntry_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  res = agt_rpc_register_method(
      y_M_intri_log,
      "sercom-log-Log-DeleteTargetConfigEntry",
      AGT_RPC_PH_INVOKE,
      intri_log_Log_DeleteTargetConfigEntry_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  res = agt_rpc_register_method(
      y_M_intri_log,
      "sercom-log-Log-GetActionConfig",
      AGT_RPC_PH_INVOKE,
      intri_log_Log_GetActionConfig_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  res = agt_rpc_register_method(
      y_M_intri_log,
      "sercom-log-Log-UpdateActionConfig",
      AGT_RPC_PH_INVOKE,
      intri_log_Log_UpdateActionConfig_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  res = agt_rpc_register_method(
      y_M_intri_log,
      "sercom-log-Log-RunSendTestEvent",
      AGT_RPC_PH_INVOKE,
      intri_log_Log_RunSendTestEvent_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  res = agt_rpc_register_method(
      y_M_intri_log,
      "sercom-log-Log-GetStatistics",
      AGT_RPC_PH_INVOKE,
      intri_log_Log_GetStatistics_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  res = agt_rpc_register_method(
      y_M_intri_log,
      "sercom-log-Log-RunCleanStatistics",
      AGT_RPC_PH_INVOKE,
      intri_log_Log_RunCleanStatistics_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  res = agt_rpc_register_method(
      y_M_intri_log,
      "sercom-log-Log-GetRecordTargetLogList",
      AGT_RPC_PH_INVOKE,
      intri_log_Log_GetRecordTargetLogList_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  res = agt_rpc_register_method(
      y_M_intri_log,
      "sercom-log-Log-RunCleanRecordTargetLogList",
      AGT_RPC_PH_INVOKE,
      intri_log_Log_RunCleanRecordTargetLogList_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  res = agt_rpc_register_method(
      y_M_intri_log,
      "sercom-log-Log-RunSaveLogToYAML",
      AGT_RPC_PH_INVOKE,
      intri_log_Log_RunSaveLogToYAML_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  return res;
}

status_t y_sercom_log_init2(void) {
  status_t res = NO_ERR;
  return res;
}

void y_sercom_log_cleanup(void) {
  agt_rpc_unregister_method(
      y_M_intri_log,
      "sercom-log-Log-GetConfig");
  agt_rpc_unregister_method(
      y_M_intri_log,
      "sercom-log-Log-GetBasicConfig");
  agt_rpc_unregister_method(
      y_M_intri_log,
      "sercom-log-Log-UpdateBasicConfig");
  agt_rpc_unregister_method(
      y_M_intri_log,
      "sercom-log-Log-GetTargetConfig");
  agt_rpc_unregister_method(
      y_M_intri_log,
      "sercom-log-Log-AddTargetConfigEntry");
  agt_rpc_unregister_method(
      y_M_intri_log,
      "sercom-log-Log-UpdateTargetConfigEntry");
  agt_rpc_unregister_method(
      y_M_intri_log,
      "sercom-log-Log-DeleteTargetConfigEntry");
  agt_rpc_unregister_method(
      y_M_intri_log,
      "sercom-log-Log-GetActionConfig");
  agt_rpc_unregister_method(
      y_M_intri_log,
      "sercom-log-Log-UpdateActionConfig");
  agt_rpc_unregister_method(
      y_M_intri_log,
      "sercom-log-Log-RunSendTestEvent");
  agt_rpc_unregister_method(
      y_M_intri_log,
      "sercom-log-Log-GetStatistics");
  agt_rpc_unregister_method(
      y_M_intri_log,
      "sercom-log-Log-RunCleanStatistics");
  agt_rpc_unregister_method(
      y_M_intri_log,
      "sercom-log-Log-GetRecordTargetLogList");
  agt_rpc_unregister_method(
      y_M_intri_log,
      "sercom-log-Log-RunCleanRecordTargetLogList");
  agt_rpc_unregister_method(
      y_M_intri_log,
      "sercom-log-Log-RunSaveLogToYAML");
}
