
/*****************************************************************************************************
 * Copyright (C) 2017-2022 by Intrising
 *  - ian0113@intrising.com.tw
 * 
 * Generated by protoc-gen-yang@gen-yang
 * 
 *****************************************************************************************************/

#include <libxml/xmlstring.h>
#include "agt.h"
#include "agt_cb.h"
#include "agt_rpc.h"
#include "agt_timer.h"
#include "agt_util.h"
#include "dlq.h"
#include "ncx.h"
#include "ncx_feature.h"
#include "ncxmod.h"
#include "ncxtypes.h"
#include "procdefs.h"
#include "rpc.h"
#include "ses.h"
#include "status.h"
#include "val.h"
#include "val_util.h"
#include "xml_util.h"

#include "intri-timecontrol@2022-06-24.h"
#include "../../../../../../../.libintrishare/libintrishare.h"
#include "../../../../../genc-trans/github.com/Intrising/intri-type/device/intri-device-trans.h"
#include "../../../../../genc-trans/github.com/Intrising/intri-type/timecontrol/intri-timecontrol-trans.h"
#include "../../../../../genc-trans/github.com/golang/protobuf/ptypes/empty/intri-empty-trans.h"
#include "../../../../../genc-trans/github.com/golang/protobuf/ptypes/timestamp/intri-timestamp-trans.h"

static ncx_module_t *intri_timecontrol_mod;
static obj_template_t *intri_timecontrol_GetInputMonitorStatus_obj;
static obj_template_t *intri_timecontrol_GetDPLLStatus_obj;
static obj_template_t *intri_timecontrol_SetDPLLRefPriority_obj;
static obj_template_t *intri_timecontrol_GetDPLLRefPriority_obj;
static obj_template_t *intri_timecontrol_SetInputClockFreq_obj;
static obj_template_t *intri_timecontrol_GetInputClockFreq_obj;
static obj_template_t *intri_timecontrol_SetToDSource_obj;
static obj_template_t *intri_timecontrol_GetToDSource_obj;
static obj_template_t *intri_timecontrol_SetToD_obj;
static obj_template_t *intri_timecontrol_GetToD_obj;
static obj_template_t *intri_timecontrol_SetFrequencyControl_obj;
static obj_template_t *intri_timecontrol_GetFrequencyControl_obj;
static obj_template_t *intri_timecontrol_SetPhaseControl_obj;
static obj_template_t *intri_timecontrol_GetPhaseControl_obj;
static obj_template_t *intri_timecontrol_SetPhaseSlopeLimit_obj;
static obj_template_t *intri_timecontrol_GetPhaseSlopeLimit_obj;
static obj_template_t *intri_timecontrol_SetPhaseControlTimer_obj;
static obj_template_t *intri_timecontrol_GetPhaseControlTimer_obj;

static status_t intri_timecontrol_TimeControl_GetInputMonitorStatus_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct timecontrolpb_InputClockManage in;
  struct timecontrolpb_MonitorStatus out;
  timecontrol_TimeControl_GetInputMonitorStatus(&in, &out);
  val_value_t *resval = val_new_value();
  res =  build_to_xml_timecontrol_MonitorStatus(
      resval,
    &out);
  return res;
}

static status_t intri_timecontrol_TimeControl_GetDPLLStatus_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct timecontrolpb_DPLLManage in;
  struct timecontrolpb_DPLLStatus out;
  timecontrol_TimeControl_GetDPLLStatus(&in, &out);
  val_value_t *resval = val_new_value();
  res =  build_to_xml_timecontrol_DPLLStatus(
      resval,
    &out);
  return res;
}

static status_t intri_timecontrol_TimeControl_SetDPLLRefPriority_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct timecontrolpb_DPLLRefPriority in;
  struct emptypb_Empty out;
  timecontrol_TimeControl_SetDPLLRefPriority(&in, &out);
  val_value_t *resval = val_new_value();
  return res;
}

static status_t intri_timecontrol_TimeControl_GetDPLLRefPriority_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct timecontrolpb_DPLLRefPriorityManage in;
  struct timecontrolpb_DPLLRefPriority out;
  timecontrol_TimeControl_GetDPLLRefPriority(&in, &out);
  val_value_t *resval = val_new_value();
  res =  build_to_xml_timecontrol_DPLLRefPriority(
      resval,
    &out);
  return res;
}

static status_t intri_timecontrol_TimeControl_SetInputClockFreq_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct timecontrolpb_SyncEInputClockSpeed in;
  struct emptypb_Empty out;
  timecontrol_TimeControl_SetInputClockFreq(&in, &out);
  val_value_t *resval = val_new_value();
  return res;
}

static status_t intri_timecontrol_TimeControl_GetInputClockFreq_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct timecontrolpb_InputClockManage in;
  struct timecontrolpb_SyncEInputClockSpeed out;
  timecontrol_TimeControl_GetInputClockFreq(&in, &out);
  val_value_t *resval = val_new_value();
  res =  build_to_xml_timecontrol_SyncEInputClockSpeed(
      resval,
    &out);
  return res;
}

static status_t intri_timecontrol_TimeControl_SetToDSource_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct timecontrolpb_ToDSource in;
  struct emptypb_Empty out;
  timecontrol_TimeControl_SetToDSource(&in, &out);
  val_value_t *resval = val_new_value();
  return res;
}

static status_t intri_timecontrol_TimeControl_GetToDSource_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct emptypb_Empty in;
  struct timecontrolpb_ToDSource out;
  timecontrol_TimeControl_GetToDSource(&in, &out);
  val_value_t *resval = val_new_value();
  res =  build_to_xml_timecontrol_ToDSource(
      resval,
    &out);
  return res;
}

static status_t intri_timecontrol_TimeControl_SetToD_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct timecontrolpb_ToDTime in;
  struct emptypb_Empty out;
  timecontrol_TimeControl_SetToD(&in, &out);
  val_value_t *resval = val_new_value();
  return res;
}

static status_t intri_timecontrol_TimeControl_GetToD_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct timecontrolpb_DPLLToDManage in;
  struct timecontrolpb_ToDTime out;
  timecontrol_TimeControl_GetToD(&in, &out);
  val_value_t *resval = val_new_value();
  res =  build_to_xml_timecontrol_ToDTime(
      resval,
    &out);
  return res;
}

static status_t intri_timecontrol_TimeControl_SetFrequencyControl_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct timecontrolpb_DPLLFrequencyControl in;
  struct emptypb_Empty out;
  timecontrol_TimeControl_SetFrequencyControl(&in, &out);
  val_value_t *resval = val_new_value();
  return res;
}

static status_t intri_timecontrol_TimeControl_GetFrequencyControl_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct timecontrolpb_DPLLManage in;
  struct timecontrolpb_DPLLFrequencyControl out;
  timecontrol_TimeControl_GetFrequencyControl(&in, &out);
  val_value_t *resval = val_new_value();
  res =  build_to_xml_timecontrol_DPLLFrequencyControl(
      resval,
    &out);
  return res;
}

static status_t intri_timecontrol_TimeControl_SetPhaseControl_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct timecontrolpb_DPLLPhaseControl in;
  struct emptypb_Empty out;
  timecontrol_TimeControl_SetPhaseControl(&in, &out);
  val_value_t *resval = val_new_value();
  return res;
}

static status_t intri_timecontrol_TimeControl_GetPhaseControl_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct timecontrolpb_DPLLManage in;
  struct timecontrolpb_DPLLPhaseControl out;
  timecontrol_TimeControl_GetPhaseControl(&in, &out);
  val_value_t *resval = val_new_value();
  res =  build_to_xml_timecontrol_DPLLPhaseControl(
      resval,
    &out);
  return res;
}

static status_t intri_timecontrol_TimeControl_SetPhaseSlopeLimit_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct timecontrolpb_DPLLPhaseSlopeLimit in;
  struct emptypb_Empty out;
  timecontrol_TimeControl_SetPhaseSlopeLimit(&in, &out);
  val_value_t *resval = val_new_value();
  return res;
}

static status_t intri_timecontrol_TimeControl_GetPhaseSlopeLimit_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct timecontrolpb_DPLLManage in;
  struct timecontrolpb_DPLLPhaseSlopeLimit out;
  timecontrol_TimeControl_GetPhaseSlopeLimit(&in, &out);
  val_value_t *resval = val_new_value();
  res =  build_to_xml_timecontrol_DPLLPhaseSlopeLimit(
      resval,
    &out);
  return res;
}

static status_t intri_timecontrol_TimeControl_SetPhaseControlTimer_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct timecontrolpb_DPLLPhaseControlTimer in;
  struct emptypb_Empty out;
  timecontrol_TimeControl_SetPhaseControlTimer(&in, &out);
  val_value_t *resval = val_new_value();
  return res;
}

static status_t intri_timecontrol_TimeControl_GetPhaseControlTimer_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct timecontrolpb_DPLLManage in;
  struct timecontrolpb_DPLLPhaseControlTimer out;
  timecontrol_TimeControl_GetPhaseControlTimer(&in, &out);
  val_value_t *resval = val_new_value();
  res =  build_to_xml_timecontrol_DPLLPhaseControlTimer(
      resval,
    &out);
  return res;
}

status_t y_intri_timecontrol_init(
    const xmlChar *modname,
    const xmlChar *revision) {
  status_t res = NO_ERR;
  agt_profile_t *agt_profile = agt_get_profile();

  if (xml_strcmp(modname, y_M_intri_timecontrol)) {
    return ERR_NCX_UNKNOWN_MODULE;
  }

  if (revision && xml_strcmp(revision, y_R_intri_timecontrol)) {
    return ERR_NCX_WRONG_VERSION;
  }

  res = ncxmod_load_module(
      y_M_intri_timecontrol,
      y_R_intri_timecontrol,
      &agt_profile->agt_savedevQ,
      &intri_timecontrol_mod);
  if (res != NO_ERR) {
    return res;
  }

  intri_timecontrol_GetInputMonitorStatus_obj = ncx_find_object(
      intri_timecontrol_mod,
      "intri-timecontrol-GetInputMonitorStatus");
  if (intri_timecontrol_GetInputMonitorStatus_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_timecontrol,
      "intri-timecontrol-GetInputMonitorStatus",
      AGT_RPC_PH_INVOKE,
      intri_timecontrol_TimeControl_GetInputMonitorStatus_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_timecontrol_GetDPLLStatus_obj = ncx_find_object(
      intri_timecontrol_mod,
      "intri-timecontrol-GetDPLLStatus");
  if (intri_timecontrol_GetDPLLStatus_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_timecontrol,
      "intri-timecontrol-GetDPLLStatus",
      AGT_RPC_PH_INVOKE,
      intri_timecontrol_TimeControl_GetDPLLStatus_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_timecontrol_SetDPLLRefPriority_obj = ncx_find_object(
      intri_timecontrol_mod,
      "intri-timecontrol-SetDPLLRefPriority");
  if (intri_timecontrol_SetDPLLRefPriority_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_timecontrol,
      "intri-timecontrol-SetDPLLRefPriority",
      AGT_RPC_PH_INVOKE,
      intri_timecontrol_TimeControl_SetDPLLRefPriority_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_timecontrol_GetDPLLRefPriority_obj = ncx_find_object(
      intri_timecontrol_mod,
      "intri-timecontrol-GetDPLLRefPriority");
  if (intri_timecontrol_GetDPLLRefPriority_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_timecontrol,
      "intri-timecontrol-GetDPLLRefPriority",
      AGT_RPC_PH_INVOKE,
      intri_timecontrol_TimeControl_GetDPLLRefPriority_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_timecontrol_SetInputClockFreq_obj = ncx_find_object(
      intri_timecontrol_mod,
      "intri-timecontrol-SetInputClockFreq");
  if (intri_timecontrol_SetInputClockFreq_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_timecontrol,
      "intri-timecontrol-SetInputClockFreq",
      AGT_RPC_PH_INVOKE,
      intri_timecontrol_TimeControl_SetInputClockFreq_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_timecontrol_GetInputClockFreq_obj = ncx_find_object(
      intri_timecontrol_mod,
      "intri-timecontrol-GetInputClockFreq");
  if (intri_timecontrol_GetInputClockFreq_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_timecontrol,
      "intri-timecontrol-GetInputClockFreq",
      AGT_RPC_PH_INVOKE,
      intri_timecontrol_TimeControl_GetInputClockFreq_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_timecontrol_SetToDSource_obj = ncx_find_object(
      intri_timecontrol_mod,
      "intri-timecontrol-SetToDSource");
  if (intri_timecontrol_SetToDSource_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_timecontrol,
      "intri-timecontrol-SetToDSource",
      AGT_RPC_PH_INVOKE,
      intri_timecontrol_TimeControl_SetToDSource_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_timecontrol_GetToDSource_obj = ncx_find_object(
      intri_timecontrol_mod,
      "intri-timecontrol-GetToDSource");
  if (intri_timecontrol_GetToDSource_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_timecontrol,
      "intri-timecontrol-GetToDSource",
      AGT_RPC_PH_INVOKE,
      intri_timecontrol_TimeControl_GetToDSource_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_timecontrol_SetToD_obj = ncx_find_object(
      intri_timecontrol_mod,
      "intri-timecontrol-SetToD");
  if (intri_timecontrol_SetToD_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_timecontrol,
      "intri-timecontrol-SetToD",
      AGT_RPC_PH_INVOKE,
      intri_timecontrol_TimeControl_SetToD_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_timecontrol_GetToD_obj = ncx_find_object(
      intri_timecontrol_mod,
      "intri-timecontrol-GetToD");
  if (intri_timecontrol_GetToD_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_timecontrol,
      "intri-timecontrol-GetToD",
      AGT_RPC_PH_INVOKE,
      intri_timecontrol_TimeControl_GetToD_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_timecontrol_SetFrequencyControl_obj = ncx_find_object(
      intri_timecontrol_mod,
      "intri-timecontrol-SetFrequencyControl");
  if (intri_timecontrol_SetFrequencyControl_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_timecontrol,
      "intri-timecontrol-SetFrequencyControl",
      AGT_RPC_PH_INVOKE,
      intri_timecontrol_TimeControl_SetFrequencyControl_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_timecontrol_GetFrequencyControl_obj = ncx_find_object(
      intri_timecontrol_mod,
      "intri-timecontrol-GetFrequencyControl");
  if (intri_timecontrol_GetFrequencyControl_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_timecontrol,
      "intri-timecontrol-GetFrequencyControl",
      AGT_RPC_PH_INVOKE,
      intri_timecontrol_TimeControl_GetFrequencyControl_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_timecontrol_SetPhaseControl_obj = ncx_find_object(
      intri_timecontrol_mod,
      "intri-timecontrol-SetPhaseControl");
  if (intri_timecontrol_SetPhaseControl_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_timecontrol,
      "intri-timecontrol-SetPhaseControl",
      AGT_RPC_PH_INVOKE,
      intri_timecontrol_TimeControl_SetPhaseControl_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_timecontrol_GetPhaseControl_obj = ncx_find_object(
      intri_timecontrol_mod,
      "intri-timecontrol-GetPhaseControl");
  if (intri_timecontrol_GetPhaseControl_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_timecontrol,
      "intri-timecontrol-GetPhaseControl",
      AGT_RPC_PH_INVOKE,
      intri_timecontrol_TimeControl_GetPhaseControl_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_timecontrol_SetPhaseSlopeLimit_obj = ncx_find_object(
      intri_timecontrol_mod,
      "intri-timecontrol-SetPhaseSlopeLimit");
  if (intri_timecontrol_SetPhaseSlopeLimit_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_timecontrol,
      "intri-timecontrol-SetPhaseSlopeLimit",
      AGT_RPC_PH_INVOKE,
      intri_timecontrol_TimeControl_SetPhaseSlopeLimit_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_timecontrol_GetPhaseSlopeLimit_obj = ncx_find_object(
      intri_timecontrol_mod,
      "intri-timecontrol-GetPhaseSlopeLimit");
  if (intri_timecontrol_GetPhaseSlopeLimit_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_timecontrol,
      "intri-timecontrol-GetPhaseSlopeLimit",
      AGT_RPC_PH_INVOKE,
      intri_timecontrol_TimeControl_GetPhaseSlopeLimit_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_timecontrol_SetPhaseControlTimer_obj = ncx_find_object(
      intri_timecontrol_mod,
      "intri-timecontrol-SetPhaseControlTimer");
  if (intri_timecontrol_SetPhaseControlTimer_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_timecontrol,
      "intri-timecontrol-SetPhaseControlTimer",
      AGT_RPC_PH_INVOKE,
      intri_timecontrol_TimeControl_SetPhaseControlTimer_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_timecontrol_GetPhaseControlTimer_obj = ncx_find_object(
      intri_timecontrol_mod,
      "intri-timecontrol-GetPhaseControlTimer");
  if (intri_timecontrol_GetPhaseControlTimer_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_timecontrol,
      "intri-timecontrol-GetPhaseControlTimer",
      AGT_RPC_PH_INVOKE,
      intri_timecontrol_TimeControl_GetPhaseControlTimer_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  return res;
}

void y_intri_timecontrol_cleanup(void) {
  agt_rpc_unregister_method(
      y_M_intri_timecontrol,
      "intri-timecontrol-GetInputMonitorStatus");

  agt_rpc_unregister_method(
      y_M_intri_timecontrol,
      "intri-timecontrol-GetDPLLStatus");

  agt_rpc_unregister_method(
      y_M_intri_timecontrol,
      "intri-timecontrol-SetDPLLRefPriority");

  agt_rpc_unregister_method(
      y_M_intri_timecontrol,
      "intri-timecontrol-GetDPLLRefPriority");

  agt_rpc_unregister_method(
      y_M_intri_timecontrol,
      "intri-timecontrol-SetInputClockFreq");

  agt_rpc_unregister_method(
      y_M_intri_timecontrol,
      "intri-timecontrol-GetInputClockFreq");

  agt_rpc_unregister_method(
      y_M_intri_timecontrol,
      "intri-timecontrol-SetToDSource");

  agt_rpc_unregister_method(
      y_M_intri_timecontrol,
      "intri-timecontrol-GetToDSource");

  agt_rpc_unregister_method(
      y_M_intri_timecontrol,
      "intri-timecontrol-SetToD");

  agt_rpc_unregister_method(
      y_M_intri_timecontrol,
      "intri-timecontrol-GetToD");

  agt_rpc_unregister_method(
      y_M_intri_timecontrol,
      "intri-timecontrol-SetFrequencyControl");

  agt_rpc_unregister_method(
      y_M_intri_timecontrol,
      "intri-timecontrol-GetFrequencyControl");

  agt_rpc_unregister_method(
      y_M_intri_timecontrol,
      "intri-timecontrol-SetPhaseControl");

  agt_rpc_unregister_method(
      y_M_intri_timecontrol,
      "intri-timecontrol-GetPhaseControl");

  agt_rpc_unregister_method(
      y_M_intri_timecontrol,
      "intri-timecontrol-SetPhaseSlopeLimit");

  agt_rpc_unregister_method(
      y_M_intri_timecontrol,
      "intri-timecontrol-GetPhaseSlopeLimit");

  agt_rpc_unregister_method(
      y_M_intri_timecontrol,
      "intri-timecontrol-SetPhaseControlTimer");

  agt_rpc_unregister_method(
      y_M_intri_timecontrol,
      "intri-timecontrol-GetPhaseControlTimer");

}

