

t-list:
	gcc ./go.list.sample.c ../.libintrishare/libintrishare.a -lpthread -o go.list.sample.o; ./go.list.sample.o

t-oneof:
	gcc ./go.oneof.sample.c ../.libintrishare/libintrishare.a -lpthread -o go.oneof.sample.o; ./go.oneof.sample.o

t-map:
	gcc ./go.map.sample.c ../.libintrishare/libintrishare.a -lpthread -o go.map.sample.o; ./go.map.sample.o
