// Code generated by protoc-gen-yang(*.c) DO NOT EDIT.

/*****************************************************************************************************
 * Copyright (C) 2017-2022 by Intrising
 *  - ian0113@intrising.com.tw
 * 
 * Generated by protoc-gen-yang@gen-yang
 * 
 *****************************************************************************************************/

#include <libxml/xmlstring.h>
#include "agt.h"
#include "agt_cb.h"
#include "agt_rpc.h"
#include "agt_timer.h"
#include "agt_util.h"
#include "dlq.h"
#include "ncx.h"
#include "ncx_feature.h"
#include "ncxmod.h"
#include "ncxtypes.h"
#include "procdefs.h"
#include "rpc.h"
#include "ses.h"
#include "status.h"
#include "val.h"
#include "val_util.h"
#include "xml_util.h"

#include "intri-time-trans.h"
#include "../../../../../../../../.libintrishare/libintrishare.h"

#include "../../../../../github.com/Intrising/intri-type/common/intri-common-trans.h"
#include "../../../../../github.com/golang/protobuf/ptypes/empty/intri-empty-trans.h"
#include "../../../../../github.com/golang/protobuf/ptypes/timestamp/intri-timestamp-trans.h"
status_t build_to_xml_time_Config (
    val_value_t *parentval,
    struct timepb_Config *entry) {
  status_t res = NO_ERR;
  val_value_t *childval = NULL;
  /* ---------------------------------------------------------------------------------------------------- */
  childval =  agt_make_object(
      parentval->obj,
    "Mode",
    &res);
  if (childval != NULL) {
    val_add_child(childval, parentval);
  } else if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  /* enum */
  VAL_ENUM(childval) = entry->Mode;
  /* ---------------------------------------------------------------------------------------------------- */
  childval =  agt_make_object(
      parentval->obj,
    "MainNTPServer",
    &res);
  if (childval != NULL) {
    val_add_child(childval, parentval);
  } else if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  /* string */
  VAL_STRING(childval) = entry->MainNTPServer;
  /* ---------------------------------------------------------------------------------------------------- */
  childval =  agt_make_object(
      parentval->obj,
    "BackupNTPServer",
    &res);
  if (childval != NULL) {
    val_add_child(childval, parentval);
  } else if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  /* string */
  VAL_STRING(childval) = entry->BackupNTPServer;
  /* ---------------------------------------------------------------------------------------------------- */
  childval =  agt_make_object(
      parentval->obj,
    "TrustedServerEnabled",
    &res);
  if (childval != NULL) {
    val_add_child(childval, parentval);
  } else if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  /* bool */
  VAL_BOOL(childval) = entry->TrustedServerEnabled;
  /* ---------------------------------------------------------------------------------------------------- */
  childval =  agt_make_object(
      parentval->obj,
    "SyncInterval",
    &res);
  if (childval != NULL) {
    val_add_child(childval, parentval);
  } else if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  /* int32 */
  VAL_INT(childval) = entry->SyncInterval;
  /* ---------------------------------------------------------------------------------------------------- */
  childval =  agt_make_object(
      parentval->obj,
    "TimeZone",
    &res);
  if (childval != NULL) {
    val_add_child(childval, parentval);
  } else if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  /* string */
  VAL_STRING(childval) = entry->TimeZone;
  /* ---------------------------------------------------------------------------------------------------- */
  childval =  agt_make_object(
      parentval->obj,
    "TimeFormat",
    &res);
  if (childval != NULL) {
    val_add_child(childval, parentval);
  } else if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  /* string */
  VAL_STRING(childval) = entry->TimeFormat;
  /* ---------------------------------------------------------------------------------------------------- */
  childval =  agt_make_object(
      parentval->obj,
    "DateFormat",
    &res);
  if (childval != NULL) {
    val_add_child(childval, parentval);
  } else if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  /* string */
  VAL_STRING(childval) = entry->DateFormat;
  /* ---------------------------------------------------------------------------------------------------- */
  childval =  agt_make_object(
      parentval->obj,
    "Manual",
    &res);
  if (childval != NULL) {
    val_add_child(childval, parentval);
  } else if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  /* string */
  VAL_STRING(childval) = entry->Manual;
  return res;
}

status_t build_to_xml_time_ListTimeZones (
    val_value_t *parentval,
    struct timepb_ListTimeZones *entry) {
  status_t res = NO_ERR;
  val_value_t *childval = NULL;
  /* ---------------------------------------------------------------------------------------------------- */
  childval =  agt_make_object(
      parentval->obj,
    "List",
    &res);
  if (childval != NULL) {
    val_add_child(childval, parentval);
  } else if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  /* list */
  for (int i = 0; i < entry->List_Len; i++) {
  val_value_t *listval = NULL;
listval =  agt_make_object(
    childval->obj,
    "List_Entry",
    &res);
if (listval != NULL) {
  val_add_child(listval, childval);
} else if (res != NO_ERR) {
  return SET_ERROR(res);
}
VAL_STRING(listval) = entry->List[i];
  }
  return res;
}

status_t build_to_xml_time_Status (
    val_value_t *parentval,
    struct timepb_Status *entry) {
  status_t res = NO_ERR;
  val_value_t *childval = NULL;
  /* ---------------------------------------------------------------------------------------------------- */
  childval =  agt_make_object(
      parentval->obj,
    "Status",
    &res);
  if (childval != NULL) {
    val_add_child(childval, parentval);
  } else if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  /* enum */
  VAL_ENUM(childval) = entry->Status;
  /* ---------------------------------------------------------------------------------------------------- */
  childval =  agt_make_object(
      parentval->obj,
    "LocalTime",
    &res);
  if (childval != NULL) {
    val_add_child(childval, parentval);
  } else if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  /* string */
  VAL_STRING(childval) = entry->LocalTime;
  /* ---------------------------------------------------------------------------------------------------- */
  childval =  agt_make_object(
      parentval->obj,
    "LocalDate",
    &res);
  if (childval != NULL) {
    val_add_child(childval, parentval);
  } else if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  /* string */
  VAL_STRING(childval) = entry->LocalDate;
  /* ---------------------------------------------------------------------------------------------------- */
  childval =  agt_make_object(
      parentval->obj,
    "UsedNTPServer",
    &res);
  if (childval != NULL) {
    val_add_child(childval, parentval);
  } else if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  /* string */
  VAL_STRING(childval) = entry->UsedNTPServer;
  return res;
}

status_t build_to_xml_time_RequestWithTimestamp (
    val_value_t *parentval,
    struct timepb_RequestWithTimestamp *entry) {
  status_t res = NO_ERR;
  val_value_t *childval = NULL;
  /* ---------------------------------------------------------------------------------------------------- */
  childval =  agt_make_object(
      parentval->obj,
    "Ts",
    &res);
  if (childval != NULL) {
    val_add_child(childval, parentval);
  } else if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  /* message */
   build_to_xml_timestamp_Timestamp(
      childval,
    entry->Ts);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  return res;
}

status_t build_to_xml_time_RequestWithInt64 (
    val_value_t *parentval,
    struct timepb_RequestWithInt64 *entry) {
  status_t res = NO_ERR;
  val_value_t *childval = NULL;
  /* ---------------------------------------------------------------------------------------------------- */
  childval =  agt_make_object(
      parentval->obj,
    "Ts",
    &res);
  if (childval != NULL) {
    val_add_child(childval, parentval);
  } else if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  /* int64 */
  VAL_LONG(childval) = entry->Ts;
  return res;
}

status_t build_to_xml_time_Response (
    val_value_t *parentval,
    struct timepb_Response *entry) {
  status_t res = NO_ERR;
  val_value_t *childval = NULL;
  /* ---------------------------------------------------------------------------------------------------- */
  childval =  agt_make_object(
      parentval->obj,
    "Ts",
    &res);
  if (childval != NULL) {
    val_add_child(childval, parentval);
  } else if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  /* string */
  VAL_STRING(childval) = entry->Ts;
  return res;
}

