
/*****************************************************************************************************
 * Copyright (C) 2017-2022 by Intrising
 *  - ian0113@intrising.com.tw
 * 
 * Generated by protoc-gen-yang@gen-yang
 * 
 *****************************************************************************************************/

#include <libxml/xmlstring.h>
#include "agt.h"
#include "agt_cb.h"
#include "agt_rpc.h"
#include "agt_timer.h"
#include "agt_util.h"
#include "dlq.h"
#include "ncx.h"
#include "ncx_feature.h"
#include "ncxmod.h"
#include "ncxtypes.h"
#include "procdefs.h"
#include "rpc.h"
#include "ses.h"
#include "status.h"
#include "val.h"
#include "val_util.h"
#include "xml_util.h"

#include "intri-monitor@2022-06-24.h"
#include "../../../../../../../../.libintrishare/libintrishare.h"
#include "../../../../../../genc-trans/github.com/Intrising/intri-type/core/monitor/intri-monitor-trans.h"
#include "../../../../../../genc-trans/github.com/Intrising/intri-type/device/intri-device-trans.h"
#include "../../../../../../genc-trans/github.com/Intrising/intri-type/event/intri-event-trans.h"
#include "../../../../../../genc-trans/github.com/golang/protobuf/ptypes/empty/intri-empty-trans.h"

static ncx_module_t *intri_monitor_mod;
static obj_template_t *intri_monitor_GetConfig_obj;
static obj_template_t *intri_monitor_GetDeviceLimitConfig_obj;
static obj_template_t *intri_monitor_UpdateDeviceScorllBarValueEntry_obj;
static obj_template_t *intri_monitor_UpdateDeviceScorllBarValue_obj;
static obj_template_t *intri_monitor_GetSystemLimitConfig_obj;
static obj_template_t *intri_monitor_UpdateSystemScorllBarValueEntry_obj;
static obj_template_t *intri_monitor_UpdateSystemScorllBarValue_obj;
static obj_template_t *intri_monitor_GetStatus_obj;
static obj_template_t *intri_monitor_GetDeviceStatus_obj;
static obj_template_t *intri_monitor_GetSystemStatus_obj;
static obj_template_t *intri_monitor_GetLEDStatus_obj;

static status_t intri_monitor_Monitor_GetConfig_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct emptypb_Empty in;
  struct monitorpb_Config out;
  monitor_Monitor_GetConfig(&in, &out);
  val_value_t *resval = val_new_value();
  res =  build_to_xml_monitor_Config(
      resval,
    &out);
  return res;
}

static status_t intri_monitor_Monitor_GetDeviceLimitConfig_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct emptypb_Empty in;
  struct monitorpb_DeviceLimitConfig out;
  monitor_Monitor_GetDeviceLimitConfig(&in, &out);
  val_value_t *resval = val_new_value();
  res =  build_to_xml_monitor_DeviceLimitConfig(
      resval,
    &out);
  return res;
}

static status_t intri_monitor_Monitor_UpdateDeviceScorllBarValueEntry_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct monitorpb_DeviceScorllBarValueEntry in;
  struct emptypb_Empty out;
  monitor_Monitor_UpdateDeviceScorllBarValueEntry(&in, &out);
  val_value_t *resval = val_new_value();
  return res;
}

static status_t intri_monitor_Monitor_UpdateDeviceScorllBarValue_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct monitorpb_DeviceScorllBarValue in;
  struct emptypb_Empty out;
  monitor_Monitor_UpdateDeviceScorllBarValue(&in, &out);
  val_value_t *resval = val_new_value();
  return res;
}

static status_t intri_monitor_Monitor_GetSystemLimitConfig_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct emptypb_Empty in;
  struct monitorpb_SystemLimitConfig out;
  monitor_Monitor_GetSystemLimitConfig(&in, &out);
  val_value_t *resval = val_new_value();
  res =  build_to_xml_monitor_SystemLimitConfig(
      resval,
    &out);
  return res;
}

static status_t intri_monitor_Monitor_UpdateSystemScorllBarValueEntry_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct monitorpb_SystemScorllBarValueEntry in;
  struct emptypb_Empty out;
  monitor_Monitor_UpdateSystemScorllBarValueEntry(&in, &out);
  val_value_t *resval = val_new_value();
  return res;
}

static status_t intri_monitor_Monitor_UpdateSystemScorllBarValue_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct monitorpb_SystemScorllBarValue in;
  struct emptypb_Empty out;
  monitor_Monitor_UpdateSystemScorllBarValue(&in, &out);
  val_value_t *resval = val_new_value();
  return res;
}

static status_t intri_monitor_Monitor_GetStatus_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct emptypb_Empty in;
  struct monitorpb_Status out;
  monitor_Monitor_GetStatus(&in, &out);
  val_value_t *resval = val_new_value();
  res =  build_to_xml_monitor_Status(
      resval,
    &out);
  return res;
}

static status_t intri_monitor_Monitor_GetDeviceStatus_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct emptypb_Empty in;
  struct monitorpb_DeviceStatus out;
  monitor_Monitor_GetDeviceStatus(&in, &out);
  val_value_t *resval = val_new_value();
  res =  build_to_xml_monitor_DeviceStatus(
      resval,
    &out);
  return res;
}

static status_t intri_monitor_Monitor_GetSystemStatus_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct emptypb_Empty in;
  struct monitorpb_SystemStatus out;
  monitor_Monitor_GetSystemStatus(&in, &out);
  val_value_t *resval = val_new_value();
  res =  build_to_xml_monitor_SystemStatus(
      resval,
    &out);
  return res;
}

static status_t intri_monitor_Monitor_GetLEDStatus_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct emptypb_Empty in;
  struct monitorpb_LEDStatus out;
  monitor_Monitor_GetLEDStatus(&in, &out);
  val_value_t *resval = val_new_value();
  res =  build_to_xml_monitor_LEDStatus(
      resval,
    &out);
  return res;
}

status_t y_intri_monitor_init(
    const xmlChar *modname,
    const xmlChar *revision) {
  status_t res = NO_ERR;
  agt_profile_t *agt_profile = agt_get_profile();

  if (xml_strcmp(modname, y_M_intri_monitor)) {
    return ERR_NCX_UNKNOWN_MODULE;
  }

  if (revision && xml_strcmp(revision, y_R_intri_monitor)) {
    return ERR_NCX_WRONG_VERSION;
  }

  res = ncxmod_load_module(
      y_M_intri_monitor,
      y_R_intri_monitor,
      &agt_profile->agt_savedevQ,
      &intri_monitor_mod);
  if (res != NO_ERR) {
    return res;
  }

  intri_monitor_GetConfig_obj = ncx_find_object(
      intri_monitor_mod,
      "intri-monitor-GetConfig");
  if (intri_monitor_GetConfig_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_monitor,
      "intri-monitor-GetConfig",
      AGT_RPC_PH_INVOKE,
      intri_monitor_Monitor_GetConfig_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_monitor_GetDeviceLimitConfig_obj = ncx_find_object(
      intri_monitor_mod,
      "intri-monitor-GetDeviceLimitConfig");
  if (intri_monitor_GetDeviceLimitConfig_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_monitor,
      "intri-monitor-GetDeviceLimitConfig",
      AGT_RPC_PH_INVOKE,
      intri_monitor_Monitor_GetDeviceLimitConfig_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_monitor_UpdateDeviceScorllBarValueEntry_obj = ncx_find_object(
      intri_monitor_mod,
      "intri-monitor-UpdateDeviceScorllBarValueEntry");
  if (intri_monitor_UpdateDeviceScorllBarValueEntry_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_monitor,
      "intri-monitor-UpdateDeviceScorllBarValueEntry",
      AGT_RPC_PH_INVOKE,
      intri_monitor_Monitor_UpdateDeviceScorllBarValueEntry_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_monitor_UpdateDeviceScorllBarValue_obj = ncx_find_object(
      intri_monitor_mod,
      "intri-monitor-UpdateDeviceScorllBarValue");
  if (intri_monitor_UpdateDeviceScorllBarValue_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_monitor,
      "intri-monitor-UpdateDeviceScorllBarValue",
      AGT_RPC_PH_INVOKE,
      intri_monitor_Monitor_UpdateDeviceScorllBarValue_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_monitor_GetSystemLimitConfig_obj = ncx_find_object(
      intri_monitor_mod,
      "intri-monitor-GetSystemLimitConfig");
  if (intri_monitor_GetSystemLimitConfig_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_monitor,
      "intri-monitor-GetSystemLimitConfig",
      AGT_RPC_PH_INVOKE,
      intri_monitor_Monitor_GetSystemLimitConfig_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_monitor_UpdateSystemScorllBarValueEntry_obj = ncx_find_object(
      intri_monitor_mod,
      "intri-monitor-UpdateSystemScorllBarValueEntry");
  if (intri_monitor_UpdateSystemScorllBarValueEntry_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_monitor,
      "intri-monitor-UpdateSystemScorllBarValueEntry",
      AGT_RPC_PH_INVOKE,
      intri_monitor_Monitor_UpdateSystemScorllBarValueEntry_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_monitor_UpdateSystemScorllBarValue_obj = ncx_find_object(
      intri_monitor_mod,
      "intri-monitor-UpdateSystemScorllBarValue");
  if (intri_monitor_UpdateSystemScorllBarValue_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_monitor,
      "intri-monitor-UpdateSystemScorllBarValue",
      AGT_RPC_PH_INVOKE,
      intri_monitor_Monitor_UpdateSystemScorllBarValue_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_monitor_GetStatus_obj = ncx_find_object(
      intri_monitor_mod,
      "intri-monitor-GetStatus");
  if (intri_monitor_GetStatus_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_monitor,
      "intri-monitor-GetStatus",
      AGT_RPC_PH_INVOKE,
      intri_monitor_Monitor_GetStatus_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_monitor_GetDeviceStatus_obj = ncx_find_object(
      intri_monitor_mod,
      "intri-monitor-GetDeviceStatus");
  if (intri_monitor_GetDeviceStatus_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_monitor,
      "intri-monitor-GetDeviceStatus",
      AGT_RPC_PH_INVOKE,
      intri_monitor_Monitor_GetDeviceStatus_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_monitor_GetSystemStatus_obj = ncx_find_object(
      intri_monitor_mod,
      "intri-monitor-GetSystemStatus");
  if (intri_monitor_GetSystemStatus_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_monitor,
      "intri-monitor-GetSystemStatus",
      AGT_RPC_PH_INVOKE,
      intri_monitor_Monitor_GetSystemStatus_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_monitor_GetLEDStatus_obj = ncx_find_object(
      intri_monitor_mod,
      "intri-monitor-GetLEDStatus");
  if (intri_monitor_GetLEDStatus_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_monitor,
      "intri-monitor-GetLEDStatus",
      AGT_RPC_PH_INVOKE,
      intri_monitor_Monitor_GetLEDStatus_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  return res;
}

void y_intri_monitor_cleanup(void) {
  agt_rpc_unregister_method(
      y_M_intri_monitor,
      "intri-monitor-GetConfig");

  agt_rpc_unregister_method(
      y_M_intri_monitor,
      "intri-monitor-GetDeviceLimitConfig");

  agt_rpc_unregister_method(
      y_M_intri_monitor,
      "intri-monitor-UpdateDeviceScorllBarValueEntry");

  agt_rpc_unregister_method(
      y_M_intri_monitor,
      "intri-monitor-UpdateDeviceScorllBarValue");

  agt_rpc_unregister_method(
      y_M_intri_monitor,
      "intri-monitor-GetSystemLimitConfig");

  agt_rpc_unregister_method(
      y_M_intri_monitor,
      "intri-monitor-UpdateSystemScorllBarValueEntry");

  agt_rpc_unregister_method(
      y_M_intri_monitor,
      "intri-monitor-UpdateSystemScorllBarValue");

  agt_rpc_unregister_method(
      y_M_intri_monitor,
      "intri-monitor-GetStatus");

  agt_rpc_unregister_method(
      y_M_intri_monitor,
      "intri-monitor-GetDeviceStatus");

  agt_rpc_unregister_method(
      y_M_intri_monitor,
      "intri-monitor-GetSystemStatus");

  agt_rpc_unregister_method(
      y_M_intri_monitor,
      "intri-monitor-GetLEDStatus");

}

