// Code generated by protoc-gen-yang(*.c) DO NOT EDIT.

/*****************************************************************************************************
 * Copyright (C) 2017-2022 by Intrising
 *  - ian0113@intrising.com.tw
 * 
 * Generated by protoc-gen-yang@gen-yang
 * 
 *****************************************************************************************************/

#include <libxml/xmlstring.h>
#include "agt.h"
#include "agt_cb.h"
#include "agt_rpc.h"
#include "agt_timer.h"
#include "agt_util.h"
#include "dlq.h"
#include "ncx.h"
#include "ncx_feature.h"
#include "ncxmod.h"
#include "ncxtypes.h"
#include "procdefs.h"
#include "rpc.h"
#include "ses.h"
#include "status.h"
#include "val.h"
#include "val_util.h"
#include "xml_util.h"

#include "intri-timecontrol-trans.h"
#include "../../../../../../../.libintrishare/libintrishare.h"

#include "../../../../github.com/Intrising/intri-type/device/intri-device-trans.h"
#include "../../../../github.com/golang/protobuf/ptypes/empty/intri-empty-trans.h"
#include "../../../../github.com/golang/protobuf/ptypes/timestamp/intri-timestamp-trans.h"
status_t build_to_xml_timecontrol_InputClockManage (
    val_value_t *parentval,
    struct timecontrolpb_InputClockManage *entry) {
  status_t res = NO_ERR;
  val_value_t *childval = NULL;
  /* ---------------------------------------------------------------------------------------------------- */
  childval =  agt_make_object(
      parentval->obj,
    "List",
    &res);
  if (childval != NULL) {
    val_add_child(childval, parentval);
  } else if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  /* list */
  for (int i = 0; i < entry->List_Len; i++) {
  val_value_t *listval = NULL;
listval =  agt_make_object(
    childval->obj,
    "List_Entry",
    &res);
if (listval != NULL) {
  val_add_child(listval, childval);
} else if (res != NO_ERR) {
  return SET_ERROR(res);
}
res =  build_to_xml_timecontrol_InputClockManageEntry(
    listval,
    entry->List[i]);
if (res != NO_ERR) {
  return SET_ERROR(res);
}
  }
  return res;
}

status_t build_to_xml_timecontrol_InputClockManageEntry (
    val_value_t *parentval,
    struct timecontrolpb_InputClockManageEntry *entry) {
  status_t res = NO_ERR;
  val_value_t *childval = NULL;
  /* ---------------------------------------------------------------------------------------------------- */
  childval =  agt_make_object(
      parentval->obj,
    "InputCLK",
    &res);
  if (childval != NULL) {
    val_add_child(childval, parentval);
  } else if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  /* enum */
  VAL_ENUM(childval) = entry->InputCLK;
  return res;
}

status_t build_to_xml_timecontrol_MonitorStatus (
    val_value_t *parentval,
    struct timecontrolpb_MonitorStatus *entry) {
  status_t res = NO_ERR;
  val_value_t *childval = NULL;
  /* ---------------------------------------------------------------------------------------------------- */
  childval =  agt_make_object(
      parentval->obj,
    "List",
    &res);
  if (childval != NULL) {
    val_add_child(childval, parentval);
  } else if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  /* list */
  for (int i = 0; i < entry->List_Len; i++) {
  val_value_t *listval = NULL;
listval =  agt_make_object(
    childval->obj,
    "List_Entry",
    &res);
if (listval != NULL) {
  val_add_child(listval, childval);
} else if (res != NO_ERR) {
  return SET_ERROR(res);
}
res =  build_to_xml_timecontrol_MonitorStatusEntry(
    listval,
    entry->List[i]);
if (res != NO_ERR) {
  return SET_ERROR(res);
}
  }
  return res;
}

status_t build_to_xml_timecontrol_MonitorStatusEntry (
    val_value_t *parentval,
    struct timecontrolpb_MonitorStatusEntry *entry) {
  status_t res = NO_ERR;
  val_value_t *childval = NULL;
  /* ---------------------------------------------------------------------------------------------------- */
  childval =  agt_make_object(
      parentval->obj,
    "InputCLK",
    &res);
  if (childval != NULL) {
    val_add_child(childval, parentval);
  } else if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  /* enum */
  VAL_ENUM(childval) = entry->InputCLK;
  /* ---------------------------------------------------------------------------------------------------- */
  childval =  agt_make_object(
      parentval->obj,
    "StatusList",
    &res);
  if (childval != NULL) {
    val_add_child(childval, parentval);
  } else if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  /* list */
  for (int i = 0; i < entry->StatusList_Len; i++) {
  val_value_t *listval = NULL;
listval =  agt_make_object(
    childval->obj,
    "StatusList_Entry",
    &res);
if (listval != NULL) {
  val_add_child(listval, childval);
} else if (res != NO_ERR) {
  return SET_ERROR(res);
}
res =  build_to_xml_timecontrol_StatusInputBit(
    listval,
    entry->StatusList[i]);
if (res != NO_ERR) {
  return SET_ERROR(res);
}
  }
  /* ---------------------------------------------------------------------------------------------------- */
  childval =  agt_make_object(
      parentval->obj,
    "Valid",
    &res);
  if (childval != NULL) {
    val_add_child(childval, parentval);
  } else if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  /* bool */
  VAL_BOOL(childval) = entry->Valid;
  return res;
}

status_t build_to_xml_timecontrol_StatusInputBit (
    val_value_t *parentval,
    struct timecontrolpb_StatusInputBit *entry) {
  status_t res = NO_ERR;
  val_value_t *childval = NULL;
  /* ---------------------------------------------------------------------------------------------------- */
  childval =  agt_make_object(
      parentval->obj,
    "Type",
    &res);
  if (childval != NULL) {
    val_add_child(childval, parentval);
  } else if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  /* enum */
  VAL_ENUM(childval) = entry->Type;
  /* ---------------------------------------------------------------------------------------------------- */
  childval =  agt_make_object(
      parentval->obj,
    "Valid",
    &res);
  if (childval != NULL) {
    val_add_child(childval, parentval);
  } else if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  /* bool */
  VAL_BOOL(childval) = entry->Valid;
  return res;
}

status_t build_to_xml_timecontrol_DPLLManage (
    val_value_t *parentval,
    struct timecontrolpb_DPLLManage *entry) {
  status_t res = NO_ERR;
  val_value_t *childval = NULL;
  /* ---------------------------------------------------------------------------------------------------- */
  childval =  agt_make_object(
      parentval->obj,
    "List",
    &res);
  if (childval != NULL) {
    val_add_child(childval, parentval);
  } else if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  /* list */
  for (int i = 0; i < entry->List_Len; i++) {
  val_value_t *listval = NULL;
listval =  agt_make_object(
    childval->obj,
    "List_Entry",
    &res);
if (listval != NULL) {
  val_add_child(listval, childval);
} else if (res != NO_ERR) {
  return SET_ERROR(res);
}
res =  build_to_xml_timecontrol_DPLLManageEntry(
    listval,
    entry->List[i]);
if (res != NO_ERR) {
  return SET_ERROR(res);
}
  }
  return res;
}

status_t build_to_xml_timecontrol_DPLLManageEntry (
    val_value_t *parentval,
    struct timecontrolpb_DPLLManageEntry *entry) {
  status_t res = NO_ERR;
  val_value_t *childval = NULL;
  /* ---------------------------------------------------------------------------------------------------- */
  childval =  agt_make_object(
      parentval->obj,
    "Index",
    &res);
  if (childval != NULL) {
    val_add_child(childval, parentval);
  } else if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  /* enum */
  VAL_ENUM(childval) = entry->Index;
  return res;
}

status_t build_to_xml_timecontrol_DPLLStatus (
    val_value_t *parentval,
    struct timecontrolpb_DPLLStatus *entry) {
  status_t res = NO_ERR;
  val_value_t *childval = NULL;
  /* ---------------------------------------------------------------------------------------------------- */
  childval =  agt_make_object(
      parentval->obj,
    "List",
    &res);
  if (childval != NULL) {
    val_add_child(childval, parentval);
  } else if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  /* list */
  for (int i = 0; i < entry->List_Len; i++) {
  val_value_t *listval = NULL;
listval =  agt_make_object(
    childval->obj,
    "List_Entry",
    &res);
if (listval != NULL) {
  val_add_child(listval, childval);
} else if (res != NO_ERR) {
  return SET_ERROR(res);
}
res =  build_to_xml_timecontrol_DPLLStatusEntry(
    listval,
    entry->List[i]);
if (res != NO_ERR) {
  return SET_ERROR(res);
}
  }
  return res;
}

status_t build_to_xml_timecontrol_DPLLStatusEntry (
    val_value_t *parentval,
    struct timecontrolpb_DPLLStatusEntry *entry) {
  status_t res = NO_ERR;
  val_value_t *childval = NULL;
  /* ---------------------------------------------------------------------------------------------------- */
  childval =  agt_make_object(
      parentval->obj,
    "Index",
    &res);
  if (childval != NULL) {
    val_add_child(childval, parentval);
  } else if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  /* enum */
  VAL_ENUM(childval) = entry->Index;
  /* ---------------------------------------------------------------------------------------------------- */
  childval =  agt_make_object(
      parentval->obj,
    "StatusType",
    &res);
  if (childval != NULL) {
    val_add_child(childval, parentval);
  } else if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  /* enum */
  VAL_ENUM(childval) = entry->StatusType;
  /* ---------------------------------------------------------------------------------------------------- */
  childval =  agt_make_object(
      parentval->obj,
    "InputCLK",
    &res);
  if (childval != NULL) {
    val_add_child(childval, parentval);
  } else if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  /* enum */
  VAL_ENUM(childval) = entry->InputCLK;
  return res;
}

status_t build_to_xml_timecontrol_DPLLRefPriorityManage (
    val_value_t *parentval,
    struct timecontrolpb_DPLLRefPriorityManage *entry) {
  status_t res = NO_ERR;
  val_value_t *childval = NULL;
  /* ---------------------------------------------------------------------------------------------------- */
  childval =  agt_make_object(
      parentval->obj,
    "List",
    &res);
  if (childval != NULL) {
    val_add_child(childval, parentval);
  } else if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  /* list */
  for (int i = 0; i < entry->List_Len; i++) {
  val_value_t *listval = NULL;
listval =  agt_make_object(
    childval->obj,
    "List_Entry",
    &res);
if (listval != NULL) {
  val_add_child(listval, childval);
} else if (res != NO_ERR) {
  return SET_ERROR(res);
}
res =  build_to_xml_timecontrol_DPLLRefPriorityManageEntry(
    listval,
    entry->List[i]);
if (res != NO_ERR) {
  return SET_ERROR(res);
}
  }
  return res;
}

status_t build_to_xml_timecontrol_DPLLRefPriorityManageEntry (
    val_value_t *parentval,
    struct timecontrolpb_DPLLRefPriorityManageEntry *entry) {
  status_t res = NO_ERR;
  val_value_t *childval = NULL;
  /* ---------------------------------------------------------------------------------------------------- */
  childval =  agt_make_object(
      parentval->obj,
    "Index",
    &res);
  if (childval != NULL) {
    val_add_child(childval, parentval);
  } else if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  /* enum */
  VAL_ENUM(childval) = entry->Index;
  /* ---------------------------------------------------------------------------------------------------- */
  childval =  agt_make_object(
      parentval->obj,
    "PriorityList",
    &res);
  if (childval != NULL) {
    val_add_child(childval, parentval);
  } else if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  /* list */
  for (int i = 0; i < entry->PriorityList_Len; i++) {
  val_value_t *listval = NULL;
listval =  agt_make_object(
    childval->obj,
    "PriorityList_Entry",
    &res);
if (listval != NULL) {
  val_add_child(listval, childval);
} else if (res != NO_ERR) {
  return SET_ERROR(res);
}
VAL_ENUM(listval) = entry->PriorityList[i];
  }
  return res;
}

status_t build_to_xml_timecontrol_DPLLRefPriority (
    val_value_t *parentval,
    struct timecontrolpb_DPLLRefPriority *entry) {
  status_t res = NO_ERR;
  val_value_t *childval = NULL;
  /* ---------------------------------------------------------------------------------------------------- */
  childval =  agt_make_object(
      parentval->obj,
    "List",
    &res);
  if (childval != NULL) {
    val_add_child(childval, parentval);
  } else if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  /* list */
  for (int i = 0; i < entry->List_Len; i++) {
  val_value_t *listval = NULL;
listval =  agt_make_object(
    childval->obj,
    "List_Entry",
    &res);
if (listval != NULL) {
  val_add_child(listval, childval);
} else if (res != NO_ERR) {
  return SET_ERROR(res);
}
res =  build_to_xml_timecontrol_DPLLRefPriorityEntry(
    listval,
    entry->List[i]);
if (res != NO_ERR) {
  return SET_ERROR(res);
}
  }
  return res;
}

status_t build_to_xml_timecontrol_DPLLRefPriorityEntry (
    val_value_t *parentval,
    struct timecontrolpb_DPLLRefPriorityEntry *entry) {
  status_t res = NO_ERR;
  val_value_t *childval = NULL;
  /* ---------------------------------------------------------------------------------------------------- */
  childval =  agt_make_object(
      parentval->obj,
    "Index",
    &res);
  if (childval != NULL) {
    val_add_child(childval, parentval);
  } else if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  /* enum */
  VAL_ENUM(childval) = entry->Index;
  /* ---------------------------------------------------------------------------------------------------- */
  childval =  agt_make_object(
      parentval->obj,
    "PrioritList",
    &res);
  if (childval != NULL) {
    val_add_child(childval, parentval);
  } else if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  /* list */
  for (int i = 0; i < entry->PrioritList_Len; i++) {
  val_value_t *listval = NULL;
listval =  agt_make_object(
    childval->obj,
    "PrioritList_Entry",
    &res);
if (listval != NULL) {
  val_add_child(listval, childval);
} else if (res != NO_ERR) {
  return SET_ERROR(res);
}
res =  build_to_xml_timecontrol_PriorityList(
    listval,
    entry->PrioritList[i]);
if (res != NO_ERR) {
  return SET_ERROR(res);
}
  }
  return res;
}

status_t build_to_xml_timecontrol_PriorityList (
    val_value_t *parentval,
    struct timecontrolpb_PriorityList *entry) {
  status_t res = NO_ERR;
  val_value_t *childval = NULL;
  /* ---------------------------------------------------------------------------------------------------- */
  childval =  agt_make_object(
      parentval->obj,
    "Priority",
    &res);
  if (childval != NULL) {
    val_add_child(childval, parentval);
  } else if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  /* enum */
  VAL_ENUM(childval) = entry->Priority;
  /* ---------------------------------------------------------------------------------------------------- */
  childval =  agt_make_object(
      parentval->obj,
    "InputCLK",
    &res);
  if (childval != NULL) {
    val_add_child(childval, parentval);
  } else if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  /* enum */
  VAL_ENUM(childval) = entry->InputCLK;
  return res;
}

status_t build_to_xml_timecontrol_SyncEInputClockSpeed (
    val_value_t *parentval,
    struct timecontrolpb_SyncEInputClockSpeed *entry) {
  status_t res = NO_ERR;
  val_value_t *childval = NULL;
  /* ---------------------------------------------------------------------------------------------------- */
  childval =  agt_make_object(
      parentval->obj,
    "List",
    &res);
  if (childval != NULL) {
    val_add_child(childval, parentval);
  } else if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  /* list */
  for (int i = 0; i < entry->List_Len; i++) {
  val_value_t *listval = NULL;
listval =  agt_make_object(
    childval->obj,
    "List_Entry",
    &res);
if (listval != NULL) {
  val_add_child(listval, childval);
} else if (res != NO_ERR) {
  return SET_ERROR(res);
}
res =  build_to_xml_timecontrol_SyncEInputClockSpeedEntry(
    listval,
    entry->List[i]);
if (res != NO_ERR) {
  return SET_ERROR(res);
}
  }
  return res;
}

status_t build_to_xml_timecontrol_SyncEInputClockSpeedEntry (
    val_value_t *parentval,
    struct timecontrolpb_SyncEInputClockSpeedEntry *entry) {
  status_t res = NO_ERR;
  val_value_t *childval = NULL;
  /* ---------------------------------------------------------------------------------------------------- */
  childval =  agt_make_object(
      parentval->obj,
    "InputCLK",
    &res);
  if (childval != NULL) {
    val_add_child(childval, parentval);
  } else if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  /* enum */
  VAL_ENUM(childval) = entry->InputCLK;
  /* ---------------------------------------------------------------------------------------------------- */
  childval =  agt_make_object(
      parentval->obj,
    "Speed",
    &res);
  if (childval != NULL) {
    val_add_child(childval, parentval);
  } else if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  /* enum */
  VAL_ENUM(childval) = entry->Speed;
  return res;
}

status_t build_to_xml_timecontrol_ToDSource (
    val_value_t *parentval,
    struct timecontrolpb_ToDSource *entry) {
  status_t res = NO_ERR;
  val_value_t *childval = NULL;
  /* ---------------------------------------------------------------------------------------------------- */
  childval =  agt_make_object(
      parentval->obj,
    "Enable",
    &res);
  if (childval != NULL) {
    val_add_child(childval, parentval);
  } else if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  /* bool */
  VAL_BOOL(childval) = entry->Enable;
  /* ---------------------------------------------------------------------------------------------------- */
  childval =  agt_make_object(
      parentval->obj,
    "Source",
    &res);
  if (childval != NULL) {
    val_add_child(childval, parentval);
  } else if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  /* enum */
  VAL_ENUM(childval) = entry->Source;
  return res;
}

status_t build_to_xml_timecontrol_DPLLToDManage (
    val_value_t *parentval,
    struct timecontrolpb_DPLLToDManage *entry) {
  status_t res = NO_ERR;
  val_value_t *childval = NULL;
  /* ---------------------------------------------------------------------------------------------------- */
  childval =  agt_make_object(
      parentval->obj,
    "List",
    &res);
  if (childval != NULL) {
    val_add_child(childval, parentval);
  } else if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  /* list */
  for (int i = 0; i < entry->List_Len; i++) {
  val_value_t *listval = NULL;
listval =  agt_make_object(
    childval->obj,
    "List_Entry",
    &res);
if (listval != NULL) {
  val_add_child(listval, childval);
} else if (res != NO_ERR) {
  return SET_ERROR(res);
}
res =  build_to_xml_timecontrol_DPLLToDManageEntry(
    listval,
    entry->List[i]);
if (res != NO_ERR) {
  return SET_ERROR(res);
}
  }
  return res;
}

status_t build_to_xml_timecontrol_DPLLToDManageEntry (
    val_value_t *parentval,
    struct timecontrolpb_DPLLToDManageEntry *entry) {
  status_t res = NO_ERR;
  val_value_t *childval = NULL;
  /* ---------------------------------------------------------------------------------------------------- */
  childval =  agt_make_object(
      parentval->obj,
    "Index",
    &res);
  if (childval != NULL) {
    val_add_child(childval, parentval);
  } else if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  /* enum */
  VAL_ENUM(childval) = entry->Index;
  return res;
}

status_t build_to_xml_timecontrol_ToDTime (
    val_value_t *parentval,
    struct timecontrolpb_ToDTime *entry) {
  status_t res = NO_ERR;
  val_value_t *childval = NULL;
  /* ---------------------------------------------------------------------------------------------------- */
  childval =  agt_make_object(
      parentval->obj,
    "List",
    &res);
  if (childval != NULL) {
    val_add_child(childval, parentval);
  } else if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  /* list */
  for (int i = 0; i < entry->List_Len; i++) {
  val_value_t *listval = NULL;
listval =  agt_make_object(
    childval->obj,
    "List_Entry",
    &res);
if (listval != NULL) {
  val_add_child(listval, childval);
} else if (res != NO_ERR) {
  return SET_ERROR(res);
}
res =  build_to_xml_timecontrol_ToDTimeEntry(
    listval,
    entry->List[i]);
if (res != NO_ERR) {
  return SET_ERROR(res);
}
  }
  return res;
}

status_t build_to_xml_timecontrol_ToDTimeEntry (
    val_value_t *parentval,
    struct timecontrolpb_ToDTimeEntry *entry) {
  status_t res = NO_ERR;
  val_value_t *childval = NULL;
  /* ---------------------------------------------------------------------------------------------------- */
  childval =  agt_make_object(
      parentval->obj,
    "Index",
    &res);
  if (childval != NULL) {
    val_add_child(childval, parentval);
  } else if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  /* enum */
  VAL_ENUM(childval) = entry->Index;
  /* ---------------------------------------------------------------------------------------------------- */
  childval =  agt_make_object(
      parentval->obj,
    "DateTime",
    &res);
  if (childval != NULL) {
    val_add_child(childval, parentval);
  } else if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  /* message */
   build_to_xml_timestamp_Timestamp(
      childval,
    entry->DateTime);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  return res;
}

status_t build_to_xml_timecontrol_DPLLFrequencyControl (
    val_value_t *parentval,
    struct timecontrolpb_DPLLFrequencyControl *entry) {
  status_t res = NO_ERR;
  val_value_t *childval = NULL;
  /* ---------------------------------------------------------------------------------------------------- */
  childval =  agt_make_object(
      parentval->obj,
    "List",
    &res);
  if (childval != NULL) {
    val_add_child(childval, parentval);
  } else if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  /* list */
  for (int i = 0; i < entry->List_Len; i++) {
  val_value_t *listval = NULL;
listval =  agt_make_object(
    childval->obj,
    "List_Entry",
    &res);
if (listval != NULL) {
  val_add_child(listval, childval);
} else if (res != NO_ERR) {
  return SET_ERROR(res);
}
res =  build_to_xml_timecontrol_DPLLFrequencyControlEntry(
    listval,
    entry->List[i]);
if (res != NO_ERR) {
  return SET_ERROR(res);
}
  }
  return res;
}

status_t build_to_xml_timecontrol_DPLLFrequencyControlEntry (
    val_value_t *parentval,
    struct timecontrolpb_DPLLFrequencyControlEntry *entry) {
  status_t res = NO_ERR;
  val_value_t *childval = NULL;
  /* ---------------------------------------------------------------------------------------------------- */
  childval =  agt_make_object(
      parentval->obj,
    "Index",
    &res);
  if (childval != NULL) {
    val_add_child(childval, parentval);
  } else if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  /* enum */
  VAL_ENUM(childval) = entry->Index;
  /* ---------------------------------------------------------------------------------------------------- */
  childval =  agt_make_object(
      parentval->obj,
    "FreqOffset",
    &res);
  if (childval != NULL) {
    val_add_child(childval, parentval);
  } else if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  /* int64 */
  VAL_LONG(childval) = entry->FreqOffset;
  return res;
}

status_t build_to_xml_timecontrol_DPLLPhaseControl (
    val_value_t *parentval,
    struct timecontrolpb_DPLLPhaseControl *entry) {
  status_t res = NO_ERR;
  val_value_t *childval = NULL;
  /* ---------------------------------------------------------------------------------------------------- */
  childval =  agt_make_object(
      parentval->obj,
    "List",
    &res);
  if (childval != NULL) {
    val_add_child(childval, parentval);
  } else if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  /* list */
  for (int i = 0; i < entry->List_Len; i++) {
  val_value_t *listval = NULL;
listval =  agt_make_object(
    childval->obj,
    "List_Entry",
    &res);
if (listval != NULL) {
  val_add_child(listval, childval);
} else if (res != NO_ERR) {
  return SET_ERROR(res);
}
res =  build_to_xml_timecontrol_DPLLPhaseControlEntry(
    listval,
    entry->List[i]);
if (res != NO_ERR) {
  return SET_ERROR(res);
}
  }
  return res;
}

status_t build_to_xml_timecontrol_DPLLPhaseControlEntry (
    val_value_t *parentval,
    struct timecontrolpb_DPLLPhaseControlEntry *entry) {
  status_t res = NO_ERR;
  val_value_t *childval = NULL;
  /* ---------------------------------------------------------------------------------------------------- */
  childval =  agt_make_object(
      parentval->obj,
    "Index",
    &res);
  if (childval != NULL) {
    val_add_child(childval, parentval);
  } else if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  /* enum */
  VAL_ENUM(childval) = entry->Index;
  /* ---------------------------------------------------------------------------------------------------- */
  childval =  agt_make_object(
      parentval->obj,
    "PhOffset",
    &res);
  if (childval != NULL) {
    val_add_child(childval, parentval);
  } else if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  /* int32 */
  VAL_INT(childval) = entry->PhOffset;
  return res;
}

status_t build_to_xml_timecontrol_DPLLPhaseSlopeLimit (
    val_value_t *parentval,
    struct timecontrolpb_DPLLPhaseSlopeLimit *entry) {
  status_t res = NO_ERR;
  val_value_t *childval = NULL;
  /* ---------------------------------------------------------------------------------------------------- */
  childval =  agt_make_object(
      parentval->obj,
    "List",
    &res);
  if (childval != NULL) {
    val_add_child(childval, parentval);
  } else if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  /* list */
  for (int i = 0; i < entry->List_Len; i++) {
  val_value_t *listval = NULL;
listval =  agt_make_object(
    childval->obj,
    "List_Entry",
    &res);
if (listval != NULL) {
  val_add_child(listval, childval);
} else if (res != NO_ERR) {
  return SET_ERROR(res);
}
res =  build_to_xml_timecontrol_DPLLPhaseSlopeLimitEntry(
    listval,
    entry->List[i]);
if (res != NO_ERR) {
  return SET_ERROR(res);
}
  }
  return res;
}

status_t build_to_xml_timecontrol_DPLLPhaseSlopeLimitEntry (
    val_value_t *parentval,
    struct timecontrolpb_DPLLPhaseSlopeLimitEntry *entry) {
  status_t res = NO_ERR;
  val_value_t *childval = NULL;
  /* ---------------------------------------------------------------------------------------------------- */
  childval =  agt_make_object(
      parentval->obj,
    "Index",
    &res);
  if (childval != NULL) {
    val_add_child(childval, parentval);
  } else if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  /* enum */
  VAL_ENUM(childval) = entry->Index;
  /* ---------------------------------------------------------------------------------------------------- */
  childval =  agt_make_object(
      parentval->obj,
    "Limit",
    &res);
  if (childval != NULL) {
    val_add_child(childval, parentval);
  } else if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  /* int32 */
  VAL_INT(childval) = entry->Limit;
  return res;
}

status_t build_to_xml_timecontrol_DPLLPhaseControlTimer (
    val_value_t *parentval,
    struct timecontrolpb_DPLLPhaseControlTimer *entry) {
  status_t res = NO_ERR;
  val_value_t *childval = NULL;
  /* ---------------------------------------------------------------------------------------------------- */
  childval =  agt_make_object(
      parentval->obj,
    "List",
    &res);
  if (childval != NULL) {
    val_add_child(childval, parentval);
  } else if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  /* list */
  for (int i = 0; i < entry->List_Len; i++) {
  val_value_t *listval = NULL;
listval =  agt_make_object(
    childval->obj,
    "List_Entry",
    &res);
if (listval != NULL) {
  val_add_child(listval, childval);
} else if (res != NO_ERR) {
  return SET_ERROR(res);
}
res =  build_to_xml_timecontrol_DPLLPhaseControlTimerEntry(
    listval,
    entry->List[i]);
if (res != NO_ERR) {
  return SET_ERROR(res);
}
  }
  return res;
}

status_t build_to_xml_timecontrol_DPLLPhaseControlTimerEntry (
    val_value_t *parentval,
    struct timecontrolpb_DPLLPhaseControlTimerEntry *entry) {
  status_t res = NO_ERR;
  val_value_t *childval = NULL;
  /* ---------------------------------------------------------------------------------------------------- */
  childval =  agt_make_object(
      parentval->obj,
    "Index",
    &res);
  if (childval != NULL) {
    val_add_child(childval, parentval);
  } else if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  /* enum */
  VAL_ENUM(childval) = entry->Index;
  /* ---------------------------------------------------------------------------------------------------- */
  childval =  agt_make_object(
      parentval->obj,
    "Timeout",
    &res);
  if (childval != NULL) {
    val_add_child(childval, parentval);
  } else if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  /* int32 */
  VAL_INT(childval) = entry->Timeout;
  return res;
}

