
#ifndef _H_intri_device
#define _H_intri_device
/* 
 * Copyright (c) 2008-2012, Andy Bierman, All Rights Reserved.
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *

*** Generated by yangdump 2.13-0

  Combined SIL header
  module intri-device
  revision 2022-05-24
  namespace http://intri.com.tw
  organization Intrising Inc.

 */

#include <libxml/xmlstring.h>

#include "dlq.h"
#include "ncxtypes.h"
#include "op.h"
#include "status.h"
#include "val.h"

#ifdef __cplusplus
extern "C" {
#endif

#define y_intri_device_M_intri_device (const xmlChar *)"intri-device"
#define y_intri_device_R_intri_device (const xmlChar *)"2022-05-24"

#define y_intri_device_N_IdentifyNo (const xmlChar *)"IdentifyNo"
#define y_intri_device_N_InterfaceIdentify_DeviceID (const xmlChar *)"InterfaceIdentify_DeviceID"
#define y_intri_device_N_InterfaceIdentify_LAGNo (const xmlChar *)"InterfaceIdentify_LAGNo"
#define y_intri_device_N_InterfaceIdentify_PortNo (const xmlChar *)"InterfaceIdentify_PortNo"
#define y_intri_device_N_InterfaceIdentify_Type (const xmlChar *)"InterfaceIdentify_Type"
#define y_intri_device_N_InterfaceIdentify_VlanID (const xmlChar *)"InterfaceIdentify_VlanID"
#define y_intri_device_N_List (const xmlChar *)"List"
#define y_intri_device_N_intri_device (const xmlChar *)"intri-device"
#define y_intri_device_N_lag_port_list (const xmlChar *)"lag-port-list"
#define y_intri_device_N_mac_addr (const xmlChar *)"mac-addr"
#define y_intri_device_N_poe_port_list (const xmlChar *)"poe-port-list"
#define y_intri_device_N_port_list (const xmlChar *)"port-list"

/* container /intri-device/mac-addr */
typedef struct y_intri_device_T_intri_device_mac_addr_ {
  xmlChar *mac_addr;
} y_intri_device_T_intri_device_mac_addr;

/* container /intri-device/port-list/List/IdentifyNo */
typedef struct y_intri_device_T_intri_device_port_list_List_IdentifyNo_ {
  xmlChar *InterfaceIdentify_Type;
  int32 InterfaceIdentify_DeviceID;
  int32 InterfaceIdentify_PortNo;
  int32 InterfaceIdentify_LAGNo;
  int32 InterfaceIdentify_VlanID;
} y_intri_device_T_intri_device_port_list_List_IdentifyNo;

/* list /intri-device/port-list/List */
typedef struct y_intri_device_T_intri_device_port_list_List_ {
  dlq_hdr_t qhdr;
  y_intri_device_T_intri_device_port_list_List_IdentifyNo IdentifyNo;
} y_intri_device_T_intri_device_port_list_List;

/* container /intri-device/port-list */
typedef struct y_intri_device_T_intri_device_port_list_ {
  dlq_hdr_t List;
} y_intri_device_T_intri_device_port_list;

/* container /intri-device/lag-port-list/List/IdentifyNo */
typedef struct y_intri_device_T_intri_device_lag_port_list_List_IdentifyNo_ {
  xmlChar *InterfaceIdentify_Type;
  int32 InterfaceIdentify_DeviceID;
  int32 InterfaceIdentify_PortNo;
  int32 InterfaceIdentify_LAGNo;
  int32 InterfaceIdentify_VlanID;
} y_intri_device_T_intri_device_lag_port_list_List_IdentifyNo;

/* list /intri-device/lag-port-list/List */
typedef struct y_intri_device_T_intri_device_lag_port_list_List_ {
  dlq_hdr_t qhdr;
  y_intri_device_T_intri_device_lag_port_list_List_IdentifyNo IdentifyNo;
} y_intri_device_T_intri_device_lag_port_list_List;

/* container /intri-device/lag-port-list */
typedef struct y_intri_device_T_intri_device_lag_port_list_ {
  dlq_hdr_t List;
} y_intri_device_T_intri_device_lag_port_list;

/* container /intri-device/poe-port-list/List/IdentifyNo */
typedef struct y_intri_device_T_intri_device_poe_port_list_List_IdentifyNo_ {
  xmlChar *InterfaceIdentify_Type;
  int32 InterfaceIdentify_DeviceID;
  int32 InterfaceIdentify_PortNo;
  int32 InterfaceIdentify_LAGNo;
  int32 InterfaceIdentify_VlanID;
} y_intri_device_T_intri_device_poe_port_list_List_IdentifyNo;

/* list /intri-device/poe-port-list/List */
typedef struct y_intri_device_T_intri_device_poe_port_list_List_ {
  dlq_hdr_t qhdr;
  y_intri_device_T_intri_device_poe_port_list_List_IdentifyNo IdentifyNo;
} y_intri_device_T_intri_device_poe_port_list_List;

/* container /intri-device/poe-port-list */
typedef struct y_intri_device_T_intri_device_poe_port_list_ {
  dlq_hdr_t List;
} y_intri_device_T_intri_device_poe_port_list;

/* container /intri-device */
typedef struct y_intri_device_T_intri_device_ {
  y_intri_device_T_intri_device_mac_addr mac_addr;
  y_intri_device_T_intri_device_port_list port_list;
  y_intri_device_T_intri_device_lag_port_list lag_port_list;
  y_intri_device_T_intri_device_poe_port_list poe_port_list;
} y_intri_device_T_intri_device;
/********************************************************************
* FUNCTION y_intri_device_init
* 
* initialize the intri-device server instrumentation library
* 
* INPUTS:
*    modname == requested module name
*    revision == requested version (NULL for any)
* 
* RETURNS:
*     error status
********************************************************************/
extern status_t y_intri_device_init (
  const xmlChar *modname,
  const xmlChar *revision);

/********************************************************************
* FUNCTION y_intri_device_init2
* 
* SIL init phase 2: non-config data structures
* Called after running config is loaded
* 
* RETURNS:
*     error status
********************************************************************/
extern status_t y_intri_device_init2 (void);

/********************************************************************
* FUNCTION y_intri_device_cleanup
*    cleanup the server instrumentation library
* 
********************************************************************/
extern void y_intri_device_cleanup (void);

#ifdef __cplusplus
} /* end extern 'C' */
#endif

#endif