../../target/ncx/not.o: not.c ../platform/procdefs.h dlq.h ncx.h \
  /usr/include/libxml2/libxml/xmlstring.h \
  /usr/include/libxml2/libxml/xmlversion.h \
  /usr/include/libxml2/libxml/xmlexports.h grp.h \
  /usr/include/libxml2/libxml/xmlregexp.h \
  /usr/include/libxml2/libxml/tree.h \
  /usr/include/libxml2/libxml/xmlstring.h \
  /usr/include/libxml2/libxml/xmlregexp.h \
  /usr/include/libxml2/libxml/xmlmemory.h \
  /usr/include/libxml2/libxml/threads.h \
  /usr/include/libxml2/libxml/globals.h \
  /usr/include/libxml2/libxml/parser.h /usr/include/libxml2/libxml/dict.h \
  /usr/include/libxml2/libxml/hash.h /usr/include/libxml2/libxml/valid.h \
  /usr/include/libxml2/libxml/xmlerror.h \
  /usr/include/libxml2/libxml/list.h \
  /usr/include/libxml2/libxml/xmlautomata.h \
  /usr/include/libxml2/libxml/entities.h \
  /usr/include/libxml2/libxml/encoding.h \
  /usr/include/libxml2/libxml/xmlIO.h /usr/include/libxml2/libxml/SAX.h \
  /usr/include/libxml2/libxml/xlink.h /usr/include/libxml2/libxml/SAX2.h \
  ncxconst.h ncxtypes.h xmlns.h status.h tk.h log.h not.h psd.h typ.h \
  rpc.h op.h ps.h val.h xml_msg.h xml_util.h \
  /usr/include/libxml2/libxml/xmlreader.h \
  /usr/include/libxml2/libxml/relaxng.h \
  /usr/include/libxml2/libxml/xmlschemas.h
