usr/bin/yangcli
usr/bin/yangdump
usr/bin/yangdiff
usr/share/doc/yuma/AUTHORS
usr/share/doc/yuma/Changelog
usr/share/doc/yuma/README
usr/share/doc/yuma/yuma-quickstart-guide.pdf
usr/share/doc/yuma/yuma-user-manual.pdf
usr/share/doc/yuma/yumatools-cs-license.pdf
usr/share/doc/yuma/yumatools-legal-notices.pdf
etc/yuma/yangcli-sample.conf
etc/yuma/yangdiff-sample.conf
etc/yuma/yangdump-sample.conf
usr/share/yuma/*





