usr/bin/yangcli
usr/bin/yangdump
usr/bin/yangdiff
usr/sbin/netconfd
usr/sbin/netconf-subsystem
usr/man/man1/yangcli.1.gz
usr/man/man1/yangdiff.1.gz
usr/man/man1/yangdump.1.gz
usr/man/man1/netconfd.1.gz
usr/man/man1/netconf-subsystem.1.gz
usr/share/doc/yuma/*
usr/share/yuma/modules/*
etc/yuma/yangcli-sample.conf
etc/yuma/yangdiff-sample.conf
etc/yuma/yangdump-sample.conf
etc/yuma/netconfd-sample.conf


