usr/sbin/netconfd
usr/sbin/netconf-subsystem
etc/yuma/netconfd-sample.conf
usr/man/man1/netconfd.1.gz
usr/man/man1/netconf-subsystem.1.gz
usr/share/yuma/modules/netconfcentral/netconfd.yang
usr/share/yuma/modules/netconfcentral/toaster.yang
usr/share/yuma/modules/netconfcentral/yuma-interfaces.yang
usr/share/yuma/modules/netconfcentral/yuma-mysession.yang
usr/share/yuma/modules/netconfcentral/yuma-nacm.yang
usr/share/yuma/modules/netconfcentral/yuma-netconf.yang
usr/share/yuma/modules/netconfcentral/yuma-proc.yang
usr/share/yuma/modules/netconfcentral/yuma-system.yang




