Document: yuma
Title: Debian yuma Manual
Author: <insert document author here>
Abstract: This manual describes what yuma is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/yuma/yuma.sgml.gz

Format: postscript
Files: /usr/share/doc/yuma/yuma.ps.gz

Format: text
Files: /usr/share/doc/yuma/yuma.text.gz

Format: HTML
Index: /usr/share/doc/yuma/html/index.html
Files: /usr/share/doc/yuma/html/*.html
