.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH yangdiff 1 "July 17, 2008" Linux "yangdiff 0.1.0"
.SH NAME
yangdiff \-report semantic and syntactic changes between two revisions of a YANG module

.SH SYNOPSIS
.B yangdiff [parameter=
.I value
.B ...]

.SH DESCRIPTION
.B yangdiff

yangdiff compares the semantics and syntax between 
two revisions of the same YANG module.  The 
conceptual data model is compared, not the 
individual files.  

For example, unless statement order is significant,
changing the order is not considered a change, and 
is not reported.  Reformatted test (whitespace changes)
are also not reported.

If a data type definition is changed in form,
but not content, then a 'modify type' message
will be generated, but no additional sub-fields
will be reported.

.SH USAGE
Parameters can be entered in any order, and have the form:

   \fB[start] name [separator [value]]\fP

where:

    \fBstart\fP == 0, 1, or 2 dashes (foo, -foo, --foo)

    \fBname\fP == parameter name
.nf

         Parameter name completion will be attempted 
         if a partial name is entered.

.fi
    \fBseparator\fP == whitespace or equals sign (foo=bar, foo bar)

    \fBvalue\fP == string value for the parameter.
.nf

         Strings with whitespace need to be double quoted 
         (--foo="some string")

.fi
Some examples of valid command line parameters:
.nf

   foo=3
   -foo=3
   --foo=3
   foo 3
   foo=fred
   --foo "fred flintstone"
.fi

Partial parameter names can be entered if they are unique.

.SH OPTIONS
.IP --\fBconfig\fP=filespec
The name of the configuration file to use.
Any parameter except this one can be set in the config file.
The default config file 
.I /etc/yangdiff.conf
will be not be checked if this parameter is present.
.IP --\fBold\fP=string
The older of the two revisions to compare.

If this parameter indicates a filename, then it
represents the YANG source module name 
to compare as the older of the two revisions.

If this parameter indicates a directory,
then it will be used to to search for a
file with the same name as identified by
the 'new' parameter.

If this string represents a filespec, 
ending with the \fB.yang\fP extension,
then only that file location will be checked.

If this string represents a module name, then
the module search path will be checked for
a file the \fB.yang\fP extension.

If this string begins with a '~' character,
then a username is expected to follow or
a directory separator character.  If it begins
with a '$' character, then an environment variable
name is expected to follow.
.nf

      ~/some/path ==> <my-home-dir>/some/path

      ~fred/some/path ==> <fred-home-dir>/some/path

      $workdir/some/path ==> <workdir-env-var>/some/path

.fi
This parameter must be present unless the 'help'
or 'version' parameters are used.
.IP --\fBnew\fP=string
If this parameter indicates a filename, then it
represents the YANG source module name 
to compare as the newer of the two revisions.

If this parameter indicates a directory
(and the 'old' parameter indicates a filename),
then it will be used to to search for a
file with the same name as the 'new' parameter.

If the 'old' parameter identifies a directory
as well (and the 'no-subdirs' parameter is present),
then the modules within the 'new' directory will be 
compared to files with the same name in the 'old' 
directory.  If the 'no-subdirs' parameter is not
present, then all sub-directories within the 'src'
directory will also be checked.

If this string begins with a '~' character,
then a username is expected to follow or
a directory separator character.  If it begins
with a '$' character, then an environment variable
name is expected to follow.
.nf

      ~/some/path ==> <my-home-dir>/some/path

      ~fred/some/path ==> <fred-home-dir>/some/path

      $workdir/some/path ==> <workdir-env-var>/some/path

.fi
This parameter must be present unless the 'help'
or 'version' parameters are used.
.IP --\fBdifftype\fP=string
The type of comparison output requested.
Allowed values are 'terse', 'normal', and 'revision'.

The basic format is:
.nf

  [add/delete/modify] field-name [field-value]

.fi
The 'terse' option will include the names
of the top-level fields that are different.
.nf

     A foo  -->  Added foo in new revision
     D foo  -->  Deleted foo in new revision
     M foo  -->  Modified foo in new revision (value too long)
     M foo from '0' to '1'  -->  Modified foo in new revision

.fi
The 'normal' option will also include any changes
for any nested fields or objects.  This is the default
option.

The 'revision' option will generate the differences report
in YANG revision-stmt format.  For example:
.nf

       revision <todays-date> {
         description 
          \"
            - Added import baxtypes
            - Changed contact from 'tech@acme.com' to 'support@acme.com'
             - Modified container myobjects
               - Added list first-list\";
       }

.fi
If missing, the the default value 'normal' is used.
.IP --\fBoutput\fP=filespec
Output directory or file name to use. 
The default is STDOUT if none is specified.

If this parameter represents an existing directory,
then the default comparison output file (yangdiff.log)
will be generated in the specified directory.

If this parameter represents a file name,
then all comparison output will be directed
to the specified file.  If the file already exists,
it will be overwritten.

If this string begins with a '~' character,
then a username is expected to follow or
a directory separator character.  If it begins
with a '$' character, then an environment variable
name is expected to follow.
.nf

      ~/some/path ==> <my-home-dir>/some/path

      ~fred/some/path ==> <fred-home-dir>/some/path

      $workdir/some/path ==> <workdir-env-var>/some/path

.fi
.IP --\fBhelp\fP
Print yangdiff help file and exit.
.fi
.IP --\fBindent\fP=number
Number of spaces to indent (0..9) in formatted output.
The default is 3 spaces.
.IP --\fBlog\fP=filespec
Filespec for the log file to use instead of STDOUT.
If this string begins with a '~' character,
then a username is expected to follow or
a directory separator character.  If it begins
with a '$' character, then an environment variable
name is expected to follow.
.IP --\fBlog-append\fP
If present, the log will be appended not over-written.
If not, the log will be over-written.
Only meaningful if the \fBlog\fP parameter is
also present.
.IP --\fBlog-level\fP=enum
Sets the debug logging level for the program.
.IP --\fBmodpath\fP=list
Directory search path for YANG and NCX modules.
.IP --\fBno-subdirs\fP
If present, the file search paths for modules, scripts, and data
files will not include sub-directories if they exist in the
specified path.
      
If missing, then these file search paths will include
sub-directories, if present.  Any directory name beginning
with a dot (\fB.\fP) character, or named \fBCVS\fP, will be ignored.
.IP --\fBversion\fP
Print yangdiff version string and exit.

.SH INPUT FILES

To compare one module, use the 'old' and 'new'
parameters to specify YANG module files,
each with a filespec string ending with the '.yang'
file extension.  The filespecs must represent
different files.  If the 'old' parameter represents
a directory, then this directory will be searched
for the 'new' filename.

To compare all the modules in a subtree, use
the 'old' and 'new' parameters to specify a directory
to be searched for YANG modules to be processed.
In this mode, each new module is compared to
a corresponding file within the 'old' subtree.
Also, dependency and include files
will be kept separate, for each subtree.
           
Unless the 'help' or 'version' parameters is entered, 
the 'old' and 'new' parameters must be present.

.SH SEARCH PATH
When a module name is entered as input, or when a
module or submodule name is specified in an import or include
statement within the file, the following search algorithm
is used to find the file:
.nf    

  1) if the parameter for the file that generated the
     search request represents a subtree, search that
     subtree first.
  2) file is in the current directory
  3) YANG_MODPATH environment var (or set by modpath parameter)
  4) $HOME/modules directory
  5) $YANG_HOME/modules directory
  6) $YANG_INSTALL/modules directory OR
     default install module location, '/usr/share/yang/modules'

.fi
By default, the entire directory tree for all locations
(except step 1) will be searched, not just the specified
directory.  The \fBno-subdirs\fP parameter can be used to
prevent sub-directories from being searched.
    
Any directory name beginning with a dot character (\fB.\fP)
will be skipped.  Also, any directory named \fBCVS\fP will
be skipped in directory searches.

.SH OUTPUT MODES
By default, any translation output will be sent to \fBSTDOUT\fP.
    
The \fBoutput\fP parameter can be used to specify the 
full filespec of the output file,  or a
complete directory specification to be combined
with the default filename (yangdiff.log).

.SH ERROR LOGGING
By default, warnings and errors are sent to STDOUT.
    
A log file can be specified instead with the \fBlog\fP' parameter.

Existing log files can be reused with the 'logappend'
parameter, otherwise log files are overwritten.
    
The logging level can be controlled with the \fBlog-level\fP
parameter.

The default log level is 'info'.  The
log-levels are additive:
.nf

     off:    suppress all errors (not recommended!)
             A program return code of '1' indicates some error.
     error:  print errors
     warn:   print warnings
     info:   print generally interesting trace info
     debug:  print general debugging trace info
     debug2: print verbose debugging trace info

.fi

.SH ENVIRONMENT
The following optional environment variables can be used
to control module search behavior:

.IP \fBHOME\fP
The user's home directory  (e.g., /home/andy)
.IP \fBYANG_HOME\fP
The root of the user's YANG work directory
(e.g., /home/andy/swdev/netconf)
.IP \fBYANG_INSTALL\fP
The root of the directory that yangdiff
is installed on this system (default is, /usr/share/yang)
.IP \fBYANG_MODPATH\fP
Colon-separated list of directories to
search for modules and submodules.

(e.g.: './workdir/modules:/home/andy/test-modules')

The \fBmodpath\fP parameter will override this
environment variable, if both are present.

.SH CONFIGURATION FILES
.IP \fByangdiff.conf\fP
YANG config file
The default is: \fB/etc/yangdiff.conf\fP
    
An ASCII configuration file format is supported to
store command line parameters. 

The \fBconfig\fP parameter
is used to specify a specific config file, otherwise
the default config file will be checked.
.nf    

   - A hash mark until EOLN is treated as a comment
   - All text is case-sensitive
   - Whitespace within a line is not significant
   - Whitespace to end a line is significant/
     Unless the line starts a multi-line string,
     an escaped EOLN (backslash EOLN) is needed
     to enter a leaf on multiple lines.
   - For parameters that define lists, the key components
     are listed just after the parameter name, without
     any name,  e.g.,
    
            interface eth0 {
              # name = eth0 is not listed inside the braces
              ifMtu 1500
              ifName mySystem
            }

.fi    
A config file can contain any number of parameter
sets for different programs. 

.SH FILES
The following data files must be present in the module
search path in order for this program to function:
    
  * \fByangdiff.ncx\fP
    default: /usr/share/yang/modules/apps/yangdiff.ncx
    
  * \fBncxtypes.ncx\fP
    default: /usr/share/yang/modules/base/ncxtypes.ncx

.SH BUGS
  - keyref Xpath expressions are not validated
  - must-stmt Xpath expressions are not validated
  - comments are not preserved in HTML or YANG output
  - statement order in YANG and HTML output is not completely
    preserved beyond the very top level.  Local typedefs, 
    local groupings, and child node objects are defined in 
    separate namespaces, so nested relative order is not maintained 

.SH DIAGNOSTICS
Internal diagnostics may generate the following
type of message if any bugs are detected at runtime:
  
    [E0]
         filename.c:linenum error-number (error-msg)
    
.SH AUTHOR
Andy Bierman, <andy at netconfcentral dot com>

.SH SEE ALSO
.BR yangdump (1)
.BR pyang (1)
.BR smidump (1)
