// Code generated by protoc-gen-yang(*.c) DO NOT EDIT.

/*****************************************************************************************************
 * Copyright (C) 2017-2022 by Intrising
 *  - ian0113@intrising.com.tw
 * 
 * Generated by protoc-gen-yang@gen-yang
 * 
 *****************************************************************************************************/

#include <libxml/xmlstring.h>
#include "agt.h"
#include "agt_cb.h"
#include "agt_rpc.h"
#include "agt_timer.h"
#include "agt_util.h"
#include "dlq.h"
#include "ncx.h"
#include "ncx_feature.h"
#include "ncxmod.h"
#include "ncxtypes.h"
#include "procdefs.h"
#include "rpc.h"
#include "ses.h"
#include "status.h"
#include "val.h"
#include "val_util.h"
#include "xml_util.h"

#include "intri-gvrp-trans.h"
#include "../../../../../../../../.libintrishare/libintrishare.h"

#include "../../../../../github.com/Intrising/intri-type/common/intri-common-trans.h"
#include "../../../../../github.com/Intrising/intri-type/device/intri-device-trans.h"
#include "../../../../../github.com/golang/protobuf/ptypes/empty/intri-empty-trans.h"

status_t build_to_xml_gvrp_PortConfigEntry(
    val_value_t *parentval,
    struct gvrppb_PortConfigEntry *entry) {
  status_t res = NO_ERR;
  val_value_t *childval = NULL;
  const xmlChar *enum_str = EMPTY_STRING;
  if (entry == NULL) {
    return res;
  }
  childval = agt_make_object(
      parentval->obj,
      "IdentifyNo",
      &res);
  if (childval != NULL) {
    val_add_child(childval, parentval);
  } else if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  /* message */
  res = build_to_xml_device_InterfaceIdentify(
      childval,
      entry->IdentifyNo);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  childval = agt_make_object(
      parentval->obj,
      "IsEnabled",
      &res);
  if (childval != NULL) {
    val_add_child(childval, parentval);
  } else if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  /* bool */
  VAL_BOOL(childval) = entry->IsEnabled;
  childval = agt_make_object(
      parentval->obj,
      "Mode",
      &res);
  if (childval != NULL) {
    val_add_child(childval, parentval);
  } else if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  /* enum */
  switch (entry->Mode) {
    case gvrppb_PortModeTypeOptions_PORT_MODE_NORMAL:
      enum_str = "PORT_MODE_NORMAL";
      break;
    case gvrppb_PortModeTypeOptions_PORT_MODE_FIXED:
      enum_str = "PORT_MODE_FIXED";
      break;
    case gvrppb_PortModeTypeOptions_PORT_MODE_FORBIDDEN:
      enum_str = "PORT_MODE_FORBIDDEN";
      break;
  }
  VAL_ENUM_NAME(childval) = enum_str;
  childval = agt_make_object(
      parentval->obj,
      "LeaveAllTimerInterval",
      &res);
  if (childval != NULL) {
    val_add_child(childval, parentval);
  } else if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  /* int32 */
  VAL_INT(childval) = entry->LeaveAllTimerInterval;
  childval = agt_make_object(
      parentval->obj,
      "JoinTimerInterval",
      &res);
  if (childval != NULL) {
    val_add_child(childval, parentval);
  } else if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  /* int32 */
  VAL_INT(childval) = entry->JoinTimerInterval;
  childval = agt_make_object(
      parentval->obj,
      "HoldTimerInterval",
      &res);
  if (childval != NULL) {
    val_add_child(childval, parentval);
  } else if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  /* int32 */
  VAL_INT(childval) = entry->HoldTimerInterval;
  childval = agt_make_object(
      parentval->obj,
      "LeaveTimerInterval",
      &res);
  if (childval != NULL) {
    val_add_child(childval, parentval);
  } else if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  /* int32 */
  VAL_INT(childval) = entry->LeaveTimerInterval;
  return res;
}
status_t build_to_xml_gvrp_PortsConfig(
    val_value_t *parentval,
    struct gvrppb_PortsConfig *entry) {
  status_t res = NO_ERR;
  val_value_t *childval = NULL;
  const xmlChar *enum_str = EMPTY_STRING;
  if (entry == NULL) {
    return res;
  }
  childval = agt_make_object(
      parentval->obj,
      "List",
      &res);
  if (childval != NULL) {
    val_add_child(childval, parentval);
  } else if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  for (int i = 0; i < entry->List_Len; i++) {
    val_value_t *listval = NULL;
    listval = agt_make_object(
        childval->obj,
        "List_Entry",
        &res);
    if (listval != NULL) {
      val_add_child(listval, childval);
    } else if (res != NO_ERR) {
      return SET_ERROR(res);
    }
    /* message */
    res = build_to_xml_gvrp_PortConfigEntry(
        listval,
        entry->List[i]);
    if (res != NO_ERR) {
      return SET_ERROR(res);
    }
  }
  return res;
}
status_t build_to_xml_gvrp_Config(
    val_value_t *parentval,
    struct gvrppb_Config *entry) {
  status_t res = NO_ERR;
  val_value_t *childval = NULL;
  const xmlChar *enum_str = EMPTY_STRING;
  if (entry == NULL) {
    return res;
  }
  childval = agt_make_object(
      parentval->obj,
      "IsEnabled",
      &res);
  if (childval != NULL) {
    val_add_child(childval, parentval);
  } else if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  /* bool */
  VAL_BOOL(childval) = entry->IsEnabled;
  childval = agt_make_object(
      parentval->obj,
      "PortsConfig",
      &res);
  if (childval != NULL) {
    val_add_child(childval, parentval);
  } else if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  /* message */
  res = build_to_xml_gvrp_PortsConfig(
      childval,
      entry->PortsConfig);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }
  return res;
}

status_t build_to_priv_gvrp_PortConfigEntry(
    val_value_t *parentval,
    struct gvrppb_PortConfigEntry *entry) {
  status_t res = NO_ERR;
  val_value_t *childval = NULL;
  childval = val_first_child_name(
      parentval,
      "IdentifyNo");
  if (childval != NULL && childval->res == NO_ERR) {
    /* message */
    entry->IdentifyNo = malloc(sizeof(*(entry->IdentifyNo)));
    res = build_to_priv_device_InterfaceIdentify(
        childval,
        entry->IdentifyNo);
    if (res != NO_ERR) {
      return SET_ERROR(res);
    }
  }
  childval = val_first_child_name(
      parentval,
      "IsEnabled");
  if (childval != NULL && childval->res == NO_ERR) {
    /* bool */
    entry->IsEnabled = VAL_BOOL(childval);
  }
  childval = val_first_child_name(
      parentval,
      "Mode");
  if (childval != NULL && childval->res == NO_ERR) {
    /* enum */
    entry->Mode = VAL_ENUM(childval);
  }
  childval = val_first_child_name(
      parentval,
      "LeaveAllTimerInterval");
  if (childval != NULL && childval->res == NO_ERR) {
    /* int32 */
    entry->LeaveAllTimerInterval = VAL_INT(childval);
  }
  childval = val_first_child_name(
      parentval,
      "JoinTimerInterval");
  if (childval != NULL && childval->res == NO_ERR) {
    /* int32 */
    entry->JoinTimerInterval = VAL_INT(childval);
  }
  childval = val_first_child_name(
      parentval,
      "HoldTimerInterval");
  if (childval != NULL && childval->res == NO_ERR) {
    /* int32 */
    entry->HoldTimerInterval = VAL_INT(childval);
  }
  childval = val_first_child_name(
      parentval,
      "LeaveTimerInterval");
  if (childval != NULL && childval->res == NO_ERR) {
    /* int32 */
    entry->LeaveTimerInterval = VAL_INT(childval);
  }
  return res;
}
status_t build_to_priv_gvrp_PortsConfig(
    val_value_t *parentval,
    struct gvrppb_PortsConfig *entry) {
  status_t res = NO_ERR;
  val_value_t *childval = NULL;
  childval = val_first_child_name(
      parentval,
      "List");
  entry->List_Len = 0;
  entry->List = malloc(sizeof(*entry->List));
  if (childval != NULL && childval->res == NO_ERR) {
    entry->List_Len = dlq_count(&childval->v.childQ);
    entry->List = malloc((entry->List_Len + 1) * sizeof(*entry->List));
    unsigned int cnt = 0;
    val_value_t *listval = NULL;
    for (listval = (val_value_t *)dlq_firstEntry(&childval->v.childQ);
         listval != NULL;
         listval = (val_value_t *)dlq_nextEntry(listval)) {
      /* message */
      entry->List[cnt] = malloc(sizeof(*(entry->List[cnt])));
      res = build_to_priv_gvrp_PortConfigEntry(
          listval,
          entry->List[cnt]);
      if (res != NO_ERR) {
        return SET_ERROR(res);
      }
      cnt++;
    }
  }
  return res;
}
status_t build_to_priv_gvrp_Config(
    val_value_t *parentval,
    struct gvrppb_Config *entry) {
  status_t res = NO_ERR;
  val_value_t *childval = NULL;
  childval = val_first_child_name(
      parentval,
      "IsEnabled");
  if (childval != NULL && childval->res == NO_ERR) {
    /* bool */
    entry->IsEnabled = VAL_BOOL(childval);
  }
  childval = val_first_child_name(
      parentval,
      "PortsConfig");
  if (childval != NULL && childval->res == NO_ERR) {
    /* message */
    entry->PortsConfig = malloc(sizeof(*(entry->PortsConfig)));
    res = build_to_priv_gvrp_PortsConfig(
        childval,
        entry->PortsConfig);
    if (res != NO_ERR) {
      return SET_ERROR(res);
    }
  }
  return res;
}
