
/*****************************************************************************************************
 * Copyright (C) 2017-2022 by Intrising
 *  - ian0113@intrising.com.tw
 * 
 * Generated by protoc-gen-yang@gen-yang
 * 
 *****************************************************************************************************/

#include <libxml/xmlstring.h>
#include "agt.h"
#include "agt_cb.h"
#include "agt_rpc.h"
#include "agt_timer.h"
#include "agt_util.h"
#include "dlq.h"
#include "ncx.h"
#include "ncx_feature.h"
#include "ncxmod.h"
#include "ncxtypes.h"
#include "procdefs.h"
#include "rpc.h"
#include "ses.h"
#include "status.h"
#include "val.h"
#include "val_util.h"
#include "xml_util.h"

#include "intri-stp@2022-06-24.h"
#include "../../../../../../../../.libintrishare/libintrishare.h"
#include "../../../../../../genc-trans/github.com/Intrising/intri-type/core/stp/intri-stp-trans.h"
#include "../../../../../../genc-trans/github.com/Intrising/intri-type/device/intri-device-trans.h"
#include "../../../../../../genc-trans/github.com/golang/protobuf/ptypes/empty/intri-empty-trans.h"

static ncx_module_t *intri_stp_mod;
static obj_template_t *intri_stp_GetConfig_obj;
static obj_template_t *intri_stp_SetConfig_obj;
static obj_template_t *intri_stp_SetCistConfig_obj;
static obj_template_t *intri_stp_SetMstiConfig_obj;
static obj_template_t *intri_stp_GetCistStatus_obj;
static obj_template_t *intri_stp_GetMstiStatus_obj;
static obj_template_t *intri_stp_RunReconfigPortState_obj;
static obj_template_t *intri_stp_GetBridgeConfigMode_obj;
static obj_template_t *intri_stp_SetBridgeConfigMode_obj;
static obj_template_t *intri_stp_GetBridgeConfigPriority_obj;
static obj_template_t *intri_stp_SetBridgeConfigPriority_obj;
static obj_template_t *intri_stp_GetBridgeConfigHelloTime_obj;
static obj_template_t *intri_stp_SetBridgeConfigHelloTime_obj;
static obj_template_t *intri_stp_GetBridgeConfigMaxAge_obj;
static obj_template_t *intri_stp_SetBridgeConfigMaxAge_obj;
static obj_template_t *intri_stp_GetBridgeConfigForwardDelay_obj;
static obj_template_t *intri_stp_SetBridgeConfigForwardDelay_obj;
static obj_template_t *intri_stp_GetBridgeConfigTxHoldCount_obj;
static obj_template_t *intri_stp_SetBridgeConfigTxHoldCount_obj;
static obj_template_t *intri_stp_GetBridgeConfigMSTPRegionName_obj;
static obj_template_t *intri_stp_SetBridgeConfigMSTPRegionName_obj;
static obj_template_t *intri_stp_GetBridgeConfigMSTPRevisionLevel_obj;
static obj_template_t *intri_stp_SetBridgeConfigMSTPRevisionLevel_obj;
static obj_template_t *intri_stp_GetBridgeConfigMSTPMaxHops_obj;
static obj_template_t *intri_stp_SetBridgeConfigMSTPMaxHops_obj;
static obj_template_t *intri_stp_GetPortConfigEnabled_obj;
static obj_template_t *intri_stp_SetPortConfigEnabled_obj;
static obj_template_t *intri_stp_GetPortConfigPriority_obj;
static obj_template_t *intri_stp_SetPortConfigPriority_obj;
static obj_template_t *intri_stp_GetPortConfigAdminP2PPort_obj;
static obj_template_t *intri_stp_SetPortConfigAdminP2PPort_obj;
static obj_template_t *intri_stp_GetPortConfigAdminEdgePort_obj;
static obj_template_t *intri_stp_SetPortConfigAdminEdgePort_obj;
static obj_template_t *intri_stp_GetPortConfigAdminPathCost_obj;
static obj_template_t *intri_stp_SetPortConfigAdminPathCost_obj;
static obj_template_t *intri_stp_GetPortConfigMSTPDefaultPriority_obj;
static obj_template_t *intri_stp_SetPortConfigMSTPDefaultPriority_obj;
static obj_template_t *intri_stp_GetPortConfigMSTPPortPriority_obj;
static obj_template_t *intri_stp_SetPortConfigMSTPPortPriority_obj;
static obj_template_t *intri_stp_GetPortConfigMSTPDefaultAdminPathCost_obj;
static obj_template_t *intri_stp_SetPortConfigMSTPDefaultAdminPathCost_obj;
static obj_template_t *intri_stp_GetPortConfigMSTPPortAdminPathCost_obj;
static obj_template_t *intri_stp_SetPortConfigMSTPPortAdminPathCost_obj;
static obj_template_t *intri_stp_GetPortConfigBPDUGuard_obj;
static obj_template_t *intri_stp_SetPortConfigBPDUGuard_obj;
static obj_template_t *intri_stp_GetPortConfigBPDUReceiveOnly_obj;
static obj_template_t *intri_stp_SetPortConfigBPDUReceiveOnly_obj;
static obj_template_t *intri_stp_GetPortConfigRestrictTcn_obj;
static obj_template_t *intri_stp_SetPortConfigRestrictTcn_obj;
static obj_template_t *intri_stp_GetPortConfigRestrictRoot_obj;
static obj_template_t *intri_stp_SetPortConfigRestrictRoot_obj;
static obj_template_t *intri_stp_GetMSTPGroup_obj;
static obj_template_t *intri_stp_SetMSTPGroup_obj;
static obj_template_t *intri_stp_DeleteMSTPGroup_obj;

static status_t intri_stp_MSTP_GetConfig_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct emptypb_Empty in;
  struct stppb_MSTPConfig out;
  stp_MSTP_GetConfig(&in, &out);
  val_value_t *resval = val_new_value();
  res =  build_to_xml_stp_MSTPConfig(
      resval,
    &out);
  return res;
}

static status_t intri_stp_MSTP_SetConfig_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct stppb_MSTPConfig in;
  struct emptypb_Empty out;
  stp_MSTP_SetConfig(&in, &out);
  val_value_t *resval = val_new_value();
  return res;
}

static status_t intri_stp_MSTP_SetCistConfig_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct stppb_CISTEntry in;
  struct emptypb_Empty out;
  stp_MSTP_SetCistConfig(&in, &out);
  val_value_t *resval = val_new_value();
  return res;
}

static status_t intri_stp_MSTP_SetMstiConfig_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct stppb_MSTIList in;
  struct emptypb_Empty out;
  stp_MSTP_SetMstiConfig(&in, &out);
  val_value_t *resval = val_new_value();
  return res;
}

static status_t intri_stp_MSTP_GetCistStatus_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct emptypb_Empty in;
  struct stppb_CISTStatus out;
  stp_MSTP_GetCistStatus(&in, &out);
  val_value_t *resval = val_new_value();
  res =  build_to_xml_stp_CISTStatus(
      resval,
    &out);
  return res;
}

static status_t intri_stp_MSTP_GetMstiStatus_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct emptypb_Empty in;
  struct stppb_MSTIStatus out;
  stp_MSTP_GetMstiStatus(&in, &out);
  val_value_t *resval = val_new_value();
  res =  build_to_xml_stp_MSTIStatus(
      resval,
    &out);
  return res;
}

static status_t intri_stp_MSTP_RunReconfigPortState_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct emptypb_Empty in;
  struct emptypb_Empty out;
  stp_MSTP_RunReconfigPortState(&in, &out);
  val_value_t *resval = val_new_value();
  return res;
}

static status_t intri_stp_MSTP_GetBridgeConfigMode_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct emptypb_Empty in;
  struct stppb_BridgeConfigMode out;
  stp_MSTP_GetBridgeConfigMode(&in, &out);
  val_value_t *resval = val_new_value();
  res =  build_to_xml_stp_BridgeConfigMode(
      resval,
    &out);
  return res;
}

static status_t intri_stp_MSTP_SetBridgeConfigMode_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct stppb_BridgeConfigMode in;
  struct emptypb_Empty out;
  stp_MSTP_SetBridgeConfigMode(&in, &out);
  val_value_t *resval = val_new_value();
  return res;
}

static status_t intri_stp_MSTP_GetBridgeConfigPriority_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct emptypb_Empty in;
  struct stppb_BridgeConfigPriority out;
  stp_MSTP_GetBridgeConfigPriority(&in, &out);
  val_value_t *resval = val_new_value();
  res =  build_to_xml_stp_BridgeConfigPriority(
      resval,
    &out);
  return res;
}

static status_t intri_stp_MSTP_SetBridgeConfigPriority_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct stppb_BridgeConfigPriority in;
  struct emptypb_Empty out;
  stp_MSTP_SetBridgeConfigPriority(&in, &out);
  val_value_t *resval = val_new_value();
  return res;
}

static status_t intri_stp_MSTP_GetBridgeConfigHelloTime_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct emptypb_Empty in;
  struct stppb_BridgeConfigHelloTime out;
  stp_MSTP_GetBridgeConfigHelloTime(&in, &out);
  val_value_t *resval = val_new_value();
  res =  build_to_xml_stp_BridgeConfigHelloTime(
      resval,
    &out);
  return res;
}

static status_t intri_stp_MSTP_SetBridgeConfigHelloTime_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct stppb_BridgeConfigHelloTime in;
  struct emptypb_Empty out;
  stp_MSTP_SetBridgeConfigHelloTime(&in, &out);
  val_value_t *resval = val_new_value();
  return res;
}

static status_t intri_stp_MSTP_GetBridgeConfigMaxAge_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct emptypb_Empty in;
  struct stppb_BridgeConfigMaxAge out;
  stp_MSTP_GetBridgeConfigMaxAge(&in, &out);
  val_value_t *resval = val_new_value();
  res =  build_to_xml_stp_BridgeConfigMaxAge(
      resval,
    &out);
  return res;
}

static status_t intri_stp_MSTP_SetBridgeConfigMaxAge_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct stppb_BridgeConfigMaxAge in;
  struct emptypb_Empty out;
  stp_MSTP_SetBridgeConfigMaxAge(&in, &out);
  val_value_t *resval = val_new_value();
  return res;
}

static status_t intri_stp_MSTP_GetBridgeConfigForwardDelay_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct emptypb_Empty in;
  struct stppb_BridgeConfigForwardDelay out;
  stp_MSTP_GetBridgeConfigForwardDelay(&in, &out);
  val_value_t *resval = val_new_value();
  res =  build_to_xml_stp_BridgeConfigForwardDelay(
      resval,
    &out);
  return res;
}

static status_t intri_stp_MSTP_SetBridgeConfigForwardDelay_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct stppb_BridgeConfigForwardDelay in;
  struct emptypb_Empty out;
  stp_MSTP_SetBridgeConfigForwardDelay(&in, &out);
  val_value_t *resval = val_new_value();
  return res;
}

static status_t intri_stp_MSTP_GetBridgeConfigTxHoldCount_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct emptypb_Empty in;
  struct stppb_BridgeConfigTxHoldCount out;
  stp_MSTP_GetBridgeConfigTxHoldCount(&in, &out);
  val_value_t *resval = val_new_value();
  res =  build_to_xml_stp_BridgeConfigTxHoldCount(
      resval,
    &out);
  return res;
}

static status_t intri_stp_MSTP_SetBridgeConfigTxHoldCount_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct stppb_BridgeConfigTxHoldCount in;
  struct emptypb_Empty out;
  stp_MSTP_SetBridgeConfigTxHoldCount(&in, &out);
  val_value_t *resval = val_new_value();
  return res;
}

static status_t intri_stp_MSTP_GetBridgeConfigMSTPRegionName_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct emptypb_Empty in;
  struct stppb_BridgeConfigMSTPRegionName out;
  stp_MSTP_GetBridgeConfigMSTPRegionName(&in, &out);
  val_value_t *resval = val_new_value();
  res =  build_to_xml_stp_BridgeConfigMSTPRegionName(
      resval,
    &out);
  return res;
}

static status_t intri_stp_MSTP_SetBridgeConfigMSTPRegionName_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct stppb_BridgeConfigMSTPRegionName in;
  struct emptypb_Empty out;
  stp_MSTP_SetBridgeConfigMSTPRegionName(&in, &out);
  val_value_t *resval = val_new_value();
  return res;
}

static status_t intri_stp_MSTP_GetBridgeConfigMSTPRevisionLevel_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct emptypb_Empty in;
  struct stppb_BridgeConfigMSTPRevisionLevel out;
  stp_MSTP_GetBridgeConfigMSTPRevisionLevel(&in, &out);
  val_value_t *resval = val_new_value();
  res =  build_to_xml_stp_BridgeConfigMSTPRevisionLevel(
      resval,
    &out);
  return res;
}

static status_t intri_stp_MSTP_SetBridgeConfigMSTPRevisionLevel_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct stppb_BridgeConfigMSTPRevisionLevel in;
  struct emptypb_Empty out;
  stp_MSTP_SetBridgeConfigMSTPRevisionLevel(&in, &out);
  val_value_t *resval = val_new_value();
  return res;
}

static status_t intri_stp_MSTP_GetBridgeConfigMSTPMaxHops_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct emptypb_Empty in;
  struct stppb_BridgeConfigMSTPMaxHops out;
  stp_MSTP_GetBridgeConfigMSTPMaxHops(&in, &out);
  val_value_t *resval = val_new_value();
  res =  build_to_xml_stp_BridgeConfigMSTPMaxHops(
      resval,
    &out);
  return res;
}

static status_t intri_stp_MSTP_SetBridgeConfigMSTPMaxHops_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct stppb_BridgeConfigMSTPMaxHops in;
  struct emptypb_Empty out;
  stp_MSTP_SetBridgeConfigMSTPMaxHops(&in, &out);
  val_value_t *resval = val_new_value();
  return res;
}

static status_t intri_stp_MSTP_GetPortConfigEnabled_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct devicepb_PortList in;
  struct stppb_STPPortConfigEnabled out;
  stp_MSTP_GetPortConfigEnabled(&in, &out);
  val_value_t *resval = val_new_value();
  res =  build_to_xml_stp_STPPortConfigEnabled(
      resval,
    &out);
  return res;
}

static status_t intri_stp_MSTP_SetPortConfigEnabled_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct stppb_STPPortConfigEnabled in;
  struct emptypb_Empty out;
  stp_MSTP_SetPortConfigEnabled(&in, &out);
  val_value_t *resval = val_new_value();
  return res;
}

static status_t intri_stp_MSTP_GetPortConfigPriority_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct devicepb_PortList in;
  struct stppb_STPPortConfigPriority out;
  stp_MSTP_GetPortConfigPriority(&in, &out);
  val_value_t *resval = val_new_value();
  res =  build_to_xml_stp_STPPortConfigPriority(
      resval,
    &out);
  return res;
}

static status_t intri_stp_MSTP_SetPortConfigPriority_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct stppb_STPPortConfigPriority in;
  struct emptypb_Empty out;
  stp_MSTP_SetPortConfigPriority(&in, &out);
  val_value_t *resval = val_new_value();
  return res;
}

static status_t intri_stp_MSTP_GetPortConfigAdminP2PPort_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct devicepb_PortList in;
  struct stppb_STPPortConfigAdminP2PPort out;
  stp_MSTP_GetPortConfigAdminP2PPort(&in, &out);
  val_value_t *resval = val_new_value();
  res =  build_to_xml_stp_STPPortConfigAdminP2PPort(
      resval,
    &out);
  return res;
}

static status_t intri_stp_MSTP_SetPortConfigAdminP2PPort_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct stppb_STPPortConfigAdminP2PPort in;
  struct emptypb_Empty out;
  stp_MSTP_SetPortConfigAdminP2PPort(&in, &out);
  val_value_t *resval = val_new_value();
  return res;
}

static status_t intri_stp_MSTP_GetPortConfigAdminEdgePort_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct devicepb_PortList in;
  struct stppb_STPPortConfigAdminEdgePort out;
  stp_MSTP_GetPortConfigAdminEdgePort(&in, &out);
  val_value_t *resval = val_new_value();
  res =  build_to_xml_stp_STPPortConfigAdminEdgePort(
      resval,
    &out);
  return res;
}

static status_t intri_stp_MSTP_SetPortConfigAdminEdgePort_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct stppb_STPPortConfigAdminEdgePort in;
  struct emptypb_Empty out;
  stp_MSTP_SetPortConfigAdminEdgePort(&in, &out);
  val_value_t *resval = val_new_value();
  return res;
}

static status_t intri_stp_MSTP_GetPortConfigAdminPathCost_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct devicepb_PortList in;
  struct stppb_STPPortConfigAdminPathCost out;
  stp_MSTP_GetPortConfigAdminPathCost(&in, &out);
  val_value_t *resval = val_new_value();
  res =  build_to_xml_stp_STPPortConfigAdminPathCost(
      resval,
    &out);
  return res;
}

static status_t intri_stp_MSTP_SetPortConfigAdminPathCost_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct stppb_STPPortConfigAdminPathCost in;
  struct emptypb_Empty out;
  stp_MSTP_SetPortConfigAdminPathCost(&in, &out);
  val_value_t *resval = val_new_value();
  return res;
}

static status_t intri_stp_MSTP_GetPortConfigMSTPDefaultPriority_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct devicepb_PortList in;
  struct stppb_STPPortConfigMSTPDefaultPriority out;
  stp_MSTP_GetPortConfigMSTPDefaultPriority(&in, &out);
  val_value_t *resval = val_new_value();
  res =  build_to_xml_stp_STPPortConfigMSTPDefaultPriority(
      resval,
    &out);
  return res;
}

static status_t intri_stp_MSTP_SetPortConfigMSTPDefaultPriority_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct stppb_STPPortConfigMSTPDefaultPriority in;
  struct emptypb_Empty out;
  stp_MSTP_SetPortConfigMSTPDefaultPriority(&in, &out);
  val_value_t *resval = val_new_value();
  return res;
}

static status_t intri_stp_MSTP_GetPortConfigMSTPPortPriority_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct devicepb_PortList in;
  struct stppb_STPPortConfigMSTPPortPriority out;
  stp_MSTP_GetPortConfigMSTPPortPriority(&in, &out);
  val_value_t *resval = val_new_value();
  res =  build_to_xml_stp_STPPortConfigMSTPPortPriority(
      resval,
    &out);
  return res;
}

static status_t intri_stp_MSTP_SetPortConfigMSTPPortPriority_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct stppb_STPPortConfigMSTPPortPriority in;
  struct emptypb_Empty out;
  stp_MSTP_SetPortConfigMSTPPortPriority(&in, &out);
  val_value_t *resval = val_new_value();
  return res;
}

static status_t intri_stp_MSTP_GetPortConfigMSTPDefaultAdminPathCost_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct devicepb_PortList in;
  struct stppb_STPPortConfigMSTPDefaultAdminPathCost out;
  stp_MSTP_GetPortConfigMSTPDefaultAdminPathCost(&in, &out);
  val_value_t *resval = val_new_value();
  res =  build_to_xml_stp_STPPortConfigMSTPDefaultAdminPathCost(
      resval,
    &out);
  return res;
}

static status_t intri_stp_MSTP_SetPortConfigMSTPDefaultAdminPathCost_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct stppb_STPPortConfigMSTPDefaultAdminPathCost in;
  struct emptypb_Empty out;
  stp_MSTP_SetPortConfigMSTPDefaultAdminPathCost(&in, &out);
  val_value_t *resval = val_new_value();
  return res;
}

static status_t intri_stp_MSTP_GetPortConfigMSTPPortAdminPathCost_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct devicepb_PortList in;
  struct stppb_STPPortConfigMSTPPortAdminPathCost out;
  stp_MSTP_GetPortConfigMSTPPortAdminPathCost(&in, &out);
  val_value_t *resval = val_new_value();
  res =  build_to_xml_stp_STPPortConfigMSTPPortAdminPathCost(
      resval,
    &out);
  return res;
}

static status_t intri_stp_MSTP_SetPortConfigMSTPPortAdminPathCost_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct stppb_STPPortConfigMSTPPortAdminPathCost in;
  struct emptypb_Empty out;
  stp_MSTP_SetPortConfigMSTPPortAdminPathCost(&in, &out);
  val_value_t *resval = val_new_value();
  return res;
}

static status_t intri_stp_MSTP_GetPortConfigBPDUGuard_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct devicepb_PortList in;
  struct stppb_STPPortConfigBPDUGuard out;
  stp_MSTP_GetPortConfigBPDUGuard(&in, &out);
  val_value_t *resval = val_new_value();
  res =  build_to_xml_stp_STPPortConfigBPDUGuard(
      resval,
    &out);
  return res;
}

static status_t intri_stp_MSTP_SetPortConfigBPDUGuard_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct stppb_STPPortConfigBPDUGuard in;
  struct emptypb_Empty out;
  stp_MSTP_SetPortConfigBPDUGuard(&in, &out);
  val_value_t *resval = val_new_value();
  return res;
}

static status_t intri_stp_MSTP_GetPortConfigBPDUReceiveOnly_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct devicepb_PortList in;
  struct stppb_STPPortConfigBPDUReceiveOnly out;
  stp_MSTP_GetPortConfigBPDUReceiveOnly(&in, &out);
  val_value_t *resval = val_new_value();
  res =  build_to_xml_stp_STPPortConfigBPDUReceiveOnly(
      resval,
    &out);
  return res;
}

static status_t intri_stp_MSTP_SetPortConfigBPDUReceiveOnly_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct stppb_STPPortConfigBPDUReceiveOnly in;
  struct emptypb_Empty out;
  stp_MSTP_SetPortConfigBPDUReceiveOnly(&in, &out);
  val_value_t *resval = val_new_value();
  return res;
}

static status_t intri_stp_MSTP_GetPortConfigRestrictTcn_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct devicepb_PortList in;
  struct stppb_STPPortConfigRestrictTcn out;
  stp_MSTP_GetPortConfigRestrictTcn(&in, &out);
  val_value_t *resval = val_new_value();
  res =  build_to_xml_stp_STPPortConfigRestrictTcn(
      resval,
    &out);
  return res;
}

static status_t intri_stp_MSTP_SetPortConfigRestrictTcn_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct stppb_STPPortConfigRestrictTcn in;
  struct emptypb_Empty out;
  stp_MSTP_SetPortConfigRestrictTcn(&in, &out);
  val_value_t *resval = val_new_value();
  return res;
}

static status_t intri_stp_MSTP_GetPortConfigRestrictRoot_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct devicepb_PortList in;
  struct stppb_STPPortConfigRestrictRoot out;
  stp_MSTP_GetPortConfigRestrictRoot(&in, &out);
  val_value_t *resval = val_new_value();
  res =  build_to_xml_stp_STPPortConfigRestrictRoot(
      resval,
    &out);
  return res;
}

static status_t intri_stp_MSTP_SetPortConfigRestrictRoot_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct stppb_STPPortConfigRestrictRoot in;
  struct emptypb_Empty out;
  stp_MSTP_SetPortConfigRestrictRoot(&in, &out);
  val_value_t *resval = val_new_value();
  return res;
}

static status_t intri_stp_MSTP_GetMSTPGroup_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct stppb_MSTPIDList in;
  struct stppb_MSTPGroup out;
  stp_MSTP_GetMSTPGroup(&in, &out);
  val_value_t *resval = val_new_value();
  res =  build_to_xml_stp_MSTPGroup(
      resval,
    &out);
  return res;
}

static status_t intri_stp_MSTP_SetMSTPGroup_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct stppb_MSTPGroup in;
  struct emptypb_Empty out;
  stp_MSTP_SetMSTPGroup(&in, &out);
  val_value_t *resval = val_new_value();
  return res;
}

static status_t intri_stp_MSTP_DeleteMSTPGroup_invoke(
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode) {
  status_t res = NO_ERR;
  struct stppb_MSTPIDList in;
  struct emptypb_Empty out;
  stp_MSTP_DeleteMSTPGroup(&in, &out);
  val_value_t *resval = val_new_value();
  return res;
}

status_t y_intri_stp_init(
    const xmlChar *modname,
    const xmlChar *revision) {
  status_t res = NO_ERR;
  agt_profile_t *agt_profile = agt_get_profile();

  if (xml_strcmp(modname, y_M_intri_stp)) {
    return ERR_NCX_UNKNOWN_MODULE;
  }

  if (revision && xml_strcmp(revision, y_R_intri_stp)) {
    return ERR_NCX_WRONG_VERSION;
  }

  res = ncxmod_load_module(
      y_M_intri_stp,
      y_R_intri_stp,
      &agt_profile->agt_savedevQ,
      &intri_stp_mod);
  if (res != NO_ERR) {
    return res;
  }

  intri_stp_GetConfig_obj = ncx_find_object(
      intri_stp_mod,
      "intri-stp-GetConfig");
  if (intri_stp_GetConfig_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_stp,
      "intri-stp-GetConfig",
      AGT_RPC_PH_INVOKE,
      intri_stp_MSTP_GetConfig_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_stp_SetConfig_obj = ncx_find_object(
      intri_stp_mod,
      "intri-stp-SetConfig");
  if (intri_stp_SetConfig_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_stp,
      "intri-stp-SetConfig",
      AGT_RPC_PH_INVOKE,
      intri_stp_MSTP_SetConfig_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_stp_SetCistConfig_obj = ncx_find_object(
      intri_stp_mod,
      "intri-stp-SetCistConfig");
  if (intri_stp_SetCistConfig_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_stp,
      "intri-stp-SetCistConfig",
      AGT_RPC_PH_INVOKE,
      intri_stp_MSTP_SetCistConfig_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_stp_SetMstiConfig_obj = ncx_find_object(
      intri_stp_mod,
      "intri-stp-SetMstiConfig");
  if (intri_stp_SetMstiConfig_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_stp,
      "intri-stp-SetMstiConfig",
      AGT_RPC_PH_INVOKE,
      intri_stp_MSTP_SetMstiConfig_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_stp_GetCistStatus_obj = ncx_find_object(
      intri_stp_mod,
      "intri-stp-GetCistStatus");
  if (intri_stp_GetCistStatus_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_stp,
      "intri-stp-GetCistStatus",
      AGT_RPC_PH_INVOKE,
      intri_stp_MSTP_GetCistStatus_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_stp_GetMstiStatus_obj = ncx_find_object(
      intri_stp_mod,
      "intri-stp-GetMstiStatus");
  if (intri_stp_GetMstiStatus_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_stp,
      "intri-stp-GetMstiStatus",
      AGT_RPC_PH_INVOKE,
      intri_stp_MSTP_GetMstiStatus_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_stp_RunReconfigPortState_obj = ncx_find_object(
      intri_stp_mod,
      "intri-stp-RunReconfigPortState");
  if (intri_stp_RunReconfigPortState_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_stp,
      "intri-stp-RunReconfigPortState",
      AGT_RPC_PH_INVOKE,
      intri_stp_MSTP_RunReconfigPortState_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_stp_GetBridgeConfigMode_obj = ncx_find_object(
      intri_stp_mod,
      "intri-stp-GetBridgeConfigMode");
  if (intri_stp_GetBridgeConfigMode_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_stp,
      "intri-stp-GetBridgeConfigMode",
      AGT_RPC_PH_INVOKE,
      intri_stp_MSTP_GetBridgeConfigMode_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_stp_SetBridgeConfigMode_obj = ncx_find_object(
      intri_stp_mod,
      "intri-stp-SetBridgeConfigMode");
  if (intri_stp_SetBridgeConfigMode_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_stp,
      "intri-stp-SetBridgeConfigMode",
      AGT_RPC_PH_INVOKE,
      intri_stp_MSTP_SetBridgeConfigMode_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_stp_GetBridgeConfigPriority_obj = ncx_find_object(
      intri_stp_mod,
      "intri-stp-GetBridgeConfigPriority");
  if (intri_stp_GetBridgeConfigPriority_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_stp,
      "intri-stp-GetBridgeConfigPriority",
      AGT_RPC_PH_INVOKE,
      intri_stp_MSTP_GetBridgeConfigPriority_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_stp_SetBridgeConfigPriority_obj = ncx_find_object(
      intri_stp_mod,
      "intri-stp-SetBridgeConfigPriority");
  if (intri_stp_SetBridgeConfigPriority_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_stp,
      "intri-stp-SetBridgeConfigPriority",
      AGT_RPC_PH_INVOKE,
      intri_stp_MSTP_SetBridgeConfigPriority_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_stp_GetBridgeConfigHelloTime_obj = ncx_find_object(
      intri_stp_mod,
      "intri-stp-GetBridgeConfigHelloTime");
  if (intri_stp_GetBridgeConfigHelloTime_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_stp,
      "intri-stp-GetBridgeConfigHelloTime",
      AGT_RPC_PH_INVOKE,
      intri_stp_MSTP_GetBridgeConfigHelloTime_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_stp_SetBridgeConfigHelloTime_obj = ncx_find_object(
      intri_stp_mod,
      "intri-stp-SetBridgeConfigHelloTime");
  if (intri_stp_SetBridgeConfigHelloTime_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_stp,
      "intri-stp-SetBridgeConfigHelloTime",
      AGT_RPC_PH_INVOKE,
      intri_stp_MSTP_SetBridgeConfigHelloTime_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_stp_GetBridgeConfigMaxAge_obj = ncx_find_object(
      intri_stp_mod,
      "intri-stp-GetBridgeConfigMaxAge");
  if (intri_stp_GetBridgeConfigMaxAge_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_stp,
      "intri-stp-GetBridgeConfigMaxAge",
      AGT_RPC_PH_INVOKE,
      intri_stp_MSTP_GetBridgeConfigMaxAge_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_stp_SetBridgeConfigMaxAge_obj = ncx_find_object(
      intri_stp_mod,
      "intri-stp-SetBridgeConfigMaxAge");
  if (intri_stp_SetBridgeConfigMaxAge_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_stp,
      "intri-stp-SetBridgeConfigMaxAge",
      AGT_RPC_PH_INVOKE,
      intri_stp_MSTP_SetBridgeConfigMaxAge_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_stp_GetBridgeConfigForwardDelay_obj = ncx_find_object(
      intri_stp_mod,
      "intri-stp-GetBridgeConfigForwardDelay");
  if (intri_stp_GetBridgeConfigForwardDelay_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_stp,
      "intri-stp-GetBridgeConfigForwardDelay",
      AGT_RPC_PH_INVOKE,
      intri_stp_MSTP_GetBridgeConfigForwardDelay_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_stp_SetBridgeConfigForwardDelay_obj = ncx_find_object(
      intri_stp_mod,
      "intri-stp-SetBridgeConfigForwardDelay");
  if (intri_stp_SetBridgeConfigForwardDelay_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_stp,
      "intri-stp-SetBridgeConfigForwardDelay",
      AGT_RPC_PH_INVOKE,
      intri_stp_MSTP_SetBridgeConfigForwardDelay_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_stp_GetBridgeConfigTxHoldCount_obj = ncx_find_object(
      intri_stp_mod,
      "intri-stp-GetBridgeConfigTxHoldCount");
  if (intri_stp_GetBridgeConfigTxHoldCount_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_stp,
      "intri-stp-GetBridgeConfigTxHoldCount",
      AGT_RPC_PH_INVOKE,
      intri_stp_MSTP_GetBridgeConfigTxHoldCount_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_stp_SetBridgeConfigTxHoldCount_obj = ncx_find_object(
      intri_stp_mod,
      "intri-stp-SetBridgeConfigTxHoldCount");
  if (intri_stp_SetBridgeConfigTxHoldCount_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_stp,
      "intri-stp-SetBridgeConfigTxHoldCount",
      AGT_RPC_PH_INVOKE,
      intri_stp_MSTP_SetBridgeConfigTxHoldCount_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_stp_GetBridgeConfigMSTPRegionName_obj = ncx_find_object(
      intri_stp_mod,
      "intri-stp-GetBridgeConfigMSTPRegionName");
  if (intri_stp_GetBridgeConfigMSTPRegionName_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_stp,
      "intri-stp-GetBridgeConfigMSTPRegionName",
      AGT_RPC_PH_INVOKE,
      intri_stp_MSTP_GetBridgeConfigMSTPRegionName_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_stp_SetBridgeConfigMSTPRegionName_obj = ncx_find_object(
      intri_stp_mod,
      "intri-stp-SetBridgeConfigMSTPRegionName");
  if (intri_stp_SetBridgeConfigMSTPRegionName_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_stp,
      "intri-stp-SetBridgeConfigMSTPRegionName",
      AGT_RPC_PH_INVOKE,
      intri_stp_MSTP_SetBridgeConfigMSTPRegionName_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_stp_GetBridgeConfigMSTPRevisionLevel_obj = ncx_find_object(
      intri_stp_mod,
      "intri-stp-GetBridgeConfigMSTPRevisionLevel");
  if (intri_stp_GetBridgeConfigMSTPRevisionLevel_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_stp,
      "intri-stp-GetBridgeConfigMSTPRevisionLevel",
      AGT_RPC_PH_INVOKE,
      intri_stp_MSTP_GetBridgeConfigMSTPRevisionLevel_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_stp_SetBridgeConfigMSTPRevisionLevel_obj = ncx_find_object(
      intri_stp_mod,
      "intri-stp-SetBridgeConfigMSTPRevisionLevel");
  if (intri_stp_SetBridgeConfigMSTPRevisionLevel_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_stp,
      "intri-stp-SetBridgeConfigMSTPRevisionLevel",
      AGT_RPC_PH_INVOKE,
      intri_stp_MSTP_SetBridgeConfigMSTPRevisionLevel_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_stp_GetBridgeConfigMSTPMaxHops_obj = ncx_find_object(
      intri_stp_mod,
      "intri-stp-GetBridgeConfigMSTPMaxHops");
  if (intri_stp_GetBridgeConfigMSTPMaxHops_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_stp,
      "intri-stp-GetBridgeConfigMSTPMaxHops",
      AGT_RPC_PH_INVOKE,
      intri_stp_MSTP_GetBridgeConfigMSTPMaxHops_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_stp_SetBridgeConfigMSTPMaxHops_obj = ncx_find_object(
      intri_stp_mod,
      "intri-stp-SetBridgeConfigMSTPMaxHops");
  if (intri_stp_SetBridgeConfigMSTPMaxHops_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_stp,
      "intri-stp-SetBridgeConfigMSTPMaxHops",
      AGT_RPC_PH_INVOKE,
      intri_stp_MSTP_SetBridgeConfigMSTPMaxHops_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_stp_GetPortConfigEnabled_obj = ncx_find_object(
      intri_stp_mod,
      "intri-stp-GetPortConfigEnabled");
  if (intri_stp_GetPortConfigEnabled_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_stp,
      "intri-stp-GetPortConfigEnabled",
      AGT_RPC_PH_INVOKE,
      intri_stp_MSTP_GetPortConfigEnabled_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_stp_SetPortConfigEnabled_obj = ncx_find_object(
      intri_stp_mod,
      "intri-stp-SetPortConfigEnabled");
  if (intri_stp_SetPortConfigEnabled_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_stp,
      "intri-stp-SetPortConfigEnabled",
      AGT_RPC_PH_INVOKE,
      intri_stp_MSTP_SetPortConfigEnabled_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_stp_GetPortConfigPriority_obj = ncx_find_object(
      intri_stp_mod,
      "intri-stp-GetPortConfigPriority");
  if (intri_stp_GetPortConfigPriority_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_stp,
      "intri-stp-GetPortConfigPriority",
      AGT_RPC_PH_INVOKE,
      intri_stp_MSTP_GetPortConfigPriority_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_stp_SetPortConfigPriority_obj = ncx_find_object(
      intri_stp_mod,
      "intri-stp-SetPortConfigPriority");
  if (intri_stp_SetPortConfigPriority_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_stp,
      "intri-stp-SetPortConfigPriority",
      AGT_RPC_PH_INVOKE,
      intri_stp_MSTP_SetPortConfigPriority_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_stp_GetPortConfigAdminP2PPort_obj = ncx_find_object(
      intri_stp_mod,
      "intri-stp-GetPortConfigAdminP2PPort");
  if (intri_stp_GetPortConfigAdminP2PPort_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_stp,
      "intri-stp-GetPortConfigAdminP2PPort",
      AGT_RPC_PH_INVOKE,
      intri_stp_MSTP_GetPortConfigAdminP2PPort_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_stp_SetPortConfigAdminP2PPort_obj = ncx_find_object(
      intri_stp_mod,
      "intri-stp-SetPortConfigAdminP2PPort");
  if (intri_stp_SetPortConfigAdminP2PPort_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_stp,
      "intri-stp-SetPortConfigAdminP2PPort",
      AGT_RPC_PH_INVOKE,
      intri_stp_MSTP_SetPortConfigAdminP2PPort_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_stp_GetPortConfigAdminEdgePort_obj = ncx_find_object(
      intri_stp_mod,
      "intri-stp-GetPortConfigAdminEdgePort");
  if (intri_stp_GetPortConfigAdminEdgePort_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_stp,
      "intri-stp-GetPortConfigAdminEdgePort",
      AGT_RPC_PH_INVOKE,
      intri_stp_MSTP_GetPortConfigAdminEdgePort_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_stp_SetPortConfigAdminEdgePort_obj = ncx_find_object(
      intri_stp_mod,
      "intri-stp-SetPortConfigAdminEdgePort");
  if (intri_stp_SetPortConfigAdminEdgePort_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_stp,
      "intri-stp-SetPortConfigAdminEdgePort",
      AGT_RPC_PH_INVOKE,
      intri_stp_MSTP_SetPortConfigAdminEdgePort_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_stp_GetPortConfigAdminPathCost_obj = ncx_find_object(
      intri_stp_mod,
      "intri-stp-GetPortConfigAdminPathCost");
  if (intri_stp_GetPortConfigAdminPathCost_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_stp,
      "intri-stp-GetPortConfigAdminPathCost",
      AGT_RPC_PH_INVOKE,
      intri_stp_MSTP_GetPortConfigAdminPathCost_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_stp_SetPortConfigAdminPathCost_obj = ncx_find_object(
      intri_stp_mod,
      "intri-stp-SetPortConfigAdminPathCost");
  if (intri_stp_SetPortConfigAdminPathCost_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_stp,
      "intri-stp-SetPortConfigAdminPathCost",
      AGT_RPC_PH_INVOKE,
      intri_stp_MSTP_SetPortConfigAdminPathCost_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_stp_GetPortConfigMSTPDefaultPriority_obj = ncx_find_object(
      intri_stp_mod,
      "intri-stp-GetPortConfigMSTPDefaultPriority");
  if (intri_stp_GetPortConfigMSTPDefaultPriority_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_stp,
      "intri-stp-GetPortConfigMSTPDefaultPriority",
      AGT_RPC_PH_INVOKE,
      intri_stp_MSTP_GetPortConfigMSTPDefaultPriority_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_stp_SetPortConfigMSTPDefaultPriority_obj = ncx_find_object(
      intri_stp_mod,
      "intri-stp-SetPortConfigMSTPDefaultPriority");
  if (intri_stp_SetPortConfigMSTPDefaultPriority_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_stp,
      "intri-stp-SetPortConfigMSTPDefaultPriority",
      AGT_RPC_PH_INVOKE,
      intri_stp_MSTP_SetPortConfigMSTPDefaultPriority_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_stp_GetPortConfigMSTPPortPriority_obj = ncx_find_object(
      intri_stp_mod,
      "intri-stp-GetPortConfigMSTPPortPriority");
  if (intri_stp_GetPortConfigMSTPPortPriority_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_stp,
      "intri-stp-GetPortConfigMSTPPortPriority",
      AGT_RPC_PH_INVOKE,
      intri_stp_MSTP_GetPortConfigMSTPPortPriority_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_stp_SetPortConfigMSTPPortPriority_obj = ncx_find_object(
      intri_stp_mod,
      "intri-stp-SetPortConfigMSTPPortPriority");
  if (intri_stp_SetPortConfigMSTPPortPriority_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_stp,
      "intri-stp-SetPortConfigMSTPPortPriority",
      AGT_RPC_PH_INVOKE,
      intri_stp_MSTP_SetPortConfigMSTPPortPriority_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_stp_GetPortConfigMSTPDefaultAdminPathCost_obj = ncx_find_object(
      intri_stp_mod,
      "intri-stp-GetPortConfigMSTPDefaultAdminPathCost");
  if (intri_stp_GetPortConfigMSTPDefaultAdminPathCost_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_stp,
      "intri-stp-GetPortConfigMSTPDefaultAdminPathCost",
      AGT_RPC_PH_INVOKE,
      intri_stp_MSTP_GetPortConfigMSTPDefaultAdminPathCost_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_stp_SetPortConfigMSTPDefaultAdminPathCost_obj = ncx_find_object(
      intri_stp_mod,
      "intri-stp-SetPortConfigMSTPDefaultAdminPathCost");
  if (intri_stp_SetPortConfigMSTPDefaultAdminPathCost_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_stp,
      "intri-stp-SetPortConfigMSTPDefaultAdminPathCost",
      AGT_RPC_PH_INVOKE,
      intri_stp_MSTP_SetPortConfigMSTPDefaultAdminPathCost_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_stp_GetPortConfigMSTPPortAdminPathCost_obj = ncx_find_object(
      intri_stp_mod,
      "intri-stp-GetPortConfigMSTPPortAdminPathCost");
  if (intri_stp_GetPortConfigMSTPPortAdminPathCost_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_stp,
      "intri-stp-GetPortConfigMSTPPortAdminPathCost",
      AGT_RPC_PH_INVOKE,
      intri_stp_MSTP_GetPortConfigMSTPPortAdminPathCost_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_stp_SetPortConfigMSTPPortAdminPathCost_obj = ncx_find_object(
      intri_stp_mod,
      "intri-stp-SetPortConfigMSTPPortAdminPathCost");
  if (intri_stp_SetPortConfigMSTPPortAdminPathCost_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_stp,
      "intri-stp-SetPortConfigMSTPPortAdminPathCost",
      AGT_RPC_PH_INVOKE,
      intri_stp_MSTP_SetPortConfigMSTPPortAdminPathCost_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_stp_GetPortConfigBPDUGuard_obj = ncx_find_object(
      intri_stp_mod,
      "intri-stp-GetPortConfigBPDUGuard");
  if (intri_stp_GetPortConfigBPDUGuard_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_stp,
      "intri-stp-GetPortConfigBPDUGuard",
      AGT_RPC_PH_INVOKE,
      intri_stp_MSTP_GetPortConfigBPDUGuard_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_stp_SetPortConfigBPDUGuard_obj = ncx_find_object(
      intri_stp_mod,
      "intri-stp-SetPortConfigBPDUGuard");
  if (intri_stp_SetPortConfigBPDUGuard_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_stp,
      "intri-stp-SetPortConfigBPDUGuard",
      AGT_RPC_PH_INVOKE,
      intri_stp_MSTP_SetPortConfigBPDUGuard_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_stp_GetPortConfigBPDUReceiveOnly_obj = ncx_find_object(
      intri_stp_mod,
      "intri-stp-GetPortConfigBPDUReceiveOnly");
  if (intri_stp_GetPortConfigBPDUReceiveOnly_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_stp,
      "intri-stp-GetPortConfigBPDUReceiveOnly",
      AGT_RPC_PH_INVOKE,
      intri_stp_MSTP_GetPortConfigBPDUReceiveOnly_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_stp_SetPortConfigBPDUReceiveOnly_obj = ncx_find_object(
      intri_stp_mod,
      "intri-stp-SetPortConfigBPDUReceiveOnly");
  if (intri_stp_SetPortConfigBPDUReceiveOnly_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_stp,
      "intri-stp-SetPortConfigBPDUReceiveOnly",
      AGT_RPC_PH_INVOKE,
      intri_stp_MSTP_SetPortConfigBPDUReceiveOnly_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_stp_GetPortConfigRestrictTcn_obj = ncx_find_object(
      intri_stp_mod,
      "intri-stp-GetPortConfigRestrictTcn");
  if (intri_stp_GetPortConfigRestrictTcn_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_stp,
      "intri-stp-GetPortConfigRestrictTcn",
      AGT_RPC_PH_INVOKE,
      intri_stp_MSTP_GetPortConfigRestrictTcn_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_stp_SetPortConfigRestrictTcn_obj = ncx_find_object(
      intri_stp_mod,
      "intri-stp-SetPortConfigRestrictTcn");
  if (intri_stp_SetPortConfigRestrictTcn_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_stp,
      "intri-stp-SetPortConfigRestrictTcn",
      AGT_RPC_PH_INVOKE,
      intri_stp_MSTP_SetPortConfigRestrictTcn_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_stp_GetPortConfigRestrictRoot_obj = ncx_find_object(
      intri_stp_mod,
      "intri-stp-GetPortConfigRestrictRoot");
  if (intri_stp_GetPortConfigRestrictRoot_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_stp,
      "intri-stp-GetPortConfigRestrictRoot",
      AGT_RPC_PH_INVOKE,
      intri_stp_MSTP_GetPortConfigRestrictRoot_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_stp_SetPortConfigRestrictRoot_obj = ncx_find_object(
      intri_stp_mod,
      "intri-stp-SetPortConfigRestrictRoot");
  if (intri_stp_SetPortConfigRestrictRoot_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_stp,
      "intri-stp-SetPortConfigRestrictRoot",
      AGT_RPC_PH_INVOKE,
      intri_stp_MSTP_SetPortConfigRestrictRoot_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_stp_GetMSTPGroup_obj = ncx_find_object(
      intri_stp_mod,
      "intri-stp-GetMSTPGroup");
  if (intri_stp_GetMSTPGroup_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_stp,
      "intri-stp-GetMSTPGroup",
      AGT_RPC_PH_INVOKE,
      intri_stp_MSTP_GetMSTPGroup_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_stp_SetMSTPGroup_obj = ncx_find_object(
      intri_stp_mod,
      "intri-stp-SetMSTPGroup");
  if (intri_stp_SetMSTPGroup_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_stp,
      "intri-stp-SetMSTPGroup",
      AGT_RPC_PH_INVOKE,
      intri_stp_MSTP_SetMSTPGroup_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  intri_stp_DeleteMSTPGroup_obj = ncx_find_object(
      intri_stp_mod,
      "intri-stp-DeleteMSTPGroup");
  if (intri_stp_DeleteMSTPGroup_obj == NULL) {
    return SET_ERROR(ERR_NCX_DEF_NOT_FOUND);
  }

  res = agt_rpc_register_method(
      y_M_intri_stp,
      "intri-stp-DeleteMSTPGroup",
      AGT_RPC_PH_INVOKE,
      intri_stp_MSTP_DeleteMSTPGroup_invoke);
  if (res != NO_ERR) {
    return SET_ERROR(res);
  }

  return res;
}

void y_intri_stp_cleanup(void) {
  agt_rpc_unregister_method(
      y_M_intri_stp,
      "intri-stp-GetConfig");

  agt_rpc_unregister_method(
      y_M_intri_stp,
      "intri-stp-SetConfig");

  agt_rpc_unregister_method(
      y_M_intri_stp,
      "intri-stp-SetCistConfig");

  agt_rpc_unregister_method(
      y_M_intri_stp,
      "intri-stp-SetMstiConfig");

  agt_rpc_unregister_method(
      y_M_intri_stp,
      "intri-stp-GetCistStatus");

  agt_rpc_unregister_method(
      y_M_intri_stp,
      "intri-stp-GetMstiStatus");

  agt_rpc_unregister_method(
      y_M_intri_stp,
      "intri-stp-RunReconfigPortState");

  agt_rpc_unregister_method(
      y_M_intri_stp,
      "intri-stp-GetBridgeConfigMode");

  agt_rpc_unregister_method(
      y_M_intri_stp,
      "intri-stp-SetBridgeConfigMode");

  agt_rpc_unregister_method(
      y_M_intri_stp,
      "intri-stp-GetBridgeConfigPriority");

  agt_rpc_unregister_method(
      y_M_intri_stp,
      "intri-stp-SetBridgeConfigPriority");

  agt_rpc_unregister_method(
      y_M_intri_stp,
      "intri-stp-GetBridgeConfigHelloTime");

  agt_rpc_unregister_method(
      y_M_intri_stp,
      "intri-stp-SetBridgeConfigHelloTime");

  agt_rpc_unregister_method(
      y_M_intri_stp,
      "intri-stp-GetBridgeConfigMaxAge");

  agt_rpc_unregister_method(
      y_M_intri_stp,
      "intri-stp-SetBridgeConfigMaxAge");

  agt_rpc_unregister_method(
      y_M_intri_stp,
      "intri-stp-GetBridgeConfigForwardDelay");

  agt_rpc_unregister_method(
      y_M_intri_stp,
      "intri-stp-SetBridgeConfigForwardDelay");

  agt_rpc_unregister_method(
      y_M_intri_stp,
      "intri-stp-GetBridgeConfigTxHoldCount");

  agt_rpc_unregister_method(
      y_M_intri_stp,
      "intri-stp-SetBridgeConfigTxHoldCount");

  agt_rpc_unregister_method(
      y_M_intri_stp,
      "intri-stp-GetBridgeConfigMSTPRegionName");

  agt_rpc_unregister_method(
      y_M_intri_stp,
      "intri-stp-SetBridgeConfigMSTPRegionName");

  agt_rpc_unregister_method(
      y_M_intri_stp,
      "intri-stp-GetBridgeConfigMSTPRevisionLevel");

  agt_rpc_unregister_method(
      y_M_intri_stp,
      "intri-stp-SetBridgeConfigMSTPRevisionLevel");

  agt_rpc_unregister_method(
      y_M_intri_stp,
      "intri-stp-GetBridgeConfigMSTPMaxHops");

  agt_rpc_unregister_method(
      y_M_intri_stp,
      "intri-stp-SetBridgeConfigMSTPMaxHops");

  agt_rpc_unregister_method(
      y_M_intri_stp,
      "intri-stp-GetPortConfigEnabled");

  agt_rpc_unregister_method(
      y_M_intri_stp,
      "intri-stp-SetPortConfigEnabled");

  agt_rpc_unregister_method(
      y_M_intri_stp,
      "intri-stp-GetPortConfigPriority");

  agt_rpc_unregister_method(
      y_M_intri_stp,
      "intri-stp-SetPortConfigPriority");

  agt_rpc_unregister_method(
      y_M_intri_stp,
      "intri-stp-GetPortConfigAdminP2PPort");

  agt_rpc_unregister_method(
      y_M_intri_stp,
      "intri-stp-SetPortConfigAdminP2PPort");

  agt_rpc_unregister_method(
      y_M_intri_stp,
      "intri-stp-GetPortConfigAdminEdgePort");

  agt_rpc_unregister_method(
      y_M_intri_stp,
      "intri-stp-SetPortConfigAdminEdgePort");

  agt_rpc_unregister_method(
      y_M_intri_stp,
      "intri-stp-GetPortConfigAdminPathCost");

  agt_rpc_unregister_method(
      y_M_intri_stp,
      "intri-stp-SetPortConfigAdminPathCost");

  agt_rpc_unregister_method(
      y_M_intri_stp,
      "intri-stp-GetPortConfigMSTPDefaultPriority");

  agt_rpc_unregister_method(
      y_M_intri_stp,
      "intri-stp-SetPortConfigMSTPDefaultPriority");

  agt_rpc_unregister_method(
      y_M_intri_stp,
      "intri-stp-GetPortConfigMSTPPortPriority");

  agt_rpc_unregister_method(
      y_M_intri_stp,
      "intri-stp-SetPortConfigMSTPPortPriority");

  agt_rpc_unregister_method(
      y_M_intri_stp,
      "intri-stp-GetPortConfigMSTPDefaultAdminPathCost");

  agt_rpc_unregister_method(
      y_M_intri_stp,
      "intri-stp-SetPortConfigMSTPDefaultAdminPathCost");

  agt_rpc_unregister_method(
      y_M_intri_stp,
      "intri-stp-GetPortConfigMSTPPortAdminPathCost");

  agt_rpc_unregister_method(
      y_M_intri_stp,
      "intri-stp-SetPortConfigMSTPPortAdminPathCost");

  agt_rpc_unregister_method(
      y_M_intri_stp,
      "intri-stp-GetPortConfigBPDUGuard");

  agt_rpc_unregister_method(
      y_M_intri_stp,
      "intri-stp-SetPortConfigBPDUGuard");

  agt_rpc_unregister_method(
      y_M_intri_stp,
      "intri-stp-GetPortConfigBPDUReceiveOnly");

  agt_rpc_unregister_method(
      y_M_intri_stp,
      "intri-stp-SetPortConfigBPDUReceiveOnly");

  agt_rpc_unregister_method(
      y_M_intri_stp,
      "intri-stp-GetPortConfigRestrictTcn");

  agt_rpc_unregister_method(
      y_M_intri_stp,
      "intri-stp-SetPortConfigRestrictTcn");

  agt_rpc_unregister_method(
      y_M_intri_stp,
      "intri-stp-GetPortConfigRestrictRoot");

  agt_rpc_unregister_method(
      y_M_intri_stp,
      "intri-stp-SetPortConfigRestrictRoot");

  agt_rpc_unregister_method(
      y_M_intri_stp,
      "intri-stp-GetMSTPGroup");

  agt_rpc_unregister_method(
      y_M_intri_stp,
      "intri-stp-SetMSTPGroup");

  agt_rpc_unregister_method(
      y_M_intri_stp,
      "intri-stp-DeleteMSTPGroup");

}

