<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
          "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:py="http://purl.org/kid/ns#"
      py:extends="'master.kid'">
  <head>
    <meta content="text/html; charset=utf-8"
	  http-equiv="Content-Type" py:replace="''"/>
    <link media="screen" href="/tg_widgets/turbogears.widgets/tabber/tabber.css"
	  type="text/css" rel="stylesheet"/>
    <title>Netconf Central YANG Database</title>
  </head>
  <body>
    <div class="ncdocs">
      <h1>YANG Database Tools</h1>

      <img src="${tg.url('/static/images/ncorgdb.png')}" 
	   border="2" alt="netconfcentral database"/>
      <p>&nbsp;</p>
      <div>
	<h2>
          <a href="http://www.ibr.cs.tu-bs.de/projects/libsmi/smidump.html">
	    smidump
	  </a>
	</h2>
	<p>
          The <b>smidump</b> program is used to convert
          <a href="http://tools.ietf.org/html/rfc2578">SMIv2</a> source files
          to YANG modules.
	</p>
	<p>
	  This program is part of the
	  <a href="http://www.ibr.cs.tu-bs.de/projects/libsmi/">libsmi</a>
	  library, and is can be freely obtained from the libsmi
	  <a href="http://www.ibr.cs.tu-bs.de/projects/libsmi/download.html">
	    download</a> page.
	  It is also available in many Linux distributions.
	</p>
	<p>
	  The YANG module sources generated from SMIv2 are created
	  with smidump, using the following Makefile commands,
	  run from a work directory:
	</p>
	<pre>

    TARGET=../modules/ietf

    PLAINS = $(patsubst %.txt,%,$(wildcard *.txt))

    YANGS = $(patsubst %,$(TARGET)/%.yang,$(wildcard *-*))

    # generate the YANG modules in the target directory
    $(TARGET)/%.yang: %
         smidump -f yang --yang-smi-extensions \
            --yang-indent 3 --output $@ ./$&lt; 

    # convert FOO-MIB.txt to FOO-MIB
    %: %.txt
          mv $&lt; $@

	</pre>
      </div>
      <div>
	<h2>
          <a href="${tg.url('/yangdump_manual')}">yangdump</a>
	</h2>
	<p>
          The <b>yangdump</b> program is used to convert
          <a href="http://www.yang-central.org/">YANG</a> source files
          to <a href="http://www.w3.org/TR/xmlschema-0/">
            XML Schema 1.0 (XSD)</a>,  or
          <a href="http://www.w3.org/TR/xhtml1/">
            Extensible HyperText Markup Language 1.0 (XHTML)</a>, 
          and other formats.
	</p>
	<p>
	  The HTML for YANG modules used in most WEB pages is
	  generated with the following command line, run from
	  the modules sub-directory.
	</p>
	<pre>

    modules> yangdump --format=html --subtree=. --defnames \
      --output=$(HTML_TARGET) --log-level=info --html-div \
      --html-toc=menu --urlstart=/modules --simurls

	</pre>
	<p>
	  The HTML for the 'cooked' YANG modules WEB pages is
	  generated with the following command line, run from
	  the modules sub-directory.
	</p>
	<pre>

    modules> yangdump --format=html --subtree=. --defnames \
	--output=$(COOKEDHTML_TARGET) --log-level=info --html-div \
	--html-toc=menu --urlstart=/modules --simurls --objview=cooked

	</pre>
	<p>
	  The XSDs for the YANG modules are
	  generated with the following command line, run from
	  the modules sub-directory.
	</p>
	<pre>

    modules> yangdump --format=xsd --subtree=. --defnames \
	--output=$(XSD_TARGET) --urlstart=/xsd --log-level=info

	</pre>
	<p>
	  The source files available for the modules used in the database are
	  directly copied (with versions in the filenames) with
	  the following command line, run from the modules sub-directory.
	</p>
	<pre>

    modules> yangdump --format=copy --subtree=. --defnames \
	--output=$(COPY_TARGET) --log-level=info 

	</pre>
	<p>
	  The internal SQL database information is generated with
	  the following command line, run from the modules sub-directory.
	  This database is still under development, so it is not
	  available online at this time.  (Warning: this command
	  will generate a very large SQL file!)
	</p>
	<pre>

    modules> yangdump --format=sqldb --subtree=. \
	--output=$(SQLDB_TARGET) --log-level=info \
	--urlstart=/modules --simurls

	</pre>
	<p>
	  The following limitations apply to the HTML and YANG
	  files generated by yangdump:
	</p>
	<ul>
	  <li>
	    Comments are not saved, and are not used in the
	    generated output.
	  </li>
	  <li>
	    The order of YANG clauses are not preserved.
	    The canonical clause order defined
	    in the YANG ABNF is used instead.
	  </li>
	  <li>
	    String concatenation is not preserved.  The
	    converted string is used in the generated output.
	  </li>
	</ul>
	<p>
	  These limitations will be addressed in a future
	  program version.
	</p>
      </div>
    </div>
  </body>
</html>
