// Code generated by protoc-gen-yang(*.h) DO NOT EDIT.

#ifndef _H_sercom_rmon_trans
#define _H_sercom_rmon_trans

/*****************************************************************************************************
 * Copyright (C) 2017-2022 by Intrising
 *  - ian0113@intrising.com.tw
 * 
 * Generated by protoc-gen-yang@gen-yang
 * 
 *****************************************************************************************************/

#include <libxml/xmlstring.h>
#include "agt.h"
#include "agt_cb.h"
#include "agt_rpc.h"
#include "agt_timer.h"
#include "agt_util.h"
#include "dlq.h"

#include "../../../../../../../../.libintrishare/libintrishare.h"

extern status_t build_to_xml_rmon_IngressEntry(
    val_value_t *parentval,
    struct rmonpb_IngressEntry *entry);
extern status_t build_to_xml_rmon_Ingress(
    val_value_t *parentval,
    struct rmonpb_Ingress *entry);
extern status_t build_to_xml_rmon_EgressEntry(
    val_value_t *parentval,
    struct rmonpb_EgressEntry *entry);
extern status_t build_to_xml_rmon_Egress(
    val_value_t *parentval,
    struct rmonpb_Egress *entry);
extern status_t build_to_xml_rmon_HistogramEntry(
    val_value_t *parentval,
    struct rmonpb_HistogramEntry *entry);
extern status_t build_to_xml_rmon_Histogram(
    val_value_t *parentval,
    struct rmonpb_Histogram *entry);
extern status_t build_to_xml_rmon_UtilizationRate(
    val_value_t *parentval,
    struct rmonpb_UtilizationRate *entry);
extern status_t build_to_xml_rmon_UtilizationEntry(
    val_value_t *parentval,
    struct rmonpb_UtilizationEntry *entry);
extern status_t build_to_xml_rmon_Utilization(
    val_value_t *parentval,
    struct rmonpb_Utilization *entry);

extern status_t build_to_priv_rmon_IngressEntry(
    val_value_t *parentval,
    struct rmonpb_IngressEntry *entry);
extern status_t build_to_priv_rmon_Ingress(
    val_value_t *parentval,
    struct rmonpb_Ingress *entry);
extern status_t build_to_priv_rmon_EgressEntry(
    val_value_t *parentval,
    struct rmonpb_EgressEntry *entry);
extern status_t build_to_priv_rmon_Egress(
    val_value_t *parentval,
    struct rmonpb_Egress *entry);
extern status_t build_to_priv_rmon_HistogramEntry(
    val_value_t *parentval,
    struct rmonpb_HistogramEntry *entry);
extern status_t build_to_priv_rmon_Histogram(
    val_value_t *parentval,
    struct rmonpb_Histogram *entry);
extern status_t build_to_priv_rmon_UtilizationRate(
    val_value_t *parentval,
    struct rmonpb_UtilizationRate *entry);
extern status_t build_to_priv_rmon_UtilizationEntry(
    val_value_t *parentval,
    struct rmonpb_UtilizationEntry *entry);
extern status_t build_to_priv_rmon_Utilization(
    val_value_t *parentval,
    struct rmonpb_Utilization *entry);

#endif /* _H_sercom_rmon_trans */

